import type {Stage,Tool} from '../../model';
import type {PlanEntry} from '../../build/plan';

/**
 * A hands-on task for every lesson whose picture sequence and topic model do not already give one.
 * Each task practises the lesson's own objective with fixed, friendly numbers: comparing numbers by
 * their position on a line, sharing 13 into pairs to meet odd numbers, opening an angle to the third
 * angle of a triangle. The lesson tests prove that every goal starts unmet and can be reached with
 * the controls the model actually offers.
 */
type Explore=Extract<Stage,{kind:'explore'}>;
type Of<K extends Tool['kind']>=Extract<Tool,{kind:K}>;
type Words={title:string;text:string;hint:string;success:string};
type Side={x:number;n:number};

const W=(title:string,text:string,hint:string,success:string):Words=>({title,text,hint,success});
const task=(w:Words,tool:Tool,goal:(t:Tool)=>boolean):Explore=>({kind:'explore',title:w.title,text:w.text,tool,goal,goalHint:w.hint,success:w.success});
const is=<K extends Tool['kind']>(kind:K,test:(t:Of<K>)=>boolean)=>(t:Tool)=>t.kind===kind&&test(t as Of<K>);
const landing=(t:Of<'line'>)=>t.start+t.jumps.reduce((s,j)=>s+j,0);

// The line's buttons jump ±1 and ±10, so each journey below needs at most six presses.
const line=(w:Words,min:number,max:number,start:number,end:number,step?:number)=>task(w,{kind:'line',min,max,start,jumps:[],...(step?{step}:{})},is('line',t=>landing(t)===end));
const pattern=(w:Words,min:number,max:number,start:number,jump:number,terms:number)=>task(w,{kind:'line',min,max,start,jumps:[],step:10},is('line',t=>t.jumps.length===terms&&t.jumps.every(j=>j===jump)));
const counters=(w:Words,target:number,frame:10|20=10)=>task(w,{kind:'counters',count:0,frame},is('counters',t=>t.count===target));
const hundred=(w:Words,target:number,hideValue=false)=>task(w,{kind:'hundred',shaded:0,...(hideValue?{hideValue}:{})},is('hundred',t=>t.shaded===target));
const angle=(w:Words,from:number,to:number)=>task(w,{kind:'geometry',mode:'angle',a:from,b:0},is('geometry',t=>t.mode==='angle'&&t.a===to));
const clock=(w:Words,from:number,to:number)=>task(w,{kind:'geometry',mode:'clock',a:from,b:0},is('geometry',t=>t.mode==='clock'&&t.a===to));
const ruler=(w:Words,from:number,to:number)=>task(w,{kind:'geometry',mode:'ruler',a:from,b:0},is('geometry',t=>t.mode==='ruler'&&t.a===to));
const rectangle=(w:Words,a:number,b:number,done:(a:number,b:number)=>boolean)=>task(w,{kind:'geometry',mode:'rectangle',a,b},is('geometry',t=>t.mode==='rectangle'&&done(t.a,t.b)));
// Width and height are adjustable; the depth `c` is fixed by the task.
const cuboid=(w:Words,[a,b,c]:[number,number,number],[width,height]:[number,number])=>task(w,{kind:'geometry',mode:'solid',a,b,c},is('geometry',t=>t.mode==='solid'&&t.a===width&&t.b===height));
const strips=(w:Words,denominators:number[],shaded:number[],target:number[])=>task(w,{kind:'fractions',denominators,shaded},is('fractions',t=>t.shaded.length===target.length&&t.shaded.every((n,i)=>n===target[i])));
const chart=(w:Words,wholes:number,digits:number[],target:number[])=>task(w,{kind:'place',wholes,digits},is('place',t=>t.digits.every((d,i)=>d===target[i])));
const share=(w:Words,total:number,people:number,each:number)=>task(w,{kind:'share',total,people,given:Array(people).fill(0),mode:'share'},is('share',t=>t.given.length===people&&t.given.every(g=>g===each)));
const groups=(w:Words,size:number,count:number)=>task(w,{kind:'groups',groups:1,size},is('groups',t=>t.groups===count&&t.size===size));
const array=(w:Words,rows:number,cols:number,target:[number,number])=>task(w,{kind:'array',rows,cols},is('array',t=>t.rows===target[0]&&t.cols===target[1]));
// One row of equal blocks, each worth `unitValue`: a bar on a scaled graph, or 25% of a whole.
const blocks=(w:Words,name:string,unitValue:number,count:number)=>task(w,{kind:'ratio',names:[name],units:[1],unitValue},is('ratio',t=>t.units[0]===count));
const same=(a:Side,b:Side)=>a.x===b.x&&a.n===b.n;
const balance=(w:Words,left:Side,right:Side,xValue:number,goal:[Side,Side])=>task(w,{kind:'balance',left,right,xValue},is('balance',t=>same(t.left,goal[0])&&same(t.right,goal[1])));
const triangles=(w:Words,base:number,height:number)=>task(w,{kind:'triangle-pair',base,height,joined:false},is('triangle-pair',t=>t.joined));
const join=W('','','Press “Join the matching triangle”.','');

const ACTIVITIES:Record<string,()=>Explore>={
 // Whole numbers: place value, number names, comparing and patterns on a number line.
 'p1s-wn-04':()=>line(W('Which number is greater?','Start at 38. Jump along the line to 43. Watch which way you move.','Jump forward, to the right, until the line says “At 43”.','43 is to the right of 38, so 43 is greater: 38 < 43. Compare the tens first: 4 tens is more than 3 tens.'),30,70,38,43),
 'p1s-wn-06':()=>line(W('Walk to the sixth child','Children stand in a queue. Each jump of 1 moves to the next child. Start at 0, before the queue, and jump to the sixth child. Say “first, second, third …” as you jump.','Make one jump of +1 for each child: first, second, third, fourth, fifth, sixth.','You reached the sixth child. “Sixth” names a place in the queue. It took 6 jumps, one for each child from the first to the sixth.'),0,10,0,6),
 'p2s-wn-01':()=>line(W('Build 342 on the line','Start at 300. Use jumps of 10 and 1 to reach 342. Count the tens first, then the ones.','Make 4 jumps of +10 to reach 340, then 2 jumps of +1.','342 = 3 hundreds + 4 tens + 2 ones. Four jumps of ten and two jumps of one took you from 300 to 342.'),300,400,300,342,10),
 'p2s-wn-02':()=>line(W('Hundreds, tens and ones','Start at 500, which is 5 hundreds. Add 2 tens and 3 ones with jumps. Where do you land?','Make 2 jumps of +10, then 3 jumps of +1.','You landed on 523: 5 hundreds, 2 tens and 3 ones. Each jump of 10 adds one ten, and each jump of 1 adds one one.'),500,600,500,523,10),
 'p2s-wn-03':()=>line(W('Find the number from its name','Start at 700. Jump to seven hundred and thirty-one.','“Thirty-one” means 3 tens and 1 one. Make 3 jumps of +10 and 1 jump of +1.','Seven hundred and thirty-one is written 731: 7 hundreds, 3 tens and 1 one.'),700,800,700,731,10),
 'p2s-wn-04':()=>line(W('Which number is greater?','Start at 426. Jump to 446. Which way did you move, and what does that tell you?','Make 2 jumps of +10: 426, 436, 446.','446 is to the right of 426, so 446 > 426. The hundreds are the same, so compare the tens: 4 tens is more than 2 tens.'),400,500,426,446,10),
 'p2s-wn-06':()=>share(W('Can 13 be shared equally by 2?','Share 13 counters between 2 friends so that both get the same number. Keep going until you cannot give both friends another counter.','Press “Give one to everyone” until fewer than 2 counters are left.','Each friend has 6 and 1 counter is left over. 13 cannot be split into two equal groups, so 13 is odd. An even number, such as 12, splits into two equal groups with none left over.'),13,2,6),
 'p3s-wn-01':()=>line(W('Build 3432 on the line','Start at 3400: 3 thousands and 4 hundreds. Add 3 tens and 2 ones with jumps.','Make 3 jumps of +10, then 2 jumps of +1.','3432 = 3 thousands + 4 hundreds + 3 tens + 2 ones. The jumps added the tens and ones to 3400.'),3400,3500,3400,3432,10),
 'p3s-wn-02':()=>line(W('Find the number from its name','Start at 5600. Jump to five thousand, six hundred and twenty-four.','“Twenty-four” means 2 tens and 4 ones: 2 jumps of +10, then 4 jumps of +1.','Five thousand, six hundred and twenty-four is written 5624. Read the thousands, then the hundreds, then the tens and ones.'),5600,5700,5600,5624,10),
 'p3s-wn-03':()=>pattern(W('Continue the pattern','The pattern is 3410, 3420, 3430, … You are at 3430. Make the next two numbers in the pattern.','Each number is 10 more than the one before. Make exactly 2 jumps of +10.','3440 and 3450 come next. The rule is “add 10”, so only the tens digit changes each time.'),3400,3500,3430,10,2),
 'p4s-wn-01':()=>line(W('Place and compare','Start at 45230. Jump to 45251. Then decide which number is greater.','Make 2 jumps of +10 and 1 jump of +1.','45251 is to the right of 45230, so 45251 > 45230. The ten thousands, thousands and hundreds match, so the tens decide: 5 tens is more than 3 tens.'),45220,45270,45230,45251,10),
 'p4s-wn-04':()=>line(W('Find the number from its name','Start at 72100. Jump to seventy-two thousand, one hundred and twenty-three.','“Twenty-three” means 2 tens and 3 ones: 2 jumps of +10, then 3 jumps of +1.','Seventy-two thousand, one hundred and twenty-three is written 72123. The word “thousand” tells you where the thousands end.'),72100,72150,72100,72123,10),
 'p5s-wn-01':()=>line(W('Find the number from its name','Start at 4,305,200. Jump to four million, three hundred and five thousand, two hundred and fourteen.','“Fourteen” means 1 ten and 4 ones: 1 jump of +10, then 4 jumps of +1.','You reached 4,305,214. “Million” names the first digit, “thousand” names the next group of three digits (305), and the last group is 214.'),4305200,4305250,4305200,4305214,10),
 'p5f-wn-01':()=>line(W('Find the number from its name','Start at 2,008,300. Jump to two million, eight thousand, three hundred and twenty-four.','“Twenty-four” means 2 tens and 4 ones: 2 jumps of +10, then 4 jumps of +1.','You reached 2,008,324. The thousands group is 008: the zeros keep the empty hundred-thousands and ten-thousands places.'),2008300,2008350,2008300,2008324,10),
 'p5f-wn-02':()=>pattern(W('Continue the pattern backwards','The pattern is 52780, 52770, 52760, … You are at 52760. Make the next two numbers in the pattern.','Each number is 10 less than the one before. Make exactly 2 jumps of −10.','52750 and 52740 come next. The rule is “subtract 10”, so the tens digit goes down by 1 each time.'),52720,52770,52760,-10,2),
 'p5s-wn-02':()=>array(W('How many tens make 60?','Arrange 60 counters in rows of 10. Keep 10 in each row and add rows until there are 60.','Keep 10 columns and add one row at a time: 10, 20, 30, … until you reach 60.','6 rows of 10 make 60, so 60 ÷ 10 = 6. Dividing by 10 counts the tens, so each digit moves one place to the right. In the same way 6000 ÷ 1000 = 6, because 6000 is 6 thousands.'),1,10,[6,10]),
 'p5s-wn-03':()=>array(W('Multiply before you add','In 5 + 8 × 6, the multiplication is worked out first. Build 8 × 6 as an array: 8 rows of 6.','Keep 6 in each row. Add rows until there are 8.','8 × 6 = 48, then 5 + 48 = 53. The array keeps the 8 rows of 6 together. Adding first would give 13 × 6 = 78, which wrongly counts the 5 six times.'),1,6,[8,6]),

 // Addition and subtraction: taking away, bonds, the equals sign and mental jumps.
 'p1s-as-02':()=>task(W('Take 4 away','There are 12 counters. Tap 4 of them to take them away. Then count the blue counters that stay.','Cross out exactly 4 counters. Any 4 will do.','12 − 4 = 8. Taking away 4 leaves 8, whichever 4 you choose.'),{kind:'take-away',start:12,removed:[]},is('take-away',t=>t.removed.length===4)),
 'p1s-as-03':()=>task(W('Split 8 into two parts','The whole is 8. Move counters from the first part to the second part until the parts are 5 and 3.','Tap a counter in the first part to move it across. Move 3 counters.','5 and 3 make 8. One number bond gives four number sentences: 5 + 3 = 8, 3 + 5 = 8, 8 − 3 = 5 and 8 − 5 = 3.'),{kind:'bond',whole:8,parts:[8,0]},is('bond',t=>t.parts[0]===5&&t.parts[1]===3)),
 'p1s-as-04':()=>balance(W('Make both sides equal','The left pan has 10 and the right pan has 8. The sign ≠ means “is not equal to”. Take counters off the left pan only until both sides are equal.','Use “Take 1 off the left only” until both sides show 8.','Now 8 = 8. The = sign means both sides have the same value. You took away 2, so 10 − 2 = 8.'),{x:0,n:10},{x:0,n:8},1,[{x:0,n:8},{x:0,n:8}]),
 'p1s-as-05':()=>line(W('Add 23 on the line','Start at 34. Add 23 by jumping 2 tens, then 3 ones.','Make 2 jumps of +10 (44, 54), then 3 jumps of +1 (55, 56, 57).','34 + 23 = 57. Adding the tens first and then the ones keeps each step easy.'),20,70,34,57),
 'p1s-as-06':()=>counters(W('Add three numbers','Find 4 + 6 + 2. Put in 4 counters, then 6 more, then 2 more. Look for a ten as you go.','4 and 6 fill one ten frame. Then add 2 more in the second frame.','4 + 6 = 10, and 10 + 2 = 12. Finding two numbers that make ten makes adding three numbers easier.'),12,20),
 'p1s-as-08':()=>line(W('Take away tens and ones','Start at 68. Take away 22: jump back 2 tens, then 2 ones.','Make 2 jumps of −10 (58, 48), then 2 jumps of −1 (47, 46).','68 − 22 = 46. The tens digit went down by 2 and the ones digit went down by 2. No regrouping was needed, because there were enough ones to take 2 away.'),40,70,68,46),
 'p2s-as-01':()=>line(W('Add 23 to 346','Start at 346. Add 23 with jumps: 2 tens, then 3 ones.','Make 2 jumps of +10 (356, 366), then 3 jumps of +1.','346 + 23 = 369. The hundreds stay the same; only the tens and ones change.'),300,400,346,369,10),
 'p2s-as-02':()=>line(W('Add 3 tens in your head','Start at 523. Add 30 in your head, then check it with jumps of 10.','30 is 3 tens. Make 3 jumps of +10.','523 + 30 = 553. Only the tens digit changed: 2 tens became 5 tens.'),500,600,523,553,10),
 'p3s-as-01':()=>line(W('Add 27 with a friendly jump','Start at 2436. Add 27. Try adding 30, then taking 3 back.','Make 3 jumps of +10 to 2466, then 3 jumps of −1 to 2463.','2436 + 27 = 2463. Adding 30 and taking back 3 adds 27 altogether. In the column method, 6 ones + 7 ones = 13 ones, so 1 ten is regrouped.'),2400,2500,2436,2463,10),
 'p3s-as-02':()=>line(W('Subtract 29 in your head','Start at 83. Subtract 29: take away 30, then add back 1.','Make 3 jumps of −10 to 53, then 1 jump of +1.','83 − 29 = 54. Taking away 30 takes away 1 too many, so 1 is added back.'),40,90,83,54),
 'p5f-as-01':()=>line(W('Add 33 to 615','Start at 615. Add 33 with jumps of 10 and 1.','Make 3 jumps of +10 (625, 635, 645), then 3 jumps of +1.','615 + 33 = 648: 3 tens and 3 ones were added. Check by subtracting: 648 − 33 = 615.'),600,700,615,648,10),
 'p5f-as-02':()=>line(W('Subtract 2 tens in your head','Start at 274. Subtract 20 in your head, then check it with jumps.','20 is 2 tens. Make 2 jumps of −10.','274 − 20 = 254. Only the tens digit changes: 7 tens become 5 tens.'),200,300,274,254,10),

 // Multiplication and division, multiples and factors.
 'p3s-md-03':()=>array(W('One fact, many places','Build 3 rows of 4. You will use this fact to multiply bigger numbers.','Keep 4 in each row and add rows until there are 3.','3 × 4 = 12. So 3 × 40 = 12 tens = 120 and 3 × 400 = 12 hundreds = 1200. In 3 × 444 each place uses the same fact: 1200 + 120 + 12 = 1332.'),1,4,[3,4]),
 'p4s-md-01':()=>array(W('One fact, many places','Build 6 rows of 7. You will use this fact to multiply a four-digit number.','Keep 7 in each row and add rows until there are 6.','6 × 7 = 42. So 6 × 70 = 420, 6 × 700 = 4200 and 6 × 7000 = 42 000. In 7777 × 6 each place uses this fact: 42 000 + 4200 + 420 + 42 = 46 662.'),1,7,[6,7]),
 'p4s-md-02':()=>rectangle(W('Split into tens and ones','Use an area model to find 12 × 12. Start with the 10 by 10 square and make it 12 by 12.','Set the width to 12 and the height to 12.','12 × 12 splits into 10 × 10 = 100, two strips of 10 × 2 = 20 and a corner of 2 × 2 = 4: 100 + 20 + 20 + 4 = 144. For 402 × 67, split 67 into 60 + 7 in the same way.'),10,10,(a,b)=>a===12&&b===12),
 'p5f-md-01':()=>array(W('Put 24 into 4 rows','Put 24 counters into 4 equal rows. Keep 4 rows and add columns until the array holds 24.','Add one column at a time: 4, 8, 12, … until you reach 24.','4 rows of 6 make 24, so 24 ÷ 4 = 6 and 4 × 6 = 24. Multiplication and division use the same array.'),4,1,[4,6]),
 'p5f-md-02':()=>groups(W('10 groups of 6','Make 10 groups of 6. Compare the total with 6.','Keep 6 in each group and add groups until there are 10.','10 × 6 = 60: the 6 ones become 6 tens. In the same way 6 × 100 = 600 and 6 × 1000 = 6000, and 60 ÷ 10 = 6.'),6,10),
 'p4s-fact-03':()=>groups(W('Multiples of 4','Multiples of 4 are 4, 8, 12, 16, 20, … Make groups of 4 until the total is 20.','Keep 4 in each group and add groups: 4, 8, 12, 16, 20.','5 groups of 4 make 20, so 20 is the 5th multiple of 4. 20 is also 4 groups of 5, so 20 is a common multiple of 4 and 5.'),4,5),
 'p5f-fact-02':()=>groups(W('A common multiple of 6 and 8','Make groups of 6. Stop at the first total that is also a multiple of 8 (8, 16, 24, 32, …).','Check each total: 6, 12, 18, 24. Which one is also in the 8 times table?','4 groups of 6 make 24, and 24 = 3 × 8. So 24 is the smallest common multiple of 6 and 8.'),6,4),

 // Fractions.
 'p3s-frac-01':()=>strips(W('Find an equal fraction','The top strip shows 1/3. Shade the sixths strip to cover the same length.','Each third splits into 2 sixths. Shade 2 sixths.','1/3 = 2/6: the shaded lengths match. Multiplying the numerator and the denominator by 2 gives an equivalent fraction.'),[3,6],[1,0],[1,2]),
 'p3s-frac-04':()=>strips(W('Find the missing numerator','Complete 1/2 = □/8. The top strip shows 1/2. Shade the eighths strip to the same length.','Each half splits into 4 eighths. Shade 4 eighths.','1/2 = 4/8. The denominator was multiplied by 4 (2 → 8), so the numerator is multiplied by 4 too (1 → 4).'),[2,8],[1,0],[1,4]),
 'p5f-frac-09':()=>strips(W('Find the missing numerator','Complete 2/3 = □/12. The top strip shows 2/3. Shade the twelfths strip to the same length.','Each third splits into 4 twelfths, so 2 thirds are 8 twelfths.','2/3 = 8/12. The denominator was multiplied by 4 (3 → 12), so the numerator is too (2 → 8).'),[3,12],[2,0],[2,8]),
 'p4s-frac-03':()=>share(W('Find 1/3 of 12','Share 12 counters equally among 3 friends. One friend’s share is one third of 12.','Press “Give one to everyone” until the pile is empty.','Each friend gets 4, so 1/3 of 12 = 4. Two friends together have 2/3 of 12 = 8.'),12,3,4),
 'p5f-frac-01':()=>share(W('Find 1/4 of 12','Share 12 counters equally among 4 friends. One friend’s share is one quarter of 12.','Press “Give one to everyone” until the pile is empty.','Each friend gets 3, so 1/4 of 12 = 3. Three friends together have 3/4 of 12 = 9.'),12,4,3),
 'p5s-frac-05':()=>strips(W('3 lots of 2/5','Find 3 × 2/5. Shade 2/5 on each of the 3 strips.','Shade 2 of the 5 parts on every strip.','3 × 2/5 = 6/5 = 1 1/5. Three lots of 2 fifths make 6 fifths: one whole and 1 fifth.'),[5,5,5],[0,0,0],[2,2,2]),
 'p5f-frac-07':()=>strips(W('3 lots of 2/3','Find 3 × 2/3. Shade 2/3 on each of the 3 strips.','Shade 2 of the 3 parts on every strip.','3 × 2/3 = 6/3 = 2. Six thirds make exactly two wholes.'),[3,3,3],[0,0,0],[2,2,2]),
 'p5s-frac-07':()=>strips(W('2 lots of 1 3/4','Find 2 × 1 3/4. Each lot is one whole strip and 3/4 of the next strip. The whole strips are already shaded. Shade 3/4 on each empty strip.','Shade 3 of the 4 parts on the second and the fourth strips.','2 × 1 3/4 = 2 wholes + 6 quarters = 2 + 1 2/4 = 3 1/2. Multiply the wholes and the quarters, then regroup 4 quarters as 1 whole.'),[4,4,4,4],[4,0,4,0],[4,3,4,3]),
 'p5s-frac-06':()=>strips(W('Find 2/3 of 3/4','Find 2/3 × 3/4. The top strip shows 3/4. On the twelfths strip, shade 2/3 of that shaded length.','3/4 is 9 twelfths. Two thirds of 9 twelfths is 6 twelfths.','2/3 × 3/4 = 6/12 = 1/2. Multiply the numerators (2 × 3 = 6) and the denominators (3 × 4 = 12), then simplify.'),[4,12],[3,0],[3,6]),
 'p5f-frac-08':()=>strips(W('Find 1/2 of 3/4','Find 1/2 × 3/4. The top strip shows 3/4. On the eighths strip, shade half of that shaded length.','3/4 is 6 eighths. Half of 6 eighths is 3 eighths.','1/2 × 3/4 = 3/8. Multiply the numerators (1 × 3 = 3) and the denominators (2 × 4 = 8).'),[4,8],[3,0],[3,3]),

 // Decimals.
 'p4s-dec-02':()=>hundred(W('Compare 0.47 and 0.5','Which is greater, 0.47 or 0.5? The whole grid is 1. Shade 0.47, which is 47 hundredths.','Shade 47 of the 100 squares: use +10 four times and +1 seven times.','0.47 is 47 hundredths and 0.5 is 50 hundredths, so 0.47 < 0.5. Compare the tenths first: 4 tenths is less than 5 tenths. More digits does not mean a greater number.'),47,true),
 'p5f-dec-02':()=>hundred(W('Compare 0.58 and 0.6','Which is greater, 0.58 or 0.6? The whole grid is 1. Shade 0.58, which is 58 hundredths.','Shade 58 of the 100 squares: use +10 five times and +1 eight times.','0.58 is 58 hundredths and 0.6 is 60 hundredths, so 0.58 < 0.6. Compare the tenths first: 5 tenths is less than 6 tenths.'),58),
 'p4s-dec-04':()=>hundred(W('Round 0.36 to one decimal place','The whole grid is 1. Shade 0.36. Is it nearer to 0.3 or to 0.4?','Shade 36 of the 100 squares.','0.36 is 6 hundredths more than 0.3 but only 4 hundredths less than 0.4, so it rounds to 0.4. The hundredths digit is 5 or more, so round up.'),36,true),
 'p5f-dec-04':()=>hundred(W('Round 0.73 to one decimal place','The whole grid is 1. Shade 0.73. Is it nearer to 0.7 or to 0.8?','Shade 73 of the 100 squares.','0.73 is 3 hundredths more than 0.7 but 7 hundredths less than 0.8, so it rounds to 0.7. The hundredths digit is less than 5, so round down.'),73),
 'p6f-dec-03':()=>hundred(W('Round the answer to 2 ÷ 3','2 ÷ 3 = 0.666…, with 6s that go on for ever. Round it to two decimal places, then shade the rounded value on the grid.','The third decimal digit is 6, which is 5 or more, so round the hundredths up to 0.67. Shade 67 squares.','2 ÷ 3 ≈ 0.67 to two decimal places. The grid shows 67 hundredths, just above the exact value 0.666…'),67),
 'p4s-dec-05':()=>chart(W('Add 0.05 to 0.38','The chart shows 0.38. Add 0.05. The hundredths column cannot hold 13, so exchange 10 hundredths for 1 tenth.','Add 1 tenth, then take away 5 hundredths: 8 + 5 = 13 hundredths = 1 tenth and 3 hundredths.','0.38 + 0.05 = 0.43. 13 hundredths is 1 tenth and 3 hundredths, so the tenths go up from 3 to 4.'),0,[3,8],[4,3]),
 'p5f-dec-05':()=>chart(W('Subtract 0.07 from 0.52','The chart shows 0.52. Subtract 0.07. There are only 2 hundredths, so exchange 1 tenth for 10 hundredths first.','Take away 1 tenth, then add 3 hundredths: 12 − 7 = 5 hundredths.','0.52 − 0.07 = 0.45. After the exchange there are 4 tenths and 12 hundredths, and 12 − 7 = 5 hundredths.'),0,[5,2],[4,5]),
 'p5s-dec-01':()=>chart(W('Divide 4.2 by 100','Show 4.2 ÷ 100 on the chart. Dividing by 100 moves every digit two places to the right.','The 4 ones become 4 hundredths, and the 2 tenths become 2 thousandths.','4.2 ÷ 100 = 0.042. Each digit is worth one hundredth as much, so it moves two places to the right; the empty tenths place needs a 0.'),0,[0,0,0],[0,4,2]),
 'p5f-dec-06':()=>chart(W('Divide 2.5 by 10','Show 2.5 ÷ 10 on the chart. Dividing by 10 moves every digit one place to the right.','The 2 ones become 2 tenths, and the 5 tenths become 5 hundredths.','2.5 ÷ 10 = 0.25. Each digit is worth one tenth as much, so it moves one place to the right.'),0,[0,0],[2,5]),
 'p5s-dec-02':()=>chart(W('Write 3 m 45 cm in metres','The chart shows the 3 whole metres. Show 3 m 45 cm in metres. 100 cm make 1 m, so 1 cm is one hundredth of a metre.','45 cm is 45 hundredths of a metre: 4 tenths and 5 hundredths.','3 m 45 cm = 3.45 m, because 45 cm is 45/100 of a metre.'),3,[0,0],[4,5]),
 'p5f-dec-07':()=>chart(W('Write 1 kg 250 g in kilograms','The chart shows the 1 whole kilogram. Show 1 kg 250 g in kilograms. 1000 g make 1 kg, so 1 g is one thousandth of a kilogram.','250 g is 250 thousandths of a kilogram: 2 tenths, 5 hundredths and 0 thousandths.','1 kg 250 g = 1.250 kg, usually written 1.25 kg, because 250 g is 250/1000 of a kilogram.'),1,[0,0,0],[2,5,0]),

 // Money.
 'p2s-money-01':()=>hundred(W('Show 45 cents','The grid is $1, which is 100 cents. Each square is 1 cent. Shade 45 cents.','Shade 45 squares: 4 tens and 5 ones.','45 cents is written $0.45. The digits after the point count the cents; the digit before it counts the dollars.'),45,true),
 'p2s-money-02':()=>hundred(W('Which is more?','Which is more: 60 cents or $0.55? The grid is $1, which is 100 cents. Shade 60 cents.','Shade 60 squares: 6 tens.','$0.55 is 55 cents. 60 cents fills 5 more squares, so 60 cents is more than $0.55.'),60,true),
 'p2s-money-03':()=>line(W('Dollars into cents','$1 is 100 cents. Start at 100 cents and jump to $1.20.','$1.20 is $1 and 20 cents. Make 2 jumps of +10.','$1.20 = 100 cents + 20 cents = 120 cents.'),100,200,100,120,10),
 'p2s-money-04':()=>counters(W('Count in 10 cents','Each counter is a 10-cent coin. Put in counters to make 70 cents.','Count in tens as you add coins: 10, 20, 30, … 70.','7 ten-cent coins make 70 cents. Counting in tens is quicker than counting the cents one by one.'),7),
 'p3s-money-01':()=>line(W('Add 28 cents','Start at 345 cents, which is $3.45. Add 28 cents: add 30 cents, then take back 2 cents.','Make 3 jumps of +10 to 375, then 2 jumps of −1.','$3.45 + $0.28 = $3.73. Adding 30 cents and taking back 2 cents adds 28 cents.'),340,400,345,373,10),

 // Measurement.
 'p2s-measure-01':()=>line(W('Compare two ribbons','Ribbon A is 4 m long and ribbon B is 7 m long. Start at 4 m on the line and jump to 7 m.','Make jumps of +1 from 4 until you reach 7, counting the jumps.','You made 3 jumps of 1 m, so ribbon B is 7 − 4 = 3 m longer.'),0,10,4,7),
 'p2s-measure-02':()=>counters(W('How much heavier?','A bag of rice has a mass of 7 kg and a bag of flour has a mass of 2 kg. Each counter stands for 1 kg. Put in counters to show how much heavier the rice is.','Find the difference: 7 − 2.','The rice is 7 − 2 = 5 kg heavier than the flour.'),5),
 'p2s-measure-03':()=>counters(W('How much more water?','Jug A holds 5 litres and jug B holds 8 litres. Each counter stands for 1 litre. Put in counters to show how much more jug B holds.','Find the difference: 8 − 5.','Jug B holds 8 − 5 = 3 litres more than jug A.'),3),
 'p2s-measure-04':()=>ruler(W('Choose a sensible length','A pencil could be 12 cm long or 12 m long. Only one makes sense. Set the ruler to the sensible length.','A pencil fits in your hand. Set the ruler to 12 cm.','12 cm is about the length of a pencil; 12 m would be longer than a classroom. Choose centimetres for short lengths and metres for long ones.'),5,12),
 'p3s-measure-01':()=>hundred(W('Show 350 ml','The grid is 1 litre, which is 1000 ml, so each square is 10 ml. Shade 350 ml.','350 ml is 35 lots of 10 ml. Shade 35 squares.','350 ml fills 35 squares. That is less than half of the litre, because half a litre is 500 ml.'),35,true),
 'p3s-measure-02':()=>line(W('Write 2 m 30 cm in centimetres','Each metre is 100 cm, so 2 m is 200 cm. Start at 200 cm and jump on 30 cm.','Make 3 jumps of +10.','2 m 30 cm = 200 cm + 30 cm = 230 cm.'),200,300,200,230,10),
 'p3s-measure-03':()=>line(W('Write 1 km 50 m in metres','1 km is 1000 m. Start at 1000 m and jump on 50 m.','Make 5 jumps of +10.','1 km 50 m = 1000 m + 50 m = 1050 m. Watch the zero: it is not 150 m or 1500 m.'),1000,1100,1000,1050,10),

 // Time.
 'p1s-time-02':()=>clock(W('One hour later','The clock shows 3 o’clock. One hour is 60 minutes: the minute hand goes all the way round once. Show the time 1 hour later.','Change the hour to 4 and keep the minutes at 0.','1 hour after 3 o’clock is 4 o’clock. In 60 minutes the minute hand goes once round the clock, and the hour hand moves on to the next number.'),900,960),
 'p1s-time-03':()=>clock(W('Half an hour later','The clock shows 3 o’clock. Show the time half an hour later.','Half an hour is 30 minutes. Keep the hour at 3 and set the minutes to 30.','Half an hour after 3 o’clock is half past 3, or 3:30. The minute hand has gone halfway round the clock.'),900,930),
 'p2s-time-02':()=>clock(W('Move on 90 minutes','The clock shows 2 o’clock. Move it on by 90 minutes.','90 minutes = 60 minutes + 30 minutes = 1 hour 30 minutes. Set the hour to 3 and the minutes to 30.','90 minutes after 2:00 is 3:30, because 90 minutes = 1 h 30 min.'),840,930),
 'p3s-time-01':()=>line(W('Count on in seconds','A runner took 1 min 15 s. 1 minute is 60 seconds, so start at 60 and jump on 15 more seconds.','Make 1 jump of +10 and 5 jumps of +1.','1 min 15 s = 60 s + 15 s = 75 s.'),60,100,60,75),
 'p3s-time-02':()=>clock(W('Find the finish time','A lesson starts at 9:45 am and lasts 30 minutes. Show the finish time.','9:45 + 15 minutes = 10:00. Then add the other 15 minutes.','The lesson finishes at 10:15 am. Counting on to the hour first and then adding the rest avoids writing 9:75.'),585,615),
 'p5f-time-02':()=>clock(W('Find the finish time','A film starts at 1:50 pm and lasts 40 minutes. Show the finish time.','1:50 pm + 10 minutes = 2:00 pm. Then add the other 30 minutes.','The film finishes at 2:30 pm. Count on to the next hour first, then add the minutes that are left.'),830,870),
 'p3s-time-03':()=>clock(W('Show 14:30','The clock shows 2:30 am. Change it to show 14:30 in 24-hour time.','14:30 is after 12 noon, so it is a pm time: 14 − 12 = 2. Press pm.','14:30 is 2:30 pm. For times from 1 pm onwards, subtract 12 from the 24-hour hour. 02:30 is 2:30 am.'),150,870),
 'p5f-time-03':()=>clock(W('Show 16:45','The clock shows 4:45 am. Change it to show 16:45 in 24-hour time.','16:45 is after 12 noon, so it is a pm time: 16 − 12 = 4. Press pm.','16:45 is 4:45 pm, and 04:45 is 4:45 am.'),285,1005),
 'p5f-time-01':()=>clock(W('Add 75 minutes','School starts at 8:00 am. Assembly ends 75 minutes later. Show the time it ends.','75 minutes = 60 minutes + 15 minutes = 1 h 15 min. Set the hour to 9 and the minutes to 15.','8:00 am + 1 h 15 min = 9:15 am, because 75 minutes is 1 hour and 15 minutes.'),480,555),

 // Area, perimeter and volume.
 'p4s-area-01':()=>rectangle(W('Find the missing length','A rectangle is 4 units wide and has an area of 24 square units. Keep the width at 4. Change the height until the area is 24.','4 × ? = 24. Work out 24 ÷ 4.','4 × 6 = 24, so the missing length is 24 ÷ 4 = 6 units.'),4,5,(a,b)=>a===4&&b===6),
 'p5f-area-02':()=>rectangle(W('Find a length from the perimeter','A rectangle is 6 units wide and has a perimeter of 20 units. Keep the width at 6. Change the height until the perimeter is 20.','Half the perimeter is width + height = 10. Work out 10 − 6.','6 + 4 + 6 + 4 = 20, so the missing length is 4 units. Half the perimeter is one width plus one length.'),6,3,(a,b)=>a===6&&b===4),
 'p4s-area-02':()=>rectangle(W('Join two rectangles','A 5 by 3 rectangle and a 2 by 3 rectangle are joined along their 3-unit sides. Make the one rectangle they form.','The heights stay 3. The widths join: 5 + 2.','They make a 7 by 3 rectangle. Its area is 15 + 6 = 21 square units, the same as 7 × 3. The area of a composite figure is the sum of the areas of its parts.'),5,3,(a,b)=>a===7&&b===3),
 'p5f-area-03':()=>rectangle(W('The rectangle around an L-shape','An L-shape is a 7 by 5 rectangle with a 1 by 1 square cut from one corner. Build the full 7 by 5 rectangle first.','Make the width 7 and keep the height 5.','The rectangle’s perimeter is 7 + 5 + 7 + 5 = 24 units. Cutting a corner square removes 2 unit edges but adds 2 new ones, so the L-shape’s perimeter is also 24 units. Its area is 35 − 1 = 34 square units.'),5,5,(a,b)=>a===7&&b===5),
 'p5s-area-01':()=>triangles({...join,title:'Find the height with a matching triangle',text:'Join a matching triangle to the blue triangle to make a rectangle. Then compare the triangle’s height with the rectangle’s height.',success:'The pair makes a 6 by 4 rectangle. The triangle’s perpendicular height is the rectangle’s height: it meets the base at a right angle. A slanting side is not the height.'},6,4),
 'p6f-area-01':()=>triangles({...join,title:'Find the height with a matching triangle',text:'Join a matching triangle to the blue triangle to make a rectangle. Which side of the rectangle matches the triangle’s height?',success:'The pair makes an 8 by 5 rectangle. The triangle’s perpendicular height, 5 units, is the rectangle’s height, at a right angle to the base.'},8,5),
 'p6f-area-02':()=>triangles({...join,title:'A triangle is half a rectangle',text:'The blue triangle has a base of 10 units and a perpendicular height of 6 units. Join a matching triangle and find the area of the rectangle they make.',success:'The rectangle is 10 × 6 = 60 square units, so the triangle is half of it: 30 square units. Area of a triangle = 1/2 × base × height.'},10,6),
 'p5s-area-03':()=>triangles({...join,title:'The roof is half a rectangle',text:'A house-shaped figure has a triangular roof with a base of 6 units and a height of 3 units. Join a matching triangle to the roof to see what part of a rectangle it is.',success:'The two triangles make a 6 by 3 rectangle of 18 square units, so the roof is half of it: 9 square units. Add it to the area of the rectangle below to find the whole figure.'},6,3),
 'p6f-area-03':()=>triangles({...join,title:'The roof in a composite figure',text:'A figure is a rectangle with a triangular roof. The roof has a base of 12 units and a height of 5 units. Join a matching triangle to find the roof’s area.',success:'The pair makes a 12 by 5 rectangle of 60 square units, so the roof is 30 square units. Find the area of each part, then add them for the composite figure.'},12,5),
 'p5s-vol-02':()=>cuboid(W('Build a cuboid','Build a cuboid 5 units wide and 2 units high. Its depth stays at 3 units. How many unit cubes does it contain?','Set the width to 5 and the height to 2.','The front face has 5 × 2 = 10 cubes, and there are 3 such layers going back: 10 × 3 = 30 unit cubes. Volume = length × breadth × height.'),[2,1,3],[5,2]),
 'p5f-vol-02':()=>cuboid(W('Layers of cubes','Build a cuboid 4 units wide and 2 units high. Its depth is 3 units, so it has 3 layers going back.','Set the width to 4 and the height to 2.','Each layer has 4 × 2 = 8 cubes, and there are 3 layers: 3 × 8 = 24 unit cubes.'),[2,1,3],[4,2]),
 'p5s-vol-04':()=>cuboid(W('Fill the tank','The cuboid shows the water in a tank whose base is 5 units wide and 4 units deep. Fill the water to a height of 3 units.','Keep the width at 5 and set the height to 3.','The water’s volume is 5 × 4 × 3 = 60 cubic units: the base area, 20, times the water height, 3.'),[5,1,4],[5,3]),
 'p6f-vol-02':()=>cuboid(W('Fill the tank','The cuboid shows the water in a tank whose base is 6 units wide and 2 units deep. Fill the water to a height of 5 units.','Keep the width at 6 and set the height to 5.','The water’s volume is 6 × 2 × 5 = 60 cubic units: the base area, 12, times the water height, 5.'),[6,1,2],[6,5]),
 'p5s-vol-05':()=>hundred(W('Millilitres in a litre','The grid is 1 litre, which is 1000 ml, so each square is 10 ml. Shade 250 ml.','250 ÷ 10 = 25. Shade 25 squares.','250 ml = 250 cm³ = 0.25 litre. 1 ml is the same as 1 cm³, and 1000 ml make 1 litre.'),25),
 'p6f-vol-03':()=>hundred(W('Millilitres in a litre','The grid is 1 litre, which is 1000 ml, so each square is 10 ml. Shade 600 ml.','600 ÷ 10 = 60. Shade 60 squares.','600 ml = 600 cm³ = 0.6 litre. 1 ml is the same as 1 cm³, and 1000 ml make 1 litre.'),60),
 'p6s-vol-01':()=>cuboid(W('Find the missing height','A cuboid has a volume of 60 cubic units. It is 5 units wide and 4 units deep. Change its height until the volume is 60.','The base holds 5 × 4 = 20 cubes. How many layers of 20 make 60?','Height = 60 ÷ (5 × 4) = 3 units. Check: 5 × 4 × 3 = 60.'),[5,1,4],[5,3]),
 'p6s-vol-02':()=>cuboid(W('Base area × height','A cuboid has a base 3 units wide and 4 units deep, and a volume of 24 cubic units. Change its height until the volume is 24.','The base area is 3 × 4 = 12 square units. How many layers of 12 make 24?','Volume = base area × height: 12 × 2 = 24. So the height is 24 ÷ 12 = 2 units.'),[3,1,4],[3,2]),
 'p6s-vol-03':()=>cuboid(W('Build a cube of 27','Build a cube with a volume of 27 unit cubes. The depth is already 3 units, and in a cube every edge has the same length.','Make the width and the height equal to the depth.','3 × 3 × 3 = 27, so the edge of the cube is 3 units: 3 is the cube root of 27. Each layer holds 3 × 3 = 9 cubes, and 3 layers make 27.'),[2,2,3],[3,3]),

 // Angles, shapes and solids.
 'p4s-angle-01':()=>angle(W('Make ∠ABC = 60°','∠ABC is the angle at B, the middle letter, between the arms BA and BC. Open the angle so that ∠ABC = 60°.','Set the angle to 60 degrees.','∠ABC = 60°. The middle letter always names the vertex, where the two arms meet.'),50,60),
 'p5s-angle-01':()=>angle(W('Angles on a straight line','Two angles sit together on a straight line. One of them is 60°, as shown. Change the angle to show the other one.','Angles on a straight line add up to 180°. Work out 180° − 60°.','60° + 120° = 180°. Angles on a straight line add up to 180°.'),60,120),
 'p5f-angle-03':()=>angle(W('Angles on a straight line','Two angles sit together on a straight line. One of them is 45°, as shown. Change the angle to show the other one.','Angles on a straight line add up to 180°. Work out 180° − 45°.','45° + 135° = 180°. If the two lines cross, the angle opposite 45° is also 45°, and the angle opposite 135° is 135°.'),45,135),
 'p5s-angle-02':()=>angle(W('Angles around a point','Three angles fit around a point. Two of them are 150° and 100°. Open the angle to show the third one.','Angles around a point add up to 360°. Work out 360° − 150° − 100°.','150° + 100° + 110° = 360°. A full turn around a point is 360°.'),90,110),
 'p5s-angle-03':()=>angle(W('Vertically opposite angles','Two straight lines cross. One angle is 40°. The model shows the angle next to it, 140°. Change it to show the angle vertically opposite the 40° angle.','Vertically opposite angles are equal.','The vertically opposite angle is 40°, because vertically opposite angles are equal. Angles next to each other on a line add up to 180°: 40° + 140° = 180°.'),140,40),
 'p5s-angle-04':()=>angle(W('Find the unknown angle','Three angles sit together on a straight line: 90°, 55° and x. Show angle x.','Angles on a straight line add up to 180°. Work out 180° − 90° − 55°.','x = 35°, because 90° + 55° + 35° = 180°.'),55,35),
 'p5f-angle-04':()=>angle(W('Find the unknown angle','Three angles fit around a point: 90°, 150° and x. Show angle x.','Angles around a point add up to 360°. Work out 360° − 90° − 150°.','x = 120°, because 90° + 150° + 120° = 360°.'),90,120),
 'p1s-shape-01':()=>rectangle(W('Turn the rectangle into a square','This rectangle is 5 units wide and 3 units tall. Change it into a square.','A square has four equal sides. Make the width and the height the same.','All four sides are now equal, so it is a square. A square is a special rectangle: both have four square corners, but a square’s sides are all the same length.'),5,3,(a,b)=>a===b),
 'p1s-shape-02':()=>triangles({...join,title:'Put two triangles together',text:'Join a matching triangle to the blue triangle. What shape do the two triangles make together?',success:'The two triangles fit together to make a rectangle. Shapes can be put together to make new shapes, and a rectangle can be cut from corner to corner into two triangles.'},6,4),
 'p2s-shape-01':()=>rectangle(W('Make the next shape in the pattern','The pattern repeats: small square, large square, small square, large square, small square, … The small square is 1 by 1 and the large square is 3 by 3. The model shows the last small square. Make the next shape.','After a small square comes a large square. Make it 3 units wide and 3 units tall.','The next shape is the large 3 by 3 square. The pattern repeats “small, large”, so only the size changes; the shape stays a square.'),1,1,(a,b)=>a===3&&b===3),
 'p2s-shape-02':()=>cuboid(W('Turn the cuboid into a cube','This cuboid is 2 units wide, 3 units high and 3 units deep. Change it into a cube.','A cube has all its edges the same length. The depth is 3, so make the width and the height 3 too.','Every edge is now 3 units, so every face is a square: this is a cube. A cuboid’s faces are rectangles; a cube is a cuboid whose faces are all equal squares.'),[2,3,3],[3,3]),
 'p4s-solid-03':()=>cuboid(W('Build the cuboid from its net','A net folds into a cuboid 4 units wide, 2 units high and 3 units deep. Build that cuboid.','Set the width to 4 and the height to 2. The depth is already 3.','The cuboid has 6 faces in 3 matching pairs: two 4 by 2, two 4 by 3 and two 2 by 3 rectangles. Its net must contain all six faces, joined so that they fold without overlapping.'),[1,1,3],[4,2]),
 'p5s-shape-01':()=>angle(W('Find the third angle','Two angles of a triangle are 50° and 60°. Open the angle to show the third angle.','The three angles of a triangle add up to 180°. Work out 180° − 50° − 60°.','The third angle is 70°, because 50° + 60° + 70° = 180°. All three angles are acute, so this is an acute-angled triangle.'),90,70),
 'p6f-shape-02':()=>angle(W('Find the third angle','Two angles of a triangle are 35° and 45°. Open the angle to show the third angle.','The three angles of a triangle add up to 180°. Work out 180° − 35° − 45°.','The third angle is 100°, because 35° + 45° + 100° = 180°. One angle is obtuse, so this is an obtuse-angled triangle.'),60,100),
 'p6f-shape-01':()=>angle(W('The equal base angles','An isosceles triangle has a vertex angle of 40°. Its two base angles are equal. Change the angle to show one base angle.','The angles add up to 180°. Take away the 40°, then share what is left equally between the two base angles.','Each base angle is 70°: 180° − 40° = 140°, and 140° ÷ 2 = 70°. Check: 40° + 70° + 70° = 180°.'),40,70),
 'p5s-shape-02':()=>angle(W('The angle next to it','In a parallelogram, one angle is 70°, as shown. Change the angle to show the angle next to it along the same side.','Neighbouring angles in a parallelogram add up to 180°. Work out 180° − 70°.','70° + 110° = 180°. Neighbouring angles in a parallelogram add up to 180°, and opposite angles are equal: 70° and 70°, 110° and 110°.'),70,110),
 'p5s-shape-03':()=>angle(W('Split a square corner','A line splits a square corner (90°) into two angles. One of them is 55°. Set the angle to the other part.','The two parts fill the square corner, so they add up to 90°. Work out 90° − 55°.','The other part is 35°, because 55° + 35° = 90°. You found it from angle facts, without adding any lines.'),90,35),
 'p6s-shape-01':()=>angle(W('Angles between parallel sides','In a trapezium, the two angles along one slanting side lie between the parallel sides. One of them is 75°, as shown. Change the angle to show the other one.','These two angles add up to 180°. Work out 180° − 75°.','75° + 105° = 180°. In a trapezium, the two angles between the parallel sides along the same slanting side add up to 180°.'),75,105),
 'p6f-shape-03':()=>angle(W('The other acute angle','A right-angled triangle is cut from a rectangle. One of its acute angles is 35°. Set the angle to its other acute angle.','The right angle is 90°, so the two acute angles share the other 90°. Work out 90° − 35°.','The other acute angle is 55°, because 35° + 55° + 90° = 180°. In a right-angled triangle, the two acute angles always add up to 90°.'),90,55),
 'p6s-circle-01':()=>ruler(W('From radius to diameter','A circle has a radius of 6 cm. The ruler shows the radius. Change it to show the diameter.','The diameter goes right across the circle through its centre: it is 2 radii long.','The diameter is 2 × 6 = 12 cm. Circumference = π × diameter ≈ 3.14 × 12 = 37.68 cm, and area = π × radius × radius ≈ 3.14 × 6 × 6 = 113.04 cm².'),6,12),
 'p6s-circle-02':()=>angle(W('The corner of a quarter-circle','A quarter-circle is one of 4 equal parts of a circle. Open the angle to show the angle at its centre.','A full turn is 360°. Work out 360° ÷ 4.','The centre angle is 90°, a quarter of 360°. So a quarter-circle’s curved edge is 1/4 of the circumference, and its area is 1/4 of the circle’s area. Its perimeter also includes the two straight radii.'),45,90),
 'p6s-circle-03':()=>ruler(W('Find the radius first','A semicircle sits on the 12 cm top edge of a rectangle, so its diameter is 12 cm. The ruler shows the diameter. Change it to show the radius.','The radius is half the diameter.','The radius is 12 ÷ 2 = 6 cm. The semicircle’s area is 1/2 × π × 6 × 6; add the rectangle’s area to find the whole figure.'),12,6),

 // Data.
 'p2s-graph-01':()=>counters(W('One symbol for 2 oranges','On this picture graph, each counter stands for 2 oranges. Put in counters to show 10 oranges.','Count in twos as you add counters: 2, 4, 6, 8, 10.','5 counters show 10 oranges, because each counter stands for 2. To read a graph like this, count in twos, not in ones.'),5),
 'p3s-graph-01':()=>blocks(W('Read a scale of 5','On a bar graph, each block stands for 5 pupils. Build the bar for the 35 pupils who chose durian.','Count in fives as you add blocks: 5, 10, 15, … until you reach 35.','7 blocks × 5 pupils = 35 pupils. When the scale counts in fives, count the blocks and multiply by 5.'),'Durian',5,7),
 'p5f-graph-02':()=>blocks(W('Read a scale of 2','On a bar graph, each block stands for 2 books. Build the bar for 14 books.','Count in twos as you add blocks: 2, 4, 6, … until you reach 14.','7 blocks × 2 books = 14 books. Count the blocks, then multiply by the scale.'),'Books',2,7),
 'p4s-graph-01':()=>counters(W('Compare two rows of a table','A table shows that 9 pupils chose apples and 4 chose pears. Put in counters to show how many more pupils chose apples.','Find the difference: 9 − 4.','9 − 4 = 5 more pupils chose apples. Read each value from its own row, then compare them.'),5),
 'p5f-graph-01':()=>counters(W('Compare two rows of a table','A table shows 8 cats and 5 dogs at a shelter. Put in counters to show how many more cats there are than dogs.','Find the difference: 8 − 5.','There are 8 − 5 = 3 more cats. Read each value from its own row, then compare them.'),3),
 'p4s-graph-02':()=>line(W('Read a rise on a line graph','A line graph shows the temperature was 24 °C at 9 am and 30 °C at 12 noon. Start at 24 on the scale and move to 30. How big was the change?','Make +1 jumps from 24 until you reach 30, counting as you go.','The temperature rose by 30 − 24 = 6 °C. On a line graph, the change between two points is the difference between their values on the scale.'),20,40,24,30),
 'p5f-graph-03':()=>line(W('Read a fall on a line graph','A line graph shows 32 umbrellas sold on Monday and 27 on Tuesday. Start at 32 on the scale and move to 27.','Make −1 jumps from 32 down to 27, counting as you go.','Sales fell by 32 − 27 = 5 umbrellas. A line sloping down shows a decrease.'),20,40,32,27),
 'p4s-graph-03':()=>strips(W('One part of the pie chart','A pie chart of 40 votes is split into 4 equal parts, and apples got 1 part. This strip stands for all 40 votes, like the whole circle. Shade the apples’ share.','Shade 1 of the 4 equal parts.','Apples got 1/4 of the votes: 40 ÷ 4 = 10 votes. Each part of a pie chart is a fraction of the whole.'),[4],[0],[1]),
 'p6f-graph-01':()=>hundred(W('A pie chart share','A pie chart shows 200 votes. Apples got 35% of them. Shade 35% of the hundred grid.','Shade 35 of the 100 squares.','35% means 35 out of every 100, so 35% of 200 votes = 70 votes. Each part of a pie chart is a percentage of the whole.'),35),
 'p4s-graph-04':()=>counters(W('Complete the table','15 pupils chose a colour. 9 chose red and the rest chose blue. Put in counters for the pupils who chose blue.','The missing value is the total minus the known value: 15 − 9.','15 − 9 = 6 chose blue. Check: 9 + 6 = 15, the total.'),6,20),
 'p5f-graph-04':()=>counters(W('Complete the table','20 pupils chose a fruit. 7 chose apples, 5 chose pears and the rest chose bananas. Put in counters for bananas.','Take the known values from the total: 20 − 7 − 5.','20 − 7 − 5 = 8 chose bananas. Check: 7 + 5 + 8 = 20, the total.'),8,20),

 // Percentage, rate and algebra.
 'p6s-pct-01':()=>blocks(W('Build the whole from 25%','25% of a quantity is 15. Each block below is 25% of the whole and is worth 15. Add blocks until they make 100%.','100% is 4 × 25%. Make 4 blocks.','4 blocks × 15 = 60, so the whole quantity is 60. Check: 25% of 60 = 60 ÷ 4 = 15.'),'Whole',15,4),
 'p6s-pct-02':()=>task(W('Show a 25% discount','A $80 bag is sold at a 25% discount. Shade the discount on the bar.','Each section is 25%. Shade one section.','25% of $80 = $20, so the new price is $80 − $20 = $60. The percentage decrease compares the change, $20, with the original amount, $80: 20/80 = 25%.'),{kind:'percent',whole:80,percent:0,step:25,unit:'$'},is('percent',t=>t.percent===25)),
 'p5s-rate-01':()=>share(W('Find the price of one','4 friends each buy one notebook. Together they pay $12. Share the 12 dollar coins equally among the 4 friends.','Press “Give one to everyone” until the pile is empty.','Each friend pays $3, so one notebook costs $3. The rate is $3 per notebook: 12 ÷ 4 = 3.'),12,4,3),
 'p5f-rate-01':()=>share(W('Find the price of one','3 friends each buy one book. Together they pay $15. Share the 15 dollar coins equally among the 3 friends.','Press “Give one to everyone” until the pile is empty.','Each friend pays $5, so one book costs $5. The rate is $5 per book: 15 ÷ 3 = 5.'),15,3,5),
 'p5s-rate-02':()=>groups(W('From one to many','One notebook costs $3. Show the cost of 5 notebooks: one group of $3 for each notebook.','Keep $3 in each group and add groups until there are 5.','5 × $3 = $15. Total amount = rate × number of units.'),3,5),
 'p5f-rate-02':()=>groups(W('From one to many','One pen costs $4. Show the cost of 6 pens: one group of $4 for each pen.','Keep $4 in each group and add groups until there are 6.','6 × $4 = $24. Total amount = rate × number of units.'),4,6),
 'p6s-alg-01':()=>balance(W('Find what x stands for','The balance shows x + 3 = 8. The letter x stands for an unknown number. Keep the balance level and take 1 off both sides until x is alone.','Use “Take 1 off both sides” three times.','x = 5. The letter stands for the one number that keeps both sides equal: 5 + 3 = 8.'),{x:1,n:3},{x:0,n:8},5,[{x:1,n:0},{x:0,n:5}]),
 'p6s-alg-02':()=>balance(W('What does 3x + 2 mean?','The left pan holds 3 packets with x stickers in each and 2 loose stickers: 3x + 2. It balances 14 loose stickers. Take the loose stickers off both sides.','Use “Take 1 off both sides” until there are no loose stickers on the left.','3x = 12, so each packet holds 12 ÷ 3 = 4 stickers. The expression 3x + 2 means 3 lots of x, plus 2 more.'),{x:3,n:2},{x:0,n:14},4,[{x:3,n:0},{x:0,n:12}]),
 'p6s-alg-03':()=>balance(W('Collect the x terms','The left pan holds 2x and then 3x more: 2x + 3x. Together that is 5x, as the balance shows, and it balances 15. Split both sides into 5 equal groups.','Use “Split both sides into 5 equal groups”.','2x + 3x = 5x, and 5x = 15, so x = 3. Collecting like terms counts how many lots of x there are.'),{x:5,n:0},{x:0,n:15},3,[{x:1,n:0},{x:0,n:3}]),
 'p6s-alg-04':()=>balance(W('Check a value of x','When x = 4, is 2x + 1 equal to 9? The balance shows 2x + 1 = 9. Keep it level while you get x alone, and see what x must be.','Take 1 off both sides, then split both sides into 2 equal groups.','x = 4 keeps the balance level. Substituting x = 4 gives 2 × 4 + 1 = 8 + 1 = 9.'),{x:2,n:1},{x:0,n:9},4,[{x:1,n:0},{x:0,n:4}]),
};

/** The lessons given a task here; the tests check that each one still reaches a lesson. */
export const ACTIVITY_LESSONS=Object.keys(ACTIVITIES);
export const lessonActivity=(p:PlanEntry):Stage|undefined=>ACTIVITIES[p.id]?.();
