import type {PlanEntry} from '../../build/plan';
export interface TeachingFocus {question:string;answer:string;error:string;why:string;look:string;goal:string}
const focus=(question:string,answer:string,error:string,why:string,look:string,goal:string):TeachingFocus=>({question,answer,error,why,look,goal});
/** Mathematical attention, matched to the objective before matching its broad topic. */
export function teachingFocus(p:PlanEntry):TeachingFocus{
 const o=p.objective.toLowerCase(),c=p.code;
 if(c==='WN'&&!/operations|brackets|multiply|divide/.test(o)){
  if(p.level===1&&/count/.test(o)&&!/place|tens/.test(o))return focus('What does the 4 in 47 tell us?','4 tens, which is 40.','Just 4 ones.','The 4 sits in the tens place, so it counts 4 groups of ten: 40. The 7 counts single ones. Together they make 47.','Say how many tens and how many ones the number has.','read a number to 100 as tens and ones');
  if(/ordinal/.test(o))return focus('Before naming a position, what must we agree on?','The end where we start counting.','We can count from either end and get the same position.','The same child can be third from one end and a different position from the other.','Find the stated front. Follow the children in order from there.','name a position from a stated starting end');
  if(/odd|even/.test(o))return focus('How can pairs help us decide whether a count is even?','Every counter must have one partner.','A number is even whenever it is large.','Complete pairs use two at a time. One counter without a partner makes an odd count.','Look for a counter left without a partner, not just the number of rows.','explain odd and even counts using pairs');
  if(/round|estimate/.test(o))return focus('Which two values help us round a number?','The neighbouring multiples on either side.','Any two numbers that are easy to remember.','Rounding chooses the nearer allowed multiple. The midpoint separates the two choices.','Locate both endpoints, then the halfway point and the number itself.','use neighbouring benchmarks and the midpoint to justify an estimate');
  if(/pattern/.test(o)&&!/compare/.test(o))return focus('What should we check before continuing a number pattern?','Whether the same change works between several neighbours.','Whether our answer is larger than the last number.','Many larger answers are possible. The repeated change tells us which one follows this pattern.','Compare each neighbouring pair. Repeat the verified change once more.','explain a pattern using a repeated change');
  if(/compare|order/.test(o))return focus('When comparing numbers, where should we look first?','At the greatest place where the values differ.','Only at the ones digits.','One extra large unit can outweigh several smaller units. Equal large places make us look at the next place.','Line up the place-value columns. Find the first difference from the left.','justify a comparison with place value');
  return focus('What does a digit tell us about its column?','How many units of that column’s size we have.','Its value is the same in every column.','Three tens and three ones both use the digit three, but they describe different amounts. Zero keeps an empty column in the correct position.','Read the column name, then the digit. Join the place values to check the number.','connect a numeral or number name with its place-value groups');
 }
 if(c==='AS'){
  if(/taking away/.test(o))return focus('After some counters are taken away, which group answers “how many remain”?','The counters that stay.','The counters that were removed.','The removed group and the remaining group are different parts of the starting whole.','Keep track of the starting group, the removed part and the part that stays.','explain subtraction as finding the remaining part');
  if(/number bond/.test(o))return focus('What must the two parts of a number bond do?','Together they must make the whole.','Each part must equal the whole.','A whole can be split in many ways. The two parts still add to that same whole.','Match each part to its group of objects, then reconnect both groups.','connect whole-and-part pictures with addition and subtraction');
  if(/three one-digit/.test(o))return focus('When joining three groups, when is the addition finished?','After every group has been counted once.','As soon as the first two groups have been joined.','Joining two groups gives a useful subtotal. The third group still belongs to the whole.','Follow which groups have already been joined and which one is still waiting.','join three parts without omitting or repeating one');
  if(/symbol|correctly/.test(o))return focus('What does the equals sign tell us?','The amounts on both sides are the same.','It always means “write an answer next”.','An equation compares two amounts. A picture can show why those amounts match.','Read the operation as an action, then compare the quantities across the equals sign.','read an equation as a relationship between equal amounts');
  return focus('When we split a number to make a calculation easier, what must stay the same?','The total value of the parts.','The number of written digits.','We can regroup or split an amount while keeping its value. That lets us work with one useful part at a time.','Track the same amount through each split or exchange. Say what each part represents.','explain an addition or subtraction strategy without changing its quantities');
 }
 if(c==='FACT')return /multiple/.test(o)?focus('What makes a number a multiple?','It can be made from a whole number of equal groups.','It is any number larger than the starting number.','Successive multiples add one equal group each time. A common multiple appears in both lists.','Follow the equal group size in each list and look for shared totals.','distinguish multiples and common multiples from arbitrary larger numbers'):focus('How can we check a proposed factor?','Divide into complete equal groups with no remainder.','Choose any number smaller than the total.','A factor fits exactly. Factor pairs record the two whole numbers whose product is the total.','Match each proposed group size with the number of complete groups it makes.','justify a factor or common factor with exact grouping');
 if(c==='MD'||c==='WN'&&/operations|brackets|multiply|divide/.test(o)){
  if(/order|brackets/.test(o))return focus('Why must we pay attention to grouping in a calculation?','The grouping tells us which amount is formed first.','Every calculation is done strictly from left to right.','A multiplication can describe packets inside a larger total. Brackets can change what belongs inside each packet.','Match the grouped part of the expression to the grouped objects in the story.','explain the order of operations using the amounts being grouped');
  if(/remainder/.test(o))return focus('When should we stop making full groups?','When what is left cannot fill another group.','As soon as we have made one group.','The remainder is smaller than a full group. Otherwise we could still make another complete group.','Separate complete groups from the leftovers. Compare the leftovers with one group’s size.','explain a remainder and check it is smaller than the divisor');
  if(/10 100|powers/.test(o))return focus('What changes when a value is multiplied by ten?','Every place-value unit becomes ten times as large.','The decimal point is an object we move to change the amount.','The digits occupy different places because their values change. Thinking about units also works for division.','Track a named digit and the value of its old and new columns.','justify multiplication or division by powers of ten with place value');
  return focus('What makes multiplication and division a useful pair?','They connect a total with equal groups.','They work the same way even when the groups have different sizes.','Multiplication finds a total from equal groups. Division recovers a missing group size or number of groups.','Identify the total, how many groups there are and how much belongs in one group.','use equal groups to explain a product or quotient');
 }
 if(c==='FRAC'){
  if(/simplif/.test(o))return focus('When we regroup small fraction pieces into larger equal pieces, what must stay the same?','The amount covered by the selected pieces.','Only the denominator stays the same.','The selected count and the total count are divided by the same factor. The fraction has a new name, but its chosen share stays unchanged.','Match the shaded lengths before and after regrouping. Count both the shaded groups and all the groups.','simplify a fraction by regrouping equal parts without changing its value');
  if(/equivalent|simplif|missing numerator/.test(o))return focus('If we cut every fraction part into smaller equal pieces, what stays the same?','The amount covered by the selected pieces.','Only the denominator stays the same.','Both the selected count and the total count change together. The chosen share itself does not grow or shrink.','Compare the chosen lengths on equal-sized wholes before comparing the written numbers.','explain equivalent fractions as different names for the same share');
  if(/compare/.test(o))return focus('Before comparing fraction pictures, what must match?','The size of the wholes being compared.','The number of pieces must always match already.','A fraction describes a share of its whole. Equal-sized wholes make the lengths or areas comparable.','Check the wholes first. Then compare chosen amounts or rename the parts to the same size.','justify a fraction comparison using a common whole');
  if(/mixed|improper/.test(o)&&!/multiply|add|subtract/.test(o))return focus('When we rename a whole using fractional parts, how many parts does it contribute?','As many parts as the denominator names.','Just one extra part in the numerator.','For example, one whole contains four quarters. Whole counts must be converted to part counts before they are joined.','Mark each complete whole and the remaining parts separately.','connect whole counts and equal-part counts in mixed and improper fractions');
  if(/add|subtract/.test(o))return focus('What must match before we combine fractional parts?','The size of the parts we count.','The denominators must be added together.','Three quarters and one quarter are counts of the same-sized piece. Unlike pieces first need a common name.','Check the whole, rename unequal-sized parts when necessary, then join or remove the counts.','explain why fraction addition and subtraction need equal-sized parts');
  if(/decimal/.test(o))return focus('How can a fraction and a decimal describe the same amount?','Both can name equal parts of one whole.','Put the numerator and denominator next to a decimal point.','Tenths and hundredths are fraction units too. Equivalent parts or division link the two notations.','Keep the amount fixed as its parts are renamed. Check which place names each decimal digit.','connect fraction notation with decimal place value');
  if(/divid|division/.test(o))return focus('What should we decide before dividing a fractional amount?','Whether we are finding a share size or counting how many groups fit.','Division always gives a smaller answer.','A small group size can fit many times. Sharing among a stated number of groups asks a different question.','Name the starting amount and what one group means before choosing the calculation.','explain fractional division through sharing or measuring groups');
  if(/multiply|set|whole or set/.test(o))return focus('What does a fraction of an amount ask us to do?','Find equal parts of that amount and select the required parts.','Use the numerator and ignore the denominator.','The denominator determines one part’s size. The numerator tells us how many of those parts to take.','Identify the amount that acts as the whole, then one part, then the selected parts.','explain fraction multiplication as selecting a share of an amount');
  return focus('What must the bottom number of a fraction count?','All equal parts of the whole, including unchosen parts.','Only the unchosen parts.','The numerator counts chosen parts. The denominator keeps the size of each part tied to the whole.','Identify one whole. Compare its part sizes, then count all parts and chosen parts separately.','read and write a fraction from its whole and equal parts');
 }
 if(c==='DEC'){
  if(/measurement/.test(o))return conversion();
  if(/round|accuracy/.test(o))return focus('What determines the rounding decision?','The value’s position between the two neighbouring allowed answers.','The last digit anywhere in the number.','The requested accuracy sets the size of the rounding interval. Its midpoint decides the nearer endpoint.','Locate the requested place first, then its two neighbours and midpoint.','justify decimal rounding at the requested accuracy');
  if(/compare|order/.test(o))return focus('Does writing more decimal digits always make a larger number?','No. We must compare the values in matching places.','Yes. The longer written decimal is always greater.','A trailing zero can name the same amount in smaller units. Tenths must be compared with tenths before hundredths.','Align the decimal points and compare the first place that differs.','compare decimals by value rather than length');
  if(/fraction/.test(o))return focus('What does the place of a decimal digit tell us?','Which fractional unit the digit counts.','How many parts should be ignored.','Tenths, hundredths and thousandths name equal parts of a whole. These names let us write the same amount as a fraction.','Keep the chosen amount unchanged while naming its place-value units.','connect decimals and fractions through equal-sized units');
  if(/add|subtract/.test(o))return focus('Why do we align decimal points for addition or subtraction?','So units of the same size meet in the same column.','So the left edges of both numbers line up.','Tenths combine with tenths and hundredths with hundredths. Exchanges regroup value without changing the amount.','Say the name of each column and track any exchange between neighbouring columns.','explain decimal addition and subtraction using like units');
  if(/multiply|divide|quotient/.test(o))return focus('What must we keep track of during a decimal calculation?','The size of the units being grouped or shared.','Only the digits, without their places.','The same digits can describe very different values. An estimate and the inverse operation help check the scale of the answer.','Name the units before and after grouping. Compare the answer’s size with a sensible estimate.','explain the scale of a decimal product or quotient');
  return focus('What happens to a unit when it is split into ten equal parts?','Each new part is one tenth of that unit.','Each new part is ten times as large.','Splitting keeps the whole amount but makes each counted part smaller. That is how place value continues after ones.','Follow one whole into tenths, then one tenth into hundredths.','explain decimal places as repeated equal subdivision');
 }
 if(c==='MONEY')return focus('When counting money, what should we add?','The values shown on the coins or notes.','Only how many coins or notes we can see.','Different coins can have different values. One dollar and one hundred cents are two names for the same amount.','Read every value and its unit. Keep dollars and cents distinct until you rename them.','compare, combine or rename money while preserving its value');
 if(c==='PCT')return /original/.test(o)?focus('When finding an original amount from a percentage, what are we trying to rebuild?','The whole amount represented by 100%.','Another percentage of the amount already given.','The given amount represents only its stated percentage. Find the value of one equal percentage unit, then rebuild the whole.','Label which amount belongs to the given percentage and which unknown belongs to 100%.','recover a whole from a known percentage share'):focus('What does the percentage refer to?','A share of a named whole, split into one hundred equal parts.','A number of objects that is always the same.','The same percentage can describe different quantities when the whole changes. In a change problem, identify the original whole.','Mark 100%, the percentage share and whether the question asks for that share or the final amount.','connect a percentage, its reference whole and the requested quantity');
 if(c==='RATIO')return focus('What does one unit mean in a ratio model?','The same-sized amount in each of the compared quantities.','A different-sized amount for every colour.','The counts of equal units describe the comparison. Their actual size comes from a given quantity or total.','Keep the quantity labels in order. Distinguish one part from the sum of all ratio parts.','explain a ratio through labelled equal units');
 if(c==='RATE')return focus('What does “per unit” tell us?','The amount associated with one of the named units.','The total amount for any number of units.','A rate connects two quantities. Repeating one unit repeats its amount; dividing a total can recover the number of units.','Read both unit labels and identify the rate, total amount and number of units.','connect a rate with its total and number of units');
 if(c==='ALG')return /equation|solve/.test(o)?focus('What must we preserve while solving an equation?','The equality between its two sides.','Only the numbers on the left side.','Removing or adding equal amounts on both sides keeps them equal. We use that relationship to isolate the unknown.','Track what happens to each side and check the final value in the original equation.','explain why an equation-solving step preserves equality'):focus('What does a letter represent in an expression?','A number whose value is not yet specified.','The name of an object that cannot stand for a number.','A letter can take a numerical value. Like terms count the same unknown-sized unit; substitution replaces it consistently.','Say what one letter means before grouping terms or substituting a value.','interpret and use an expression through the meaning of its unknown');
 if(c==='TIME')return /duration|start|finish/.test(o)?focus('What links the start, duration and finish?','Moving forward by the duration takes the start to the finish.','Adding the two clock readings gives the duration.','A clock reading is a position in the day; a duration is the gap between two positions.','Mark the known endpoints or gap. Cross hour boundaries in useful jumps.','explain time calculations as movement along a timeline'): /clock/.test(o)?focus('What must stay the same when we read or rename a clock time?','The instant in the day that the hands or notation describe.','The written hour digits must never change.','The short and long hands have different jobs. A new notation can describe the same instant, with the day period made clear.','Read the hour and minute roles separately, then use the morning or afternoon information.','connect clock hands and time notation without changing the instant'):focus('When converting a duration, what do we regroup?','Equal time units using sixty where an hour meets minutes or a minute meets seconds.','Groups of one hundred for every pair of time units.','Time units do not all follow decimal place value. Rename the complete larger units, then include the remaining smaller ones.','Keep complete units and extra units separate until their names match.','rename a duration without changing how long it lasts');
 if(c==='LENGTH')return focus('What does a ruler measure between two marks?','The intervals between the endpoints.','The number of tick marks including both endpoints.','A length is a distance, not a count of boundary marks. Starting at zero makes the far reading the length.','Locate both endpoints and check the size of one interval.','measure or draw a length by its endpoints and intervals');
 if(c==='MEASURE')return /convert|compound|decimal/.test(o)?conversion():focus('What must we check before comparing measurements?','The kind of quantity, its unit and the scale.','Only which written number looks larger.','Length, mass and liquid volume need suitable units. The scale tells us what each interval or displayed amount represents.','Read the quantity and unit labels before calculating a difference.','choose and interpret units that match the measured quantity');
 if(c==='AREA')return /triangle/.test(o)?focus('Which height belongs with a chosen triangle base?','The perpendicular distance from the opposite vertex to the base line.','Any sloping edge that is easy to see.','Base and perpendicular height define the matching rectangle or parallelogram. The triangle’s area is half their product.','Find the right-angle relationship before using a dimension. For a composite surface, keep the pieces separate.','connect triangle area to a matching base and perpendicular height'): /perimeter/.test(o)&&!/area/.test(o)?focus('Which edges belong to a perimeter?','Every edge along the outside boundary, counted once.','Every line drawn inside and outside the shape.','Perimeter is one complete walk around the boundary. Internal joins are not part of that walk.','Trace a full circuit and mark each edge as you count it.','justify a perimeter by tracing its complete boundary'):focus('How does area differ from perimeter?','Area covers the inside; perimeter follows the outside.','Both count the lengths of boundary edges.','Equal rows of squares explain area. Joining or removing surfaces changes how many squares are covered.','Identify the surface to cover and the lengths that determine its rows. Keep missing or overlapping pieces visible.','explain area calculations using covered square units');
 if(c==='VOL')return /convert/.test(o)?focus('Why can millilitres and cubic centimetres describe the same volume?','One millilitre occupies one cubic centimetre.','One litre occupies one cubic centimetre.','A litre contains one thousand millilitres. Use both unit relationships while preserving the occupied space.','Track which volume each unit names before scaling its numerical count.','connect liquid-volume units with cubic centimetres'):focus('How can layers help us find volume?','Count the cubes in one layer, then all equal layers.','Count only the cubes visible from the front.','Hidden cubes occupy space too. Base area counts one layer; height tells how many unit layers fill the solid or liquid depth.','Separate base dimensions, layer size and number of layers. Check what is known and what is missing.','explain volume or a missing dimension through equal layers');
 if(c==='CIRCLE')return focus('What should we distinguish before using a circle measurement?','Radius from diameter, and covered surface from boundary length.','Treat every length across the circle as a radius.','A diameter contains two radii. A partial-circle perimeter may also contain straight edges; its area concerns the enclosed surface.','Mark the centre, radius and required outer boundary or surface before calculating.','justify circle calculations using the correct radius and region');
 if(c==='AVG')return focus('What stays the same when we redistribute amounts to find an average?','The total and the number of recipients.','Each original amount must stay unchanged.','An average describes the equal share after redistribution. It need not be one of the original amounts.','Track the complete total, then share it across the same number of items.','explain average as a fair share and reverse the relationship');
 if(c==='GRAPH')return /pie/.test(o)?focus('What does a sector’s fraction refer to?','The whole dataset represented by the circle.','Only the neighbouring sector.','Each share belongs to one common total. The pieces together must account for the whole.','Read the total and category labels before turning a sector share into a count.','interpret a pie-chart share using its common total'): /line/.test(o)?focus('What does a line between plotted observations help us track?','The order and change between observations.','Proof of every unrecorded value between them.','A line connects recorded observations. Its rise or fall shows change, but it does not supply missing measurements automatically.','Read the axes and scale, locate the named observations, then compare their values.','interpret recorded values and changes on a line graph'):focus('What gives a mark or entry its meaning in a graph or table?','Its label and the scale or key.','Its position alone, without any labels.','A symbol may represent several objects. A table value belongs to its row and column; a graph value belongs to its category and scale.','Read the title, labels and key first. Then trace the requested entry or category.','read data values and comparisons using their labels and scale');
 if(c==='LINES')return focus('How do we distinguish parallel lines from perpendicular lines?','Check constant spacing or a right-angle meeting.','Use whether the lines happen to look horizontal.','Turning the page changes orientation but not the relationship. Crossing alone does not guarantee perpendicular lines.','Extend the lines mentally and check the right-angle mark or equal spacing.','recognise or construct line relationships independent of orientation');
 if(c==='SYM')return focus('What makes a fold a line of symmetry?','Every point must meet its matching point exactly.','The two sides only need to look roughly similar.','Matching points lie the same perpendicular distance from the mirror, on opposite sides.','Compare corresponding points and distances, rather than just the overall outline.','justify symmetry by matching points across a mirror');
 if(c==='ANGLE')return /straight|around|opposite|unknown/.test(o)?focus('What must we identify before finding an unknown angle?','The marked relationship that connects the angles.','The angle size suggested by the drawing alone.','A straight turn, a full turn and vertically opposite angles use different facts. The markings decide which fact applies.','Locate the common vertex, the given lines and the complete turn being filled.','justify an unknown angle with the stated angle relationship'):focus('What determines the size of an angle?','The opening between its rays at their shared vertex.','How long its rays are drawn.','Longer sides do not make a wider opening. A square corner is a useful reference; a protractor measures from the correct baseline.','Find the vertex and compare the opening, keeping the baseline fixed.','recognise or measure a turn independently of ray length');
 if(c==='SOLID'||c==='SHAPE'&&/cube|cuboid|cone|sphere|cylinder/.test(o))return focus('What should we follow when a solid is turned or unfolded?','Its faces, surfaces and the way they meet.','Only the outline visible from one viewpoint.','A new view can hide or reveal faces without changing the solid. A net must reconnect all faces without gaps or overlaps.','Count hidden as well as visible faces and follow their shared edges.','recognise a solid or its net through its surface structure');
 if(/pattern/.test(o))return focus('What tells us which shape comes next in a pattern?','The complete unit that repeats.','Only the last shape we can see.','The repeated unit may involve shape, size, colour or orientation. Check it across more than one repetition.','Name the changing attributes and find where the unit starts again.','continue a shape pattern using its full repeated unit');
 if(/copy|draw/.test(o))return focus('What must we preserve when copying or drawing this figure?','The required distances, directions and corner relationships.','Only the number of corners.','Many different figures have the same number of corners. Corresponding positions and required properties determine this one.','Choose a starting point, follow each edge in order and check the closing edge.','construct a figure using its stated measurements or grid relationships');
 if(/compose|decompose/.test(o))return focus('How can smaller pieces make a larger shape?','Their edges fit without gaps or overlaps in the intended region.','Any pieces make the shape if there are enough of them.','The pieces must cover exactly the required region. Turning a piece changes its position, not its size.','Follow the joining edges and check the region that the pieces cover together.','explain a shape by composing or separating its parts');
 if(/angle|triangle|quadrilateral|parallelogram|rhombus|trapezium/.test(o)&&p.level>=5)return focus('What makes an angle calculation valid in a figure?','The given shape properties and marked angle relationships.','A guess that the picture looks symmetric.','Equal sides, parallel sides and complete angle sums supply different information. Use only what is given or follows from the named shape.','Identify the relevant property before combining angle facts. Do not invent extra lines or equalities.','connect shape properties with justified angle calculations');
 return focus('When a shape is turned, what stays the same?','Its defining sides, corners and curved boundaries.','Its name changes whenever its orientation changes.','Position and orientation can change while the shape’s defining properties remain.','Follow the full boundary and check the features needed for its name.','recognise a shape from its properties rather than its orientation');
}
function conversion():TeachingFocus{return focus('When a measurement is written in smaller units, what changes?','The number of units, while the measured quantity stays the same.','The object itself becomes larger.','Smaller units are needed in greater numbers. The named unit relationship, rather than a universal decimal rule, determines the factor.','Write the relationship between the two units and track complete units plus any remainder.','justify a conversion while preserving the measured quantity');}
