import {describe,it,expect} from 'vitest';
import {ACTIVITIES,activitiesFor} from './catalog';
import {CURRICULUM_SKILLS} from '../school/curriculum';
import {makeQuestion,gameSession,correctAnswer,numberValue,type Proof} from './generate';
import {applyPrimary,initialPrimary} from './progress';
function evaluate(p:Proof):number{if(typeof p==='number')return p;const a=evaluate(p.a),b=evaluate(p.b);switch(p.op){case '+':return a+b;case '-':return a-b;case '*':return a*b;case '/':return a/b;case 'round':return Math.round(a/b+1e-8)*b;case 'floor':return Math.floor(a/b)*b;}}
describe('grade-specific playable catalog',()=>{
 it('offers at least twenty activities for each primary level and foundation path',()=>{for(let level=1;level<=6;level++)expect(activitiesFor(level,'standard').length).toBeGreaterThanOrEqual(20);for(const level of [5,6])expect(activitiesFor(level,'foundation').length).toBeGreaterThanOrEqual(20);expect(new Set(ACTIVITIES.map(a=>a.id)).size).toBe(ACTIVITIES.length);});
 it('references real MOE objectives, keeping upper-primary-only concepts out of foundation',()=>{for(const a of ACTIVITIES){for(const id of a.skillIds)expect(CURRICULUM_SKILLS.find(s=>s.id===id),`${a.title}: ${id}`).toBeDefined();if(a.track==='foundation')expect(['ratio','ratioShare','algebra','equation','circle','reversePercent','percentChange']).not.toContain(a.kind);if(a.level<4)expect(['decimalPlace','decimalMultiply','factor','multiple','mixedFraction']).not.toContain(a.kind);}});
 it('generates 200 reproducible, valid questions per activity with independently evaluated numerical answers',()=>{for(const a of ACTIVITIES)for(let seed=0;seed<200;seed++){const q=makeQuestion(a,seed);expect(q.prompt.length,a.id).toBeGreaterThan(8);expect(q.hint.length,a.id).toBeGreaterThan(8);expect(q.explanation.length,a.id).toBeGreaterThan(4);expect(q.answer,a.id).not.toMatch(/NaN|Infinity|undefined/);expect(correctAnswer(q,q.answer),`${a.id}: ${q.answer}`).toBe(true);if(q.proof!==undefined){const reference=evaluate(q.proof);expect(Number.isFinite(reference),a.id).toBe(true);expect(numberValue(q.answer),`${a.id}: ${q.prompt}`).toBeCloseTo(reference,5);}if(q.choices){expect(new Set(q.choices).size).toBe(q.choices.length);expect(q.choices.length,a.id).toBeGreaterThanOrEqual(2);expect(q.choices.filter(c=>correctAnswer(q,c)).length,`${a.id}: ${q.choices.join('|')}`).toBe(1);}expect(makeQuestion(a,seed)).toEqual(q);}},30000);
 it('gives non-repeating sessions and accepts valid equivalent fractions',()=>{for(const a of ACTIVITIES){const session=gameSession(a,934);expect(session.length,a.id).toBeGreaterThanOrEqual(3);expect(new Set(session.map(q=>JSON.stringify([q.prompt,q.display,q.picture,q.answer]))).size).toBe(session.length);}const q={key:'test',prompt:'A fraction',answer:'1/2',hint:'',explanation:''};expect(correctAnswer(q,'2/4')).toBe(true);expect(correctAnswer(q,'0.5')).toBe(true);expect(correctAnswer({...q,requireSimplified:true},'2/4')).toBe(false);expect(correctAnswer(q,'1/0')).toBe(false);expect(correctAnswer({...q,order:['2','10'],answer:'2,10'},'21,0')).toBe(false);});
 it('keeps progress separated by grade/activity and track',()=>{let p=initialPrimary();const a=activitiesFor(1,'standard')[0],b=activitiesFor(6,'standard')[0];p=applyPrimary(p,{id:'a',at:1000,kind:'primary_answer',activityId:a.id,correct:true,firstTry:true,tries:1,hints:0});p=applyPrimary(p,{id:'b',at:1000,kind:'primary_complete',activityId:b.id,stars:2});expect(p.activities[a.id].attempts).toBe(1);expect(p.activities[b.id].attempts).toBe(0);expect(p.activities[b.id].stars).toBe(2);expect(applyPrimary(p,{id:'c',at:1000,kind:'primary_selection',level:2,track:'foundation'}).selection?.track).toBe('standard');});
});
