import { useEffect,useState } from 'react';
import { activitiesFor,activityById,type Activity } from './catalog';
import { CURRICULUM_SKILLS,type Track } from '../school/curriculum';
import { useAccount } from '../school/AccountContext';
import { useProgress } from '../state/ProgressContext';
import { useSessions } from './SessionContext';
import { activityBand } from './progress';
import { resumePosition,type PrimarySession } from './session';
import { TopicPreview } from './TopicPreview';
import { lessonsForActivity,lessonsForLevel } from '../teach/index';
import { learningRewards } from '../teach/rewards';
import './primary.css';
const yearCopy=[['Little ideas. Big adventures.','Build numbers to 100, discover shapes and tell the time.'],['Curiosity is your superpower.','Explore numbers to 1,000, equal groups and your first fractions.'],['Ready for your next discovery?','Tackle numbers to 10,000, equivalent fractions, area and graphs.'],['Think deeper. Try something new.','Explore decimals, factors, symmetry and three-dimensional shapes.'],['Connect your mathematical ideas.','Put fractions, percentages, rate and geometry to work.'],['Make your next breakthrough.','Reason with ratios, algebra, percentages, circles and averages.']];
const PATHS:Record<number,Record<Track,string>>={5:{standard:'Whole numbers, fractions, decimals, percentage, rate, triangles, volume and angles.',foundation:'Whole numbers, fractions, decimals, rate, measurement, angles and graphs, in smaller steps.'},6:{standard:'Fraction division, percentage, ratio, algebra, circles, volume and averages.',foundation:'Fractions, decimals, percentage, area, volume, angles and averages, in smaller steps.'}};
const INTRO_KEY='math-for-primary.intro-dismissed.v1';
const skillTitle=(a:Activity)=>CURRICULUM_SKILLS.find(s=>s.id===a.skillIds[0])?.title??a.title;
const pathOf=(a:Activity)=>`P${a.level}${a.track==='foundation'?' Foundation':''}`;
export function ago(at:number,now=Date.now()){const m=Math.round((now-at)/60000);if(m<1)return 'just now';if(m<60)return `${m} min ago`;const h=Math.round(m/60);if(h<24)return `${h} h ago`;const d=Math.round(h/24);return d<=1?'yesterday':`${d} days ago`;}
function flag(key:string,set=false){try{if(set)localStorage.setItem(key,'1');return localStorage.getItem(key)==='1'}catch{return set}}
const Stars=({n}:{n:number})=><span className="activity-stars" aria-label={`${n} of 3 stars`}>{'★'.repeat(n)}{'☆'.repeat(3-n)}</span>;
const Dots=({s}:{s:PrimarySession})=><span className="session-dots" aria-hidden="true">{Array.from({length:s.count},(_,i)=><i key={i} className={i<s.results.length?'done':i===s.results.length?'now':''}/>)}</span>;
export function PrimaryHome(){
 const {user,classes}=useAccount(),{progress,emit,syncStatus,status}=useProgress(),{unfinished,isUploaded}=useSessions();const chosen=progress.primary?.selection;
 const level=chosen?.level??classes[0]?.level??1,track:Track=level<5?'standard':chosen?.track??(classes[0]?.track==='foundation'?'foundation':'standard');
 const [strand,setStrand]=useState('All adventures');const all=activitiesFor(level,track),activities=all.filter(a=>strand==='All adventures'||a.strand===strand);
 const records=progress.primary?.activities||{},completed=all.filter(a=>records[a.id]?.sessions).length,stars=all.reduce((n,a)=>n+(records[a.id]?.stars||0),0);
 const [intro,setIntro]=useState(()=>!user&&!progress.totals.attempted&&!flag(INTRO_KEY));
 useEffect(()=>{const t=window.setTimeout(()=>void import('./PrimaryGame'),1500);return()=>clearTimeout(t);},[]);
 function select(n:number,t:Track=track){setStrand('All adventures');emit({id:crypto.randomUUID(),at:Date.now(),kind:'primary_selection',level:n,track:n<5?'standard':t});}
 const open=unfinished.filter(s=>activityById(s.activityId)),resume=open[0],openBy=new Map(open.map(s=>[s.activityId,s]));
 const others=all.filter(a=>a.id!==resume?.activityId);
 const next=others.find(a=>!records[a.id]?.sessions)??others.slice().sort((a,b)=>(records[a.id]?.lastAt||0)-(records[b.id]?.lastAt||0))[0]??all[0];
 const recent=Object.entries(records).filter(([id,r])=>activityById(id)&&r.lastAt).sort((a,b)=>b[1].lastAt-a[1].lastAt).slice(0,3);
 const saved=(s:PrimarySession)=>user?.role!=='student'?'Saved on this device':isUploaded(s.activityId)?'Saved to your school account':status.state==='saved'&&s.results.length?'Answers saved to your school account':'Saved on this device';
 const resumeActivity=resume&&activityById(resume.activityId)!;
 const rewards=learningRewards(progress),lessons=lessonsForLevel(level,track);
 return <main className={`primary-home grade-${level}`}>
 <header className="primary-intro"><div><p className="primary-eyebrow">{user?.role==='student'?`Hello, ${user.name}`:'Your mathematics adventure'}</p><h1>{track==='foundation'?'Build confidence, one idea at a time.':yearCopy[level-1][0]}</h1><p>{track==='foundation'?'A dedicated Foundation path, with clear steps and plenty of visual practice.':yearCopy[level-1][1]}</p></div><div className="primary-art" aria-hidden="true"><span>+</span><span>⅓</span><span>×</span><span>◇</span><i>✦</i></div></header>
 <div className="home-rewards" aria-label="Your learning so far"><span><b>{rewards.xp}</b> XP · Level {rewards.level.level}</span><span><b>{rewards.gems}</b> Math Gems</span><span><b>{rewards.streak}</b> day streak</span>{rewards.mastered>0&&<span><b>{rewards.mastered}</b> skills mastered</span>}</div>
 {resume&&resumeActivity&&<section className="continue-panel" aria-labelledby="continue-title"><a className="continue-card" href={`#/activity/${resumeActivity.id}`}><span className="continue-preview"><TopicPreview kind={resumeActivity.kind}/></span><span className="continue-copy"><span className="primary-eyebrow">Continue where you left off · {pathOf(resumeActivity)}</span><strong id="continue-title">{resumeActivity.title}</strong><span className="continue-meta">{resume.mode==='repair'?'Repairing tricky questions · ':''}Question {resumePosition(resume)+1} of {resume.count} · {saved(resume)} · {ago(resume.updatedAt)}</span><Dots s={resume}/></span><span className="adventure-start">Continue <b aria-hidden="true">→</b></span></a>
  {open.length>1&&<div className="also-open"><span>Also unfinished</span>{open.slice(1,4).map(s=>{const a=activityById(s.activityId)!;return <a key={s.id} href={`#/activity/${a.id}`}>{a.title}<small>{pathOf(a)} · question {resumePosition(s)+1} of {s.count}</small></a>;})}</div>}</section>}
 {intro&&<section className="how-to-play" aria-labelledby="how-title"><div><p className="primary-eyebrow">New here?</p><h2 id="how-title">How to play</h2><ol><li><strong>Choose your primary level.</strong> Each level has its own activities.</li><li><strong>Pick an activity.</strong> Look, think and answer. Ask for a clue when you are stuck.</li><li><strong>Stop whenever you like.</strong> Your place is saved on this device, even in the middle of an activity.</li></ol><p className="how-note">Made with the help of AI: if something looks wrong, check it with a teacher or parent.</p></div><button onClick={()=>{flag(INTRO_KEY,true);setIntro(false);}}>Got it</button></section>}
 <section className="primary-selector" aria-label="Choose your primary level"><div className="selector-heading"><h2>Choose your primary level</h2>{user?.role==='student'&&classes[0]&&<span>Your class: {classes[0].year} · P{classes[0].level} {classes[0].name}</span>}</div><div className="primary-years">{[1,2,3,4,5,6].map(n=><button key={n} aria-pressed={level===n} className={level===n?'selected':''} onClick={()=>select(n)}><small>PRIMARY</small><strong>{n}</strong><span>{['Discover','Explore','Build','Connect','Apply','Reason'][n-1]}</span></button>)}</div>
  {level>=5&&<div className="path-choice" role="group" aria-label={`Primary ${level} curriculum path`}>{(['standard','foundation'] as Track[]).map(t=><button key={t} aria-pressed={track===t} className={track===t?'selected':''} onClick={()=>select(level,t)}><strong>{t==='standard'?'Standard Mathematics':'Foundation Mathematics'}</strong><span>{activitiesFor(level,t).length} activities · {PATHS[level][t]}</span></button>)}</div>}
  <p className="selector-note">Selecting a level loads its own activities. {user?.role==='student'?'You can explore other levels without changing your school class.':'No sign-in needed to start.'}</p></section>
 <div className="home-next">{lessons.length>0&&<a className="learn-entry" href="#/teach"><span className="objective-preview"><TopicPreview kind={next.kind}/></span><span className="objective-copy"><span className="primary-eyebrow">Learn a new idea · P{level}</span><strong>{lessons.length} {lessons.length===1?'lesson':'lessons'} that teach the idea first</strong><span>Explore with models, work through examples, then show what you know.</span></span><span className="adventure-start">Learn <b aria-hidden="true">→</b></span></a>}<a className="next-objective" href={`#/activity/${next.id}`}><span className="objective-preview"><TopicPreview kind={next.kind}/></span><span className="objective-copy"><span className="primary-eyebrow">{resume?'Up next':'Your next objective'} · P{level}{track==='foundation'?' Foundation':''}</span><strong>{skillTitle(next)}</strong><span>Activity: {next.title}{next.parameter==='review'?' · prerequisite review':''}</span></span><span className="adventure-start">{records[next.id]?.sessions?'Practise again':'Start'} <b aria-hidden="true">→</b></span></a>
  {recent.length>0&&<section className="recent-strip" aria-labelledby="recent-title"><h2 id="recent-title">Recently</h2><ul>{recent.map(([id,r])=>{const a=activityById(id)!;return <li key={id}><a href={`#/activity/${id}`}><span className="recent-title">{a.title}</span><span className="recent-meta">{pathOf(a)} · {r.firstTry} of {r.attempts} answers first time · {ago(r.lastAt)}</span><Stars n={r.stars}/></a></li>;})}</ul></section>}</div>
 <div className="activity-heading"><div><h2>Pick your next discovery</h2><p>{all.length} activities · {completed} explored · {stars} stars collected</p></div><a href="#/curriculum">View syllabus map ↗</a></div>
 <nav className="strand-tabs" aria-label="Activity strand">{['All adventures','Number & Algebra','Measurement & Geometry','Statistics'].map(s=><button key={s} aria-pressed={strand===s} className={strand===s?'selected':''} onClick={()=>setStrand(s)}>{s==='Number & Algebra'?'Numbers & algebra':s==='Measurement & Geometry'?'Measure & geometry':s==='Statistics'?'Data & graphs':s}</button>)}</nav>
 <div className="activity-grid">{activities.map((a,i)=>{const s=openBy.get(a.id),r=records[a.id];const lesson=lessonsForActivity(a.id)[0];return <div className="activity-card-wrap" key={a.id}>{lesson&&<a className="card-learn" href={`#/teach/${lesson.id}`}>Learn it first</a>}<a href={`#/activity/${a.id}`} className={`activity-card strand-${a.strand==='Number & Algebra'?'number':a.strand==='Statistics'?'data':'shape'}`}><div className="activity-card-top"><span className="activity-thumb"><TopicPreview kind={a.kind}/></span><span className="activity-number">{String(i+1).padStart(2,'0')}</span></div><h3>{a.title}</h3><p>{skillTitle(a)}</p><div className="activity-card-foot">{s?<span className="card-progress">In progress · question {resumePosition(s)+1} of {s.count}</span>:<span>{activityBand(r)}</span>}<Stars n={r?.stars||0}/></div>{s&&<span className="card-meter" aria-hidden="true"><i style={{width:`${s.results.length/s.count*100}%`}}/></span>}{a.parameter==='review'&&<small>Prerequisite review</small>}</a></div>;})}</div>
 <footer className="primary-footer"><p className="ai-note"><strong>Made with the help of AI.</strong> Questions, explanations and diagrams can contain mistakes. Use this app as a learning resource with a teacher or parent, and check anything that looks wrong.</p><p>Based on the MOE Primary Mathematics syllabus, updated October 2025. Activities practise selected objectives; this is not an official or MOE-endorsed resource or assessment.</p><div><a href="#/teach">Learn lessons</a><a href="#/lab">Math Lab</a><a href="#/coverage">Coverage map</a><a href="#/foundations">Original guided lessons</a><a href="#/progress">My progress</a><a href="#/about">About, privacy &amp; AI</a>{!user&&<a href="#/about/passport">Save or move guest progress</a>}<span>{syncStatus}</span></div></footer></main>;
}
