import { useEffect,useRef,useState } from 'react';
import { activitiesFor,activityById,type Activity } from './catalog';
import { CURRICULUM_SKILLS,type Track } from '../school/curriculum';
import { useAccount } from '../school/AccountContext';
import { useProgress } from '../state/ProgressContext';
import { activityBand } from './progress';
import { gameSession,correctAnswer,type Question } from './generate';
import { Picture } from './Picture';
import { freshSeed } from '../engine/random';
import { SpeakButton } from '../ui/SpeakButton';
import './primary.css';
const yearCopy=[['Little ideas. Big adventures.','Build numbers to 100, discover shapes and tell the time.'],['Curiosity is your superpower.','Explore numbers to 1,000, equal groups and your first fractions.'],['Ready for your next discovery?','Tackle numbers to 10,000, equivalent fractions, area and graphs.'],['Think deeper. Try something new.','Explore decimals, factors, symmetry and three-dimensional shapes.'],['Connect your mathematical ideas.','Put fractions, percentages, rate and geometry to work.'],['Make your next breakthrough.','Reason with ratios, algebra, percentages, circles and averages.']];
export function PrimaryHome(){
 const {user,classes}=useAccount(),{progress,emit,syncStatus}=useProgress();const chosen=progress.primary?.selection;
 const level=chosen?.level??classes[0]?.level??1,track:Track=level<5?'standard':chosen?.track??(classes[0]?.track==='foundation'?'foundation':'standard');
 const [strand,setStrand]=useState('All adventures');const all=activitiesFor(level,track),activities=all.filter(a=>strand==='All adventures'||a.strand===strand);
 const records=progress.primary?.activities||{},completed=all.filter(a=>records[a.id]?.sessions).length,stars=all.reduce((n,a)=>n+(records[a.id]?.stars||0),0);
 function select(n:number,t:Track=track){setStrand('All adventures');emit({id:crypto.randomUUID(),at:Date.now(),kind:'primary_selection',level:n,track:n<5?'standard':t});}
 const next=all.find(a=>!records[a.id]?.sessions)||all.slice().sort((a,b)=>(records[a.id]?.lastAt||0)-(records[b.id]?.lastAt||0))[0];
 return <main className={`primary-home grade-${level}`}><header className="primary-intro"><div><p className="primary-eyebrow">{user?.role==='student'?`Hello, ${user.name}`:'Your mathematics adventure'}</p><h1>{track==='foundation'?'Build confidence, one idea at a time.':yearCopy[level-1][0]}</h1><p>{track==='foundation'?'A dedicated Foundation path, with clear steps and plenty of visual practice.':yearCopy[level-1][1]}</p></div><div className="primary-art" aria-hidden="true"><span>+</span><span>⅓</span><span>×</span><span>◇</span><i>✦</i></div></header>
 <section className="primary-selector" aria-label="Choose your primary level"><div className="selector-heading"><h2>Choose your primary level</h2>{user?.role==='student'&&classes[0]&&<span>Your class: {classes[0].year} · P{classes[0].level} {classes[0].name}</span>}</div><div className="primary-years">{[1,2,3,4,5,6].map(n=><button key={n} aria-pressed={level===n} className={level===n?'selected':''} onClick={()=>select(n)}><small>PRIMARY</small><strong>{n}</strong><span>{['Discover','Explore','Build','Connect','Apply','Reason'][n-1]}</span></button>)}</div>{level>=5&&<div className="track-switch" role="group" aria-label="Curriculum path"><button aria-pressed={track==='standard'} className={track==='standard'?'selected':''} onClick={()=>select(level,'standard')}>Standard Mathematics</button><button aria-pressed={track==='foundation'} className={track==='foundation'?'selected':''} onClick={()=>select(level,'foundation')}>Foundation Mathematics</button></div>}<p className="selector-note">Selecting a level loads its own activities. {user?.role==='student'?'You can explore other levels without changing your school class.':'No sign-in needed to start.'}</p></section>
 <a className="daily-adventure" href={`#/activity/${next.id}`}><span className="adventure-emblem">✦</span><div><p className="primary-eyebrow">YOUR NEXT ADVENTURE · P{level}{track==='foundation'?' FOUNDATION':''}</p><h2>{next.title}</h2><p>{CURRICULUM_SKILLS.find(s=>s.id===next.skillIds[0])?.title}</p></div><span className="adventure-start">Let’s play <b>→</b></span></a>
 <div className="activity-heading"><div><h2>Pick your next discovery</h2><p>{all.length} activities · {completed} explored · {stars} stars collected</p></div><a href="#/curriculum">View syllabus map ↗</a></div>
 <nav className="strand-tabs" aria-label="Activity strand">{['All adventures','Number & Algebra','Measurement & Geometry','Statistics'].map(s=><button key={s} aria-pressed={strand===s} className={strand===s?'selected':''} onClick={()=>setStrand(s)}>{s==='Number & Algebra'?'Numbers & algebra':s==='Measurement & Geometry'?'Measure & geometry':s==='Statistics'?'Data & graphs':s}</button>)}</nav>
 <div className="activity-grid">{activities.map((a,i)=><a href={`#/activity/${a.id}`} key={a.id} className={`activity-card strand-${a.strand==='Number & Algebra'?'number':a.strand==='Statistics'?'data':'shape'}`}><div className="activity-card-top"><span className="activity-icon">{a.kind.startsWith('fraction')?'⅔':a.kind.includes('ecimal')?'0.5':a.kind.startsWith('ratio')?'2:3':a.kind.includes('ercent')?'%':a.kind==='clock'?'◷':a.icon}</span><span className="activity-number">{String(i+1).padStart(2,'0')}</span></div><h3>{a.title}</h3><p>{CURRICULUM_SKILLS.find(s=>s.id===a.skillIds[0])?.title}</p><div className="activity-card-foot"><span>{activityBand(records[a.id])}</span><span className="activity-stars" aria-label={`${records[a.id]?.stars||0} of 3 stars`}>{'★'.repeat(records[a.id]?.stars||0)}{'☆'.repeat(3-(records[a.id]?.stars||0))}</span></div>{a.parameter==='review'&&<small>Prerequisite review</small>}</a>)}</div>
 <footer className="primary-footer"><p>Based on the MOE Primary Mathematics syllabus, updated October 2025. Activities practise selected objectives; this is not an MOE-endorsed assessment.</p><div><a href="#/foundations">Original guided lessons</a><a href="#/progress">My progress</a><span>{syncStatus}</span></div></footer></main>;
}
interface RoundResult{answer:string;correct:boolean;firstTry:boolean;hints:number;tries:number}
function Round({q,level,onNext}:{q:Question;level:number;onNext:(r:RoundResult)=>void}){
 const [answer,setAnswer]=useState(''),[ordered,setOrdered]=useState<string[]>([]),[shaded,setShaded]=useState<number[]>([]),[tries,setTries]=useState(0),[hint,setHint]=useState(false),[status,setStatus]=useState<'answering'|'wrong'|'correct'|'revealed'>('answering');
 const [sent,setSent]=useState(false),sentRef=useRef(false),input=useRef<HTMLInputElement>(null);
 const done=status==='correct'||status==='revealed';
 const current=q.order?ordered.join(','):q.fractionBuilder?`${shaded.length}/${q.fractionBuilder}`:answer;
 function check(value=current){if(done)return;const yes=correctAnswer(q,value);setTries(t=>t+1);setStatus(yes?'correct':'wrong');}
 useEffect(()=>{if(!q.choices&&!q.order&&!q.fractionBuilder&&level>2)input.current?.focus()},[q,level]);
 const submit=()=>{if(sentRef.current)return;sentRef.current=true;setSent(true);onNext({answer:current,correct:status==='correct',firstTry:status==='correct'&&tries===1&&!hint,hints:Number(hint),tries:Math.max(1,tries)});};
 return <div className="round-layout"><section className="play-question"><div className="question-topline"><span>LOOK · THINK · TRY</span><SpeakButton text={`${q.prompt} ${q.display||''}`}/></div><h2>{q.prompt}</h2>{q.display&&<div className="math-display">{q.display}</div>}{q.picture&&<Picture model={q.picture}/>} {q.fractionBuilder&&<div className="fraction-builder" style={{gridTemplateColumns:`repeat(${Math.min(q.fractionBuilder,6)},1fr)`}} aria-label="Equal parts to shade">{Array.from({length:q.fractionBuilder},(_,i)=><button key={i} disabled={done} aria-label={`Part ${i+1}`} aria-pressed={shaded.includes(i)} className={shaded.includes(i)?'shaded':''} onClick={()=>{setShaded(s=>s.includes(i)?s.filter(n=>n!==i):[...s,i]);setStatus('answering')}}>{shaded.includes(i)?'✓':''}</button>)}</div>}
 {q.order&&<><div className="order-slots" aria-label="Your order">{q.order.map((_,i)=><button disabled={done} key={i} onClick={()=>setOrdered(o=>o.filter((_,j)=>j!==i))}>{ordered[i]||'?'}</button>)}</div><div className="order-choices">{q.order.filter(n=>!ordered.includes(n)).map(n=><button disabled={done} key={n} onClick={()=>{setOrdered(o=>[...o,n]);setStatus('answering')}}>{n}</button>)}</div></>}
 {q.choices&&<div className="answer-choices">{q.choices.map(value=><button disabled={done} className={answer===value?(status==='wrong'?'picked wrong':'picked'):''} key={value} onClick={()=>{setAnswer(value);check(value)}}>{value}</button>)}</div>}
 {!q.choices&&!q.order&&!q.fractionBuilder&&<form onSubmit={e=>{e.preventDefault();check()}}><label className="answer-input">Your answer<span><input ref={input} aria-label="Your answer" value={answer} onChange={e=>{setAnswer(e.target.value);setStatus('answering')}} disabled={done} autoComplete="off" inputMode={q.answer.includes('/')?'text':'decimal'} placeholder={q.answer.includes('/')?'e.g. 3/4':'Type a number'}/>{q.unit&&<b>{q.unit}</b>}</span></label>{level<=2&&!done&&<div className="primary-keypad">{['1','2','3','4','5','6','7','8','9',q.answer.includes('/')?'/':'.','0','⌫'].map(key=><button type="button" key={key} aria-label={key==='⌫'?'Delete digit':key} onClick={()=>{setAnswer(a=>key==='⌫'?a.slice(0,-1):a+key);setStatus('answering')}}>{key}</button>)}</div>}{!done&&<button className="check-answer" disabled={!answer.trim()}>Check my answer →</button>}</form>}
 {!done&&(q.order||q.fractionBuilder)&&<button className="check-answer" disabled={!!q.order&&ordered.length!==q.order.length} onClick={()=>check()}>Check my answer →</button>}
 </section><aside className="play-coach"><div className="coach-star" aria-hidden="true">✦</div><h3>{status==='correct'?'You found it!':status==='revealed'?'Let’s learn from this.':status==='wrong'?'Try another way.':'Every attempt grows your thinking.'}</h3><div aria-live="polite">{status==='wrong'&&<p>That answer doesn’t fit yet. Use the clue, check the units, and have another go.</p>}{done&&<><p className="solution-answer">{status==='correct'?'✓ ':''}{q.order?q.answer.split(',').join(' → '):q.answer} {q.unit}</p><p>{q.explanation}</p></>}</div>{hint&&!done&&<p className="hint-box">{q.hint}</p>}{!done&&<div className="coach-actions"><button disabled={hint} onClick={()=>setHint(true)}>{hint?'Clue opened':'Give me a clue'}</button>{(hint||tries>=2)&&<button onClick={()=>setStatus('revealed')}>Show the steps</button>}</div>}{done&&<button className="check-answer next-answer" disabled={sent} onClick={submit}>Next discovery →</button>}<p className="coach-note">{done?'Understanding matters more than speed.':'No rush. You can use paper to show your working.'}</p></aside></div>;
}
export function PrimaryGame({id}:{id:string}){const activity=activityById(id);return activity?<Game key={id} activity={activity}/>:<main className="school-page"><h1>Let’s find another adventure.</h1><a href="#/">Choose a primary level →</a></main>;}
function Game({activity}:{activity:Activity}){
 const {emit,syncStatus}=useProgress();const [questions,setQuestions]=useState(()=>gameSession(activity,freshSeed())),[index,setIndex]=useState(0),[results,setResults]=useState<RoundResult[]>([]),[confirmStop,setConfirmStop]=useState(false);const completeRef=useRef(false);
 const finished=index>=questions.length,clean=results.filter(r=>r.firstTry).length,stars=clean/results.length>=.85?3:clean/results.length>=.5?2:1;
 function next(result:RoundResult){const nextResults=[...results,result];emit({id:crypto.randomUUID(),at:Date.now(),kind:'primary_answer',activityId:activity.id,questionKey:questions[index].key,...result});setResults(nextResults);setIndex(i=>i+1);if(index===questions.length-1&&!completeRef.current){completeRef.current=true;const count=nextResults.filter(r=>r.firstTry).length;emit({id:crypto.randomUUID(),at:Date.now(),kind:'primary_complete',activityId:activity.id,stars:count/nextResults.length>=.85?3:count/nextResults.length>=.5?2:1});}}
 function replay(repair=false){const misses=questions.filter((_,i)=>!results[i]?.firstTry);setQuestions(repair&&misses.length?misses.map((q,i)=>({...q,key:q.key+'-repair-'+i})):gameSession(activity,freshSeed()));setIndex(0);setResults([]);completeRef.current=false;}
 if(finished)return <main className="game-complete"><div className="completion-orbit">{'★'.repeat(stars)}{'☆'.repeat(3-stars)}</div><p className="primary-eyebrow">PRIMARY {activity.level} · {activity.track.toUpperCase()}</p><h1>Another discovery made.</h1><h2>{activity.title}</h2><p>{clean} of {results.length} solved first time without a clue.</p><p>{results.filter(r=>r.correct).length} solved before viewing the steps. Keep practising the ideas that felt new.</p><div className="completion-actions"><a className="check-answer" href="#/">Back to my adventures</a><button onClick={()=>replay()}>Play fresh questions</button>{clean<results.length&&<button onClick={()=>replay(true)}>Repair my tricky questions</button>}</div><p role="status">{syncStatus}</p></main>;
 return <main className={`primary-game grade-${activity.level}`}><header className="play-header"><button onClick={()=>setConfirmStop(true)} aria-label="Leave activity">×</button><div><p>P{activity.level} {activity.track==='foundation'?'Foundation':'Mathematics'} · {activity.strand}</p><h1>{activity.title}</h1></div><span>{index+1} / {questions.length}</span></header><div className="quest-track" role="progressbar" aria-label="Activity progress" aria-valuemin={0} aria-valuemax={questions.length} aria-valuenow={index}>{questions.map((_,i)=><span key={i} className={i<index?'done':i===index?'current':''}>{i<index?'✓':i===index?'✦':'·'}</span>)}</div><Round key={questions[index].key} q={questions[index]} level={activity.level} onNext={next}/><footer className="game-source">Primary {activity.level} · Diagrams may not be to scale. <span role="status">{syncStatus}</span></footer>{confirmStop&&<div className="stop-panel" role="alert"><strong>Leave this adventure?</strong><p>Answers you have advanced past are saved. Finish the activity to collect its stars.</p><button onClick={()=>setConfirmStop(false)}>Keep playing</button><a href="#/">Back to adventures</a></div>}</main>;
}
