import { useEffect,useRef,useState,type ReactNode } from 'react';
import { useAccount } from './AccountContext';
import { useProgress } from '../state/ProgressContext';
import { useSessions } from '../primary/SessionContext';
import { isUnfinished } from '../primary/session';
import { makePassport,readPassport,type Passport } from '../primary/passport';
import { browserStorage } from '../primary/sessionStore';
import { readAttempts,writeAttempt,clearAttempts,type LessonAttempt } from '../teach/progress';
import { initialProgress } from '../state/progress';
import './school.css';
const API_HOST='math-for-primary-school-api.soujanya-poria.chatgpt.site';
function Section({id,eyebrow,title,children}:{id?:string;eyebrow:string;title:string;children:ReactNode}){return <section className="school-panel about-section" id={id}><p className="school-eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</section>;}
const summary=(p:Passport)=>{const acts=Object.values(p.progress.primary?.activities||{});const lessons=Object.keys(p.progress.nodes||{}).filter(id=>id.startsWith('learn.')&&!id.endsWith('.review')).length;return `${acts.filter(a=>a.attempts).length} activities explored · ${lessons} lessons finished · ${p.progress.totals.attempted} answers · ${p.progress.totals.stars} stars · ${p.sessions.filter(isUnfinished).length} unfinished${p.at?` · saved ${new Date(p.at).toLocaleString('en-SG',{dateStyle:'medium',timeStyle:'short'})}`:''}`;};
/** Guest progress travels as a code or file the guest keeps; nothing is uploaded. */
function PassportTools(){
 const {progress,restoreLocal,scope}=useProgress(),{all,restore,clear}=useSessions();const kv=browserStorage();
 const [code,setCode]=useState(''),[paste,setPaste]=useState(''),[preview,setPreview]=useState<Passport|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[confirmClear,setConfirmClear]=useState(false);
 async function create(){setBusy(true);setMessage('');try{setCode(await makePassport(progress,Object.values(all),{lessons:readAttempts(kv,scope)}));}catch{setMessage('This browser could not create a passport.');}finally{setBusy(false);}}
 async function copy(){try{await navigator.clipboard.writeText(code);setMessage('Passport code copied. Keep it somewhere safe, such as a note or an email to yourself.');}catch{setMessage('Select the code and copy it by hand.');}}
 function download(){const url=URL.createObjectURL(new Blob([code],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download=`maths-passport-${new Date().toISOString().slice(0,10)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function open(text=paste){setBusy(true);setMessage('');setPreview(null);try{setPreview(await readPassport(text));}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function use(){if(!preview)return;restoreLocal(preview.progress);restore(preview.sessions);for(const a of Object.values(preview.lessons))writeAttempt(kv,scope,a as LessonAttempt);setPreview(null);setPaste('');setMessage('Your passport is open. Your progress and unfinished activities are now on this browser.');}
 function wipe(){restoreLocal(initialProgress());clear();clearAttempts(kv,scope);try{localStorage.removeItem('math-for-primary.intro-dismissed.v1');}catch{/* ignore */}setConfirmClear(false);setCode('');setMessage('Guest progress and unfinished activities were removed from this browser.');}
 return <div className="passport-tools">
  <div className="passport-step"><h3>1. Save your passport</h3><p>Create a code that holds your progress and unfinished activities. Keep it, then open it on another device to carry on.</p><button className="btn" disabled={busy} onClick={()=>void create()}>Create my passport</button>
   {code&&<><label className="passport-code">Your passport code ({code.length.toLocaleString('en-SG')} characters)<textarea readOnly value={code} rows={4} onFocus={e=>e.currentTarget.select()}/></label><div className="loading-actions"><button className="btn btn-soft" onClick={()=>void copy()}>Copy code</button><button className="btn btn-soft" onClick={download}>Download as a file</button></div></>}</div>
  <div className="passport-step"><h3>2. Open a passport</h3><p>Paste a passport code, or choose a passport file.</p><label className="passport-code">Passport code<textarea value={paste} onChange={e=>setPaste(e.target.value)} rows={3} placeholder="MFP1-…"/></label>
   <div className="loading-actions"><button className="btn" disabled={busy||!paste.trim()} onClick={()=>void open()}>Check this passport</button><label className="btn btn-soft file-button">Choose a file<input type="file" accept=".txt,text/plain" onChange={async e=>{const f=e.target.files?.[0];if(f){const text=await f.text();setPaste(text);void open(text);}e.target.value='';}}/></label></div>
   {preview&&<div className="school-note" role="status"><strong>This passport contains:</strong><p>{summary(preview)}</p><p>Opening it replaces the guest progress on this browser.</p><div className="loading-actions"><button className="btn" onClick={use}>Open my passport here</button><button className="btn btn-soft" onClick={()=>setPreview(null)}>Cancel</button></div></div>}</div>
  <div className="passport-step"><h3>Remove guest data</h3><p>Deletes guest progress and unfinished activities from this browser. Passports you saved are not affected.</p>{confirmClear?<div className="loading-actions"><button className="btn" onClick={wipe}>Yes, remove it</button><button className="btn btn-soft" onClick={()=>setConfirmClear(false)}>Keep it</button></div>:<button className="btn btn-soft" onClick={()=>setConfirmClear(true)}>Remove guest data from this browser</button>}</div>
  {message&&<p className="form-message" role="status">{message}</p>}
 </div>;
}
export function AboutScreen({section}:{section?:string}){
 const {user}=useAccount();const passport=useRef<HTMLElement>(null);
 useEffect(()=>{if(section==='passport')document.getElementById('passport')?.scrollIntoView();},[section]);
 return <main className="school-page about-page"><a className="back-link" href="#/">← Back to learning</a><p className="school-eyebrow">About this app</p><h1>Learning maths, openly and safely.</h1><p className="school-lead">What Maths for SG Primary Schools is, how it was made, and what happens to your data.</p>
  <Section eyebrow="Please read" title="Made with the help of AI"><div className="ai-statement"><p><strong>This app was built with the help of AI tools, including its questions, explanations, hints, diagrams and code. AI can make mistakes, and it can sound confident when it is wrong.</strong></p><p>We check the mathematics with automated tests, but a teacher has not reviewed every question, explanation or diagram. Please use Maths for SG Primary Schools as a learning resource under the guidance of a teacher, parent or another adult, and verify what it says. If an answer, explanation or diagram looks wrong, check it with an adult or your school textbook before relying on it.</p><p>The activities follow the MOE Primary Mathematics syllabus, but this is not an official MOE resource, it is not endorsed by MOE, and it is not an examination or formal assessment.</p></div></Section>
  <Section eyebrow="Your privacy" title="How this app handles personal data"><p>We designed the app to collect as little personal data as possible, with Singapore’s Personal Data Protection Act 2012 (PDPA) in mind. This statement explains what happens to data; it is not legal advice.</p>
   <h3>Playing as a guest</h3><p>No account and no personal data are needed. Guest progress and unfinished activities are kept only in this browser’s storage on this device and are not sent to us. You can remove them at any time below, or by clearing this browser’s data.</p>
   <h3>School accounts</h3><p>A school creates accounts for its teachers and pupils. For each account the service stores the name and username the school enters, school and class membership, and a hashed password. Staff sign in with an email address; pupils do not need one. When a pupil uses the app, the service stores their learning records: answers, clues used, stars, activity sessions and app settings.</p><p>These records are used only to let the pupil continue learning on any device, and to let the pupil’s own teachers and school administrators see their progress. We do not sell data, show advertising, or use third-party analytics or tracking in the app.</p>
   <h3>Who can see school data</h3><p>Pupils see their own records. Teachers see pupils in the classes assigned to them. School administrators see their own school. One school’s workspace cannot see another school’s. The service operator can access stored data only to run, secure and maintain the service.</p>
   <h3>The school’s role</h3><p>The school decides which accounts to create and is responsible for its own obligations under the PDPA, including any consent needed from parents or guardians. The service processes school account data on the school’s behalf, for the purposes above. To access, correct or delete a pupil’s data, please ask the school administrator. Administrators can reset passwords and deactivate accounts, and can contact the operator to delete records.</p>
   <h3>Where data is kept and how it is protected</h3><p>The app’s pages are served by GitHub Pages. School account data is stored by the account service ({API_HOST}), which runs on cloud infrastructure provided by Cloudflare and may process data outside Singapore. Passwords are stored as bcrypt hashes. Sign-in tokens expire after eight hours, and only their hashes are stored. The server checks school and class permissions on every request. Deactivating an account stops sign-in and ends its sessions.</p>
   <h3>Browser storage and cookies</h3><p>The app uses this browser’s local and session storage to keep progress, unfinished activities and, for the current tab only, a school sign-in. It does not use advertising or analytics cookies. The account service’s hosting provider may set a short-lived security cookie to protect against automated abuse.</p>
   <h3>How long data is kept</h3><p>Guest data stays in this browser until you remove it. School account data is kept while the school uses the service; the school administrator can ask for it to be deleted. Signing out removes a pupil’s cached progress and unfinished activities from a shared device; answers not yet saved stay on the device until they reach the school account.</p>
   <h3>Questions and requests</h3><p>For questions about this app or a data request, use the contact details on the developer’s website, <a href="https://soujanyaporia.github.io/" target="_blank" rel="noreferrer">soujanyaporia.github.io</a>. Pupils and parents should contact their school first.</p><p className="muted">Last updated 11 September 2026.</p></Section>
  <section ref={passport} className="school-panel about-section" id="passport"><p className="school-eyebrow">Guest learning passport</p><h2>Carry on from where you left off, without an account</h2>
   {user?<p>You are signed in, so your recorded answers are saved to your school account and follow you to any device where you sign in. Passports are for guests.</p>:<><p>Your guest progress lives in this browser. A <strong>learning passport</strong> lets you continue somewhere else without creating an account: the app packs your progress and unfinished activities into a code that <strong>you</strong> keep. We never receive or store it.</p><p className="muted">The code holds learning records only (activities, answers, stars and unfinished questions), not your name or any account details. Anyone who has your code can open that progress, so keep it like a saved game.</p><PassportTools/></>}</section>
 </main>;
}
