import {activityById} from '../primary/catalog';
import {PrimaryClassReport} from '../primary/ClassReport';
import { useEffect,useState,type FormEvent,type ReactNode } from 'react';
import { useAccount } from './AccountContext';
import { useProgress } from '../state/ProgressContext';
import { CURRICULUM,CURRICULUM_SKILLS,curriculumPath,type Track } from './curriculum';
import { lessonById } from '../content/lessons';
import { masteryBand,BAND_LABEL,masteryScore } from '../engine/adaptive';
import { SKILLS } from '../engine/skills';
import type { SkillId } from '../engine/types';
import { initialProgress,applyAttempt,type ProgressState } from '../state/progress';
import './school.css';
export function SchoolNav(){const {user}=useAccount();const {syncStatus}=useProgress();return <nav className="school-nav" aria-label="School navigation"><a className="school-wordmark" href="#/">✦ <span>Maths for SG Primary Schools</span></a><div><a href="#/curriculum">Curriculum</a><a href={user&&user.role!=='student'?'#/school':'#/school-start'}>{user&&user.role!=='student'?'My school':'School setup'}</a><a className="account-link" href="#/account">{user?user.name:'School sign in'} <span aria-hidden="true">↗</span></a></div>{user?.role==='student'&&!user.mustChange&&<span className="sync-label" role="status">{syncStatus}</span>}</nav>}
function Page({eyebrow,title,children}:{eyebrow:string;title:string;children:ReactNode}){return <main className="school-page"><a className="back-link" href="#/">← Back to learning</a><p className="school-eyebrow">{eyebrow}</p><h1>{title}</h1>{children}</main>}
export function AccountScreen(){
 const {user,login,logout,api,refresh,error:accountError}=useAccount(),{sync,syncStatus}=useProgress();
 const [school,setSchool]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[next,setNext]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{if(user){await api('/password','POST',{current:password,password:next});await refresh();setPassword('');setNext('');setMessage('Password changed. Your other sessions have been signed out.');}else{await login(school,username,password);setPassword('');window.location.hash='#/account';}}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function signOut(){setBusy(true);setMessage('');try{if(!await sync())throw new Error('Your progress has not synced yet. Retry when connected before signing out.');await logout();window.location.hash='#/';}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <Page eyebrow="Your learning, wherever you go" title={user?`Hello, ${user.name}`:'Welcome to your school'}><div className="account-grid"><section className="school-panel"><h2>{user?(user.mustChange?'Choose your own password':'Your account'):'School sign in'}</h2>{user&&<><p>{user.schoolName} · {user.role}</p><p className="muted">School code: <strong>{user.schoolCode}</strong> · Username: <strong>{user.username}</strong></p>{!user.mustChange&&<p><a className="btn" href={user.role==='student'?'#/':'#/school'}>{user.role==='student'?'Continue learning':'Open my school'} →</a></p>}</>}
 <form onSubmit={submit} className="school-form">{!user&&<><label>School code<input required value={school} onChange={e=>setSchool(e.target.value.toUpperCase())} autoComplete="organization" placeholder="Given by your teacher"/></label><label>Username or staff email<input required value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" autoCapitalize="none" spellCheck={false}/></label></>}
 <label>{user?'Current password or temporary PIN':'Password or PIN'}<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>
 {user&&<label>New password<input type="password" required minLength={user.role==='student'?8:12} value={next} onChange={e=>setNext(e.target.value)} autoComplete="new-password"/><small>At least {user.role==='student'?8:12} characters. Ask your teacher if you need help.</small></label>}
 <button className="btn" disabled={busy}>{busy?'Please wait…':user?'Change password':'Sign in →'}</button></form>
 {user&&syncStatus.includes('expired')&&<button className="btn btn-soft" disabled={busy||!password} onClick={async()=>{setBusy(true);try{await login(user.schoolCode,user.username,password);setPassword('');setMessage('Reconnected. Your pending progress will sync.');void sync();}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>Reconnect with current password</button>}
 {(message||accountError)&&<p className="form-message" role="status">{message||accountError}</p>}{user&&<><p className="muted">{user.role==='student'?syncStatus:'Sign out when you finish on a shared device.'}</p><button className="btn btn-soft" disabled={busy} onClick={()=>void signOut()}>Sign out</button></>}
 </section><aside className="account-aside"><span className="large-symbol">✦</span><h2>A little practice.<br/>A lot of possibility.</h2><p>Learn with pictures, try a new strategy, and pick up where you left off on another device.</p><div className="school-note"><strong>Just here to play?</strong><p>You can start without an account. Guest progress stays on this browser.</p><a href="#/learn">Explore the lessons →</a></div><p className="muted">Pupils do not need an email address. Your school administrator creates accounts; your teacher can reset your PIN.</p><p><a href="#/school-start">Setting up a school? Start here →</a></p></aside></div></Page>;
}
export function CurriculumScreen(){
 const [level,setLevel]=useState(1),[track,setTrack]=useState<Track>('standard'),[strand,setStrand]=useState('All strands'),[query,setQuery]=useState(''),[open,setOpen]=useState<string|null>(null);
 const skills=curriculumPath(level,track).filter(s=>(strand==='All strands'||s.strand===strand)&&`${s.title} ${s.topic} ${s.id}`.toLowerCase().includes(query.toLowerCase()));
 const topics=[...new Set(skills.map(s=>s.topic))];
 return <Page eyebrow="A connected path · Primary 1–6" title="Every idea builds on another."><p className="school-lead">Explore the Singapore mathematics curriculum, from first number bonds to upper-primary reasoning.</p><div className="curriculum-banner"><span>MOE syllabus · Updated October 2025</span><a href={CURRICULUM.source} target="_blank" rel="noreferrer">View official syllabus ↗</a></div>
 <div className="year-tabs" aria-label="Primary level">{[1,2,3,4,5,6].map(n=><button key={n} className={level===n?'selected':''} aria-pressed={level===n} onClick={()=>{setLevel(n);setOpen(null)}}><small>PRIMARY</small>{n}</button>)}</div>
 <div className="curriculum-filters"><label>Path<select value={level<5?'standard':track} disabled={level<5} onChange={e=>setTrack(e.target.value as Track)}><option value="standard">{level<5?'Common curriculum':'Standard Mathematics'}</option><option value="foundation">Foundation Mathematics</option></select></label><label>Strand<select value={strand} onChange={e=>setStrand(e.target.value)}>{['All strands','Number & Algebra','Measurement & Geometry','Statistics'].map(x=><option key={x}>{x}</option>)}</select></label><label>Find an idea<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Fractions, area, number bonds…" type="search"/></label></div>
 <p className="coverage-note"><strong>{skills.length} mapped objectives</strong> · Filled green labels identify objectives with playable activities. Other objectives have curriculum metadata; their lessons are still to come. Foundation is a separate P5/P6 path.</p>
 <div className="curriculum-topics">{topics.map(topic=><section className="school-panel" key={topic}><p className="school-eyebrow">{skills.find(s=>s.topic===topic)?.strand}</p><h2>{topic}</h2>{skills.filter(s=>s.topic===topic).map(s=><div className="objective" key={s.id}><button aria-expanded={open===s.id} className="objective-button" onClick={()=>setOpen(open===s.id?null:s.id)}><span className={s.status==='available'?'objective-dot available':'objective-dot'}>{s.status==='available'?'✓':'·'}</span><span>{s.title}<small>{s.id}</small></span><span className={`status-pill ${s.status}`}>{s.status==='available'?'Play':'Mapped'}</span><span>{open===s.id?'−':'+'}</span></button>{open===s.id&&<div className="objective-detail"><p>{s.objective}</p><p><strong>Representations:</strong> {s.representations.join(' → ')}</p><p><strong>Builds on:</strong> {s.prerequisites.length?s.prerequisites.map(id=>CURRICULUM_SKILLS.find(x=>x.id===id)!.title).join('; '):'No earlier prerequisite in this map.'}</p><small>MOE syllabus p. {s.sourcePage} · {s.version}. Prerequisite links are our instructional mapping.</small>{s.activityIds.map(id=><a className="lesson-link" href={`#/activity/${id}`} key={id}>{activityById(id)!.title} →</a>)}{s.lessonIds.map(id=><a className="lesson-link" href={`#/lesson/${id}`} key={id}>{lessonById(id)!.title} →</a>)}</div>}</div>)}</section>)}</div>{!topics.length&&<p>No objectives match this search.</p>}</Page>;
}
interface Pupil {id:string;name:string;username:string;active:boolean;updatedAt:number|null;progress:ProgressState}
const monitored:SkillId[]=['add.result','sub.result','add.missing_first','word.translate'];
function demoPupils(level:number):Pupil[]{return ['Aisha Tan','Daniel Lim','Ravi Kumar','Mei Chen','Zara Hassan'].map((name,i)=>{let progress=initialProgress();for(const [j,skill] of monitored.entries())for(let k=0;k<(i===4?0:12);k++){const clean=(k+i+j)%5>(i===2?2:0);progress=applyAttempt(progress,{skill,level:1,correct:true,firstTry:clean,tries:clean?1:2,hints:clean?0:1,revealed:false,format:'equation',at:Date.UTC(2026,8,8+k%3,10),...(i===2&&!clean?{misconception:'off_by_one' as const}:{})});}return {id:`demo-${level}-${i}`,name,username:`p${level}_${i+1}`,active:true,updatedAt:i===4?null:Date.UTC(2026,8,10),progress};});}
function csvCell(s:unknown){const value=String(s??'');return '"'+(/^[=+@\-\t\r]/.test(value)?"'"+value:value).replaceAll('"','""')+'"';}
function downloadCsv(name:string,rows:unknown[][]){const blob=new Blob([rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Report({pupils,demo}:{pupils:Pupil[];demo:boolean}){
 const total=pupils.reduce((s,p)=>s+p.progress.totals.attempted,0),first=pupils.reduce((s,p)=>s+p.progress.totals.firstTry,0),legacy=pupils.some(p=>Object.keys(p.progress.skills).length>0);
 return <><div className="school-stats"><div><strong>{pupils.length}</strong><span>Pupils</span></div><div><strong>{total}</strong><span>Questions attempted</span></div><div><strong>{total?Math.round(first/total*100)+'%':'—'}</strong><span>First-attempt accuracy</span></div><div><strong>{pupils.filter(p=>p.progress.totals.attempted>0).length}</strong><span>Started practising</span></div></div><section className="school-panel"><div className="section-heading"><div><h2>{demo?'Sample practice evidence':'Class overview'}</h2><p className="muted">{demo?'Synthetic examples of guided arithmetic practice.':'Saved answers across the original guided lessons and P1–P6 activities.'}</p></div><button className="btn btn-soft" onClick={()=>downloadCsv(demo?'demo-class-report.csv':'class-report.csv',[['Name','Username','Questions','First-try correct','Hints','Sessions'],...pupils.map(p=>[p.name,p.username,p.progress.totals.attempted,p.progress.totals.firstTry,p.progress.totals.hints,p.progress.totals.sessions])])}>Export CSV</button></div>{legacy&&<><h3>Original guided arithmetic</h3><div className="table-scroll"><table className="school-table"><thead><tr><th>Pupil</th>{monitored.map(id=><th key={id}>{SKILLS[id]?.title||id}</th>)}<th>Questions</th></tr></thead><tbody>{pupils.map(p=><tr key={p.id}><th>{p.name}<small>{p.username}{!p.active?' · inactive':''}</small></th>{monitored.map(id=>{const s=p.progress.skills[id],band=masteryBand(s);return <td key={id}><span className={`heat ${band}`} title={s?`${s.attempts} attempts, ${s.firstTry} first-try correct, ${s.hints} hints; practice score ${Math.round(masteryScore(s)*100)}%.`:'No evidence yet'}>{BAND_LABEL[band]}</span></td>})}<td>{p.progress.totals.attempted}</td></tr>)}</tbody></table></div></>}{!pupils.length&&<p>No pupils in this class yet. Create an account or import a roster below.</p>}<p className="coverage-note">These are practice indicators, not curriculum certification. A pupil with no answers is “Not started”. P1–P6 activity evidence appears separately below.</p></section></>;
}
export function DemoSchoolScreen(){const [level,setLevel]=useState(1);const names=['Courage','Respect','Integrity','Harmony','Resilience','Excellence'];return <Page eyebrow="For teachers · Preview" title="A clearer view of learning."><p className="school-lead">Notice who is finding their feet, and who is ready for another challenge.</p><div className="demo-banner"><strong>Demo data · Merlion Primary School</strong><span>Read-only examples. Names and results are synthetic; no real pupil records.</span></div><div className="section-heading"><label>Class<select value={level} onChange={e=>setLevel(Number(e.target.value))}>{names.map((n,i)=><option key={n} value={i+1}>2026 · P{i+1} {n}</option>)}</select></label><p>Teacher: {level<=3?'Ms Tan':'Mr Lim'} · Common arithmetic practice</p></div><Report pupils={demoPupils(level)} demo/><section className="school-panel"><h2>Built for your school</h2><p>School accounts support classes, teacher permissions, pupil creation, roster import, PIN resets and learning saved across devices.</p><p>Diagnostics, assignments, exit tickets and full upper-primary lessons are later development phases.</p><a className="btn" href="#/account">Sign in to your school →</a></section></Page>}
export function SchoolScreen(){
 const {user,api}=useAccount();const [data,setData]=useState<any>(null),[classId,setClassId]=useState(''),[pupils,setPupils]=useState<Pupil[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[credentials,setCredentials]=useState<any[]>([]);
 async function refresh(){const d=await api('/school');setData(d);setClassId(c=>d.classes.some((x:any)=>x.id===c)?c:d.classes[0]?.id||'');}
 useEffect(()=>{if(user&&!user.mustChange&&user.role!=='student')void refresh().catch(e=>setMessage(e.message));},[api,user]);
 useEffect(()=>{let live=true;setPupils([]);if(classId)api(`/classes/${classId}/report`).then(r=>{if(live)setPupils(r.students)}).catch(e=>{if(live)setMessage(e.message)});return()=>{live=false}},[classId,api,data]);
 async function action(e:FormEvent<HTMLFormElement>,path:string,transform:(f:FormData)=>unknown,method='POST'){e.preventDefault();const form=e.currentTarget;setBusy(true);setMessage('');try{const b=transform(new FormData(form));const r=await api(path,method,b);if(r.credentials)setCredentials(r.credentials);setMessage('Saved successfully.');form.reset();await refresh();}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 if(!user||user.role==='student'||user.mustChange)return <Page eyebrow="School workspace" title="Staff sign-in required"><a className="btn" href="#/account">Open account →</a></Page>;
 const selected=data?.classes.find((c:any)=>c.id===classId);
 return <Page eyebrow={`${user.schoolName} · ${user.role==='admin'?'Administrator':'Teacher'}`} title="Your school, growing together."><p className="school-lead">Organise your classes and follow their progress, one idea at a time.</p><p className="muted">School code <strong>{user.schoolCode}</strong> · Curriculum {CURRICULUM.revision}</p>{message&&<p className="form-message" role="status">{message}</p>}{!data?<p>Loading school…</p>:<>{!data.classes.length&&<div className="school-note"><strong>Welcome! Let’s set up your first class.</strong><p>1. Create a class below. 2. Create teacher and pupil accounts, or import a pupil roster. 3. Give each person this school code, their username and temporary password. They choose a new password at first sign-in.</p><a href="#/school-start">View the setup guide →</a></div>}
 <div className="section-heading"><label>Academic year & class<select value={classId} onChange={e=>setClassId(e.target.value)}>{!data.classes.length&&<option value="">Create a class below</option>}{data.classes.map((c:any)=><option key={c.id} value={c.id}>{c.year} · P{c.level} {c.name} · {c.track}</option>)}</select></label><button className="btn btn-soft" disabled={busy} onClick={()=>void refresh().catch(e=>setMessage(e.message))}>Refresh</button></div><Report pupils={pupils} demo={false}/><PrimaryClassReport pupils={pupils}/>
 <div className="admin-grid">{user.role==='admin'&&<><section className="school-panel"><h2>Academic years</h2><p>{data.years.map((y:any)=>y.year).join(' · ')}</p><form className="school-form" onSubmit={e=>void action(e,'/years',f=>({year:Number(f.get('year'))}))}><label>New year<input name="year" type="number" min="2020" max="2100" defaultValue="2027" required/></label><button className="btn btn-soft" disabled={busy}>Add academic year</button></form></section><section className="school-panel"><h2>Create a class</h2><form className="school-form" onSubmit={e=>void action(e,'/classes',f=>({name:f.get('name'),yearId:f.get('yearId'),level:Number(f.get('level')),track:f.get('track')}))}><label>Year<select name="yearId">{data.years.map((y:any)=><option key={y.id} value={y.id}>{y.year}</option>)}</select></label><label>Primary level<select name="level">{[1,2,3,4,5,6].map(n=><option key={n} value={n}>P{n}</option>)}</select></label><label>Class name<input name="name" placeholder="Courage" required maxLength={60}/></label><label>Curriculum track<select name="track"><option value="standard">Standard / common</option><option value="foundation">Foundation (P5/P6)</option></select></label><button className="btn" disabled={busy}>Create class</button></form></section></>}
 <section className="school-panel"><h2>Create an account</h2><form className="school-form" onSubmit={e=>void action(e,'/users',f=>({name:f.get('name'),username:f.get('username'),password:f.get('password'),role:f.get('role'),classId:classId||undefined}))}><label>Role<select name="role"><option value="student">Student</option>{user.role==='admin'&&<><option value="teacher">Teacher</option><option value="admin">Administrator</option></>}</select></label><label>Name<input name="name" required maxLength={100}/></label><label>Username / staff email<input name="username" required autoCapitalize="none"/></label><label>Temporary password<input name="password" type="password" required minLength={8} autoComplete="new-password"/><small>Pupil: 8+ characters. Staff: 12+. A new password is required at first sign-in.</small></label><p className="muted">Assigned to {selected?`P${selected.level} ${selected.name}`:'no class'}. Give the school code, username and temporary password privately.</p><button className="btn" disabled={busy}>Create account</button></form></section>
 <section className="school-panel"><h2>Import class roster</h2><p>Paste up to 50 pupils for the selected class. The import is all-or-nothing; temporary passwords are generated once.</p><form className="school-form" onSubmit={e=>void action(e,'/import',f=>({classId,students:parseRoster(String(f.get('csv')),selected)}))}><label>CSV: student_id,name,level,class<textarea name="csv" rows={6} required placeholder={'student_id,name,level,class\n10001,Alice Tan,P1,Courage'}/></label><button className="btn" disabled={busy||!classId}>Import pupils</button></form>{credentials.length>0&&<div className="school-note"><strong>{credentials.length} accounts created</strong><p>Download the temporary sign-in details now. They are not shown again after leaving this page.</p><button className="btn btn-soft" onClick={()=>downloadCsv('private-student-logins.csv',[['School code','Username','Name','Temporary password'],...credentials.map(c=>[user.schoolCode,c.username,c.name,c.password])])}>Download private login sheet</button><button className="btn btn-soft" onClick={()=>setCredentials([])}>Dismiss</button></div>}</section>
 <section className="school-panel"><h2>Manage an account</h2><form className="school-form" onSubmit={e=>{const form=e.currentTarget;void action(e,`/users/${new FormData(form).get('userId')}`,f=>{const operation=f.get('operation');if(operation==='password')return {password:f.get('value')};if(operation==='class')return {classId};return {active:operation==='activate'}},'PATCH')}}><label>Account<select name="userId">{data.users.map((u:any)=><option key={u.id} value={u.id}>{u.name} · {u.role}{u.active?'':' · inactive'}</option>)}</select></label><label>Action<select name="operation"><option value="password">Reset temporary password</option>{user.role==='admin'&&<><option value="class">Assign / move to selected class</option><option value="deactivate">Deactivate account</option><option value="activate">Reactivate account</option></>}</select></label><label>New temporary password (for resets)<input name="value" type="password" autoComplete="new-password"/></label><p className="muted">Moving a pupil changes their class and preserves progress. A teacher can belong to more than one class. Resetting or deactivating revokes active sessions.</p><button className="btn btn-soft" disabled={busy||!data.users.length}>Apply change</button></form></section></div></>}</Page>;
}
export function parseRoster(text:string,selected:{level:number;name:string}|undefined){
 const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell.trim());cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}
 if(quoted)throw new Error('Unclosed quote in CSV.');row.push(cell.trim());if(row.some(Boolean))rows.push(row);const header=rows.shift()?.map(s=>s.replace(/^\uFEFF/,'').toLowerCase());if(!header?.includes('student_id')||!header.includes('name'))throw new Error('Include student_id and name columns.');
 return rows.map(r=>{const value=(key:string)=>r[header.indexOf(key)]||'';if(header.includes('level')&&value('level').replace(/^p/i,'')!==String(selected?.level))throw new Error('The CSV level must match the selected class.');if(header.includes('class')&&value('class')!==selected?.name)throw new Error('The CSV class must match the selected class.');return {student_id:value('student_id'),name:value('name')};});
}

export function SchoolStartScreen(){const {user}=useAccount();return <Page eyebrow="A simple start for your school" title="One workspace. Every learner."><p className="school-lead">An administrator sets up the school. Teachers manage their assigned classes. Pupils sign in and play at their primary level.</p><div className="account-grid"><section className="school-panel"><p className="school-eyebrow">I’m setting up a school</p><h2>Create your workspace</h2><p>No backend approval is needed. Create a private school workspace and receive a unique school code immediately.</p><a className="btn" href={user?.role==='admin'?'#/school':'#/register'}>{user?.role==='admin'?'Open my school':'Create a school workspace'} →</a></section><section className="school-panel"><p className="school-eyebrow">I’m a teacher or pupil</p><h2>Join your existing school</h2><p>Ask your school administrator or teacher for three things: <strong>school code, username and temporary password</strong>.</p><p>Sign in once, choose your own password, and you’re ready. Pupils do not need an email address.</p><a className="btn btn-soft" href="#/account">School sign in →</a></section></div><section className="school-panel"><h2>How school setup works</h2><ol className="setup-steps"><li><strong>Create the school workspace</strong><p>Enter your school name, your name, staff email and password. Your email is your sign-in username; the school code is generated for you.</p></li><li><strong>Add years and classes</strong><p>The current academic year is ready. Add P1–P6 classes and choose Standard or Foundation for P5/P6.</p></li><li><strong>Add teachers and pupils</strong><p>Create teacher accounts and assign their classes. Create pupils individually or import a CSV roster. Download generated temporary passwords after an import.</p></li><li><strong>Share sign-in details privately</strong><p>Give each person the website link, school code, username and their temporary password. The app does not send invitation emails. Teachers can reset passwords for pupils in their classes.</p></li></ol><p className="coverage-note">Each school workspace is separate. Creating a workspace does not grant access to an existing school’s records. Keep your administrator password safe; email-based password recovery is not available yet.</p></section><section className="school-panel"><h2>Just looking around?</h2><p>Try the games without an account, or view a clearly labelled, read-only sample dashboard. Sample records are not your school’s data.</p><div className="guide-links"><a href="#/">Try the P1–P6 games →</a><a href="#/demo">View sample dashboard →</a></div></section></Page>}
export function RegisterSchoolScreen(){const {user,register}=useAccount();const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMessage('');try{await register(String(f.get('schoolName')),String(f.get('name')),String(f.get('email')),String(f.get('password')));window.location.hash='#/school';}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 if(user)return <Page eyebrow="School workspace" title="You’re already signed in."><p>Use your existing school workspace, or sign out before creating a separate school.</p><a className="btn" href={user.role==='student'?'#/account':'#/school'}>Continue →</a></Page>;
 return <Page eyebrow="School administrator · Step 1" title="Let’s open your school workspace."><p className="school-lead">You’ll be the first administrator. Your school code and current academic year are created automatically.</p><div className="account-grid"><section className="school-panel"><form className="school-form" onSubmit={e=>void submit(e)}><label>School name<input name="schoolName" required maxLength={100} autoComplete="organization" placeholder="e.g. Merlion Primary School"/></label><label>Your name<input name="name" required maxLength={100} autoComplete="name"/></label><label>Your staff email<input name="email" type="email" required maxLength={100} autoComplete="email"/><small>This is your administrator username. No email is required for pupils.</small></label><label>Create your administrator password<input name="password" type="password" required minLength={12} autoComplete="new-password"/><small>At least 12 characters. Keep it safe; email recovery is not available yet.</small></label><button className="btn" disabled={busy}>{busy?'Creating your workspace…':'Create school workspace →'}</button></form>{message&&<p className="form-message" role="status">{message}</p>}</section><aside className="account-aside"><h2>What happens next?</h2><p>You’ll go directly to your school workspace. Create a class, add teachers, and create or import pupil accounts.</p><p>Only authorised staff can see that school’s pupil records. Teachers see the classes assigned to them.</p><a href="#/school-start">Read the setup guide →</a></aside></div></Page>;
}
