import type {Item,Lesson,RevealStep,Stage,Tool} from '../model';
import {annotateSteps} from '../build/teachingNotes';
import {questionModel} from '../tools/questionModel';

const bond=(whole:number,a:number,covered?:'a'|'b'):Tool=>({kind:'bond',whole,parts:[a,whole-a],locked:true,covered});
const groups=(count:number,size:number):Tool=>({kind:'groups',groups:count,size});
const wall=(d:number[],n:number[]):Tool=>({kind:'fractions',denominators:d,shaded:n});
const place=(a:number,b:number,c=0):Tool=>({kind:'place',digits:[a,b,c],wholes:0});
const grid=(shaded:number):Tool=>({kind:'hundred',shaded});
const percent=(whole:number,p:number):Tool=>({kind:'percent',whole,percent:p,step:10});
const balance=(x:number,n:number,total:number,value:number):Tool=>({kind:'balance',left:{x,n},right:{x:0,n:total},xValue:value});
const table=(rows:string[][]):Tool=>({kind:'table',headers:['Tenths','Hundredths'],rows,caption:'Keep tenths with tenths and hundredths with hundredths.'});
const frame=(text:string,tool:Tool,math?:string):RevealStep=>({text,tool,math});
const turn=(text:string,tool:Tool,prompt:string,answer:string,hint:string,wrong?:Record<string,string>):RevealStep=>({text,tool:questionModel(tool),ask:{prompt,answer,hint,wrong}});
const q=(key:string,prompt:string,answer:string,tool:Tool,hints:string[],check:string,wrong?:Record<string,string>):Item=>({key,prompt,answer,tool:questionModel(tool),hints,steps:[...hints,`So the answer is ${answer}.`],check,wrong,facet:'direct',another:[{title:'Explain the model',steps:hints,tool:questionModel(tool)}]});
interface Reference {
 goal:string;setup:string;prediction:string;options:[string,boolean,string][];
 explore:Extract<Stage,{kind:'explore'}>;frames:RevealStep[];
 worked:Extract<Stage,{kind:'worked'}>;practice:Item[];
 reflect:Omit<Extract<Stage,{kind:'reflect'}>,'kind'|'title'>;
}
const references:Record<string,Reference>={
 'p1s-as-03':{
  goal:'Use the same whole and two parts to explain adding and taking away.',
  setup:'Eight counters belong to one group. Five are blue and three are orange. How can this one picture show both adding and taking away?',
  prediction:'If we cover the three orange counters, do the five blue counters disappear too?',
  options:[['No. Five blue counters stay.',true,'Only the orange part is covered. The blue part stays.'],['Yes. All eight disappear.',false,'Covering one part leaves the other part where it is.']],
  explore:{kind:'explore',title:'Make the two parts',text:'Keep the same eight counters. They now start in two parts of four. Move one counter from the right part to the left part to make five on the left and three on the right.',tool:{kind:'bond',whole:8,parts:[4,4]},goal:t=>t.kind==='bond'&&t.whole===8&&t.parts[0]===5&&t.parts[1]===3,goalHint:'The whole stays eight. Make the left part five and the right part three.',success:'You changed where one counter belongs. You did not add or lose a counter: five and three still make eight.'},
  frames:[frame('Here are our eight counters in two parts. Trace the lines: both parts belong to the same whole.',bond(8,5),'5 + 3 = 8'),frame('Start with the whole eight. Imagine covering the orange part of three. The blue part of five stays.',bond(8,5,'b'),'8 − 3 = 5'),frame('Now uncover the orange part and cover the blue part instead. This time the orange three stay.',bond(8,5,'a'),'8 − 5 = 3'),frame('Addition joins the parts. Subtraction starts with the whole and finds the other part. We used the same eight counters each time.',bond(8,5),'5 + 3 = 8; 8 − 3 = 5; 8 − 5 = 3')],
  worked:{kind:'worked',title:'A different whole, the same connection',problem:'Nine counters have two parts: six and three. What is 9 − 6?',tool:bond(9,6),steps:[frame('The whole is now nine. Its parts are six and three. First find the whole and both parts in the picture.',bond(9,6)),turn('We take away the part of six. The question asks for the part that stays.',bond(9,6,'a'),'What is 9 − 6?','3','Find the other part of nine. Cover the six.',{'6':'Six is the part being taken away. Find the other part.','15':'That joins nine and six. Nine already includes the six.'}),frame('Three stays. Put the six back and the whole becomes nine again.',bond(9,6),'9 − 6 = 3; 3 + 6 = 9')]},
  practice:[q('bonds-same','Use the same whole of nine. What is 9 − 6?','3',bond(9,6),['The parts are six and three.','Take away six and name the other part.'],'3 + 6 rebuilds nine.'),q('bonds-switch','Keep the same whole and parts. Now what is 9 − 3?','6',bond(9,6),['This time the part of three leaves.','Find the part that stays.'],'6 + 3 rebuilds the same nine.'),q('bonds-change','Change the whole to ten. Three leave. How many stay?','7',bond(10,7),['The whole has grown by one.','Ten is made of three and another part.'],'7 + 3 = 10.')],
  reflect:{text:'Look back at our nine counters. Explain why knowing 6 + 3 = 9 also tells us 9 − 6.',tool:bond(9,6),prompts:['Point to the whole and both parts.','Which part leaves? Which part stays?','How can addition check the answer?'],explanation:['Nine is the whole. Six and three are its parts.','Taking away the six leaves three. No new counters are made.','Putting six back joins 3 + 6 and rebuilds nine.'],transfer:'If the whole grows to ten and we still take away six, would more or fewer stay? Explain before counting.'}
 },
 'p2s-md-02':{
  goal:'Explain how multiplication builds equal groups and division finds a missing group size or number of groups.',
  setup:'Three plates each hold four buns. There are twelve buns altogether. How can the plates help us connect multiplication and division?',
  prediction:'If we know there are twelve buns and three equal plates, what does 12 ÷ 3 find?',
  options:[['The buns on each plate.',true,'We know the number of plates. Sharing finds how many go on each.'],['The total number of buns.',false,'Twelve already tells us the total. Division finds one missing part of the grouping.']],
  explore:{kind:'explore',title:'Build the three plates',text:'The model starts with two plates of four. Keep four on each plate and add one more plate.',tool:groups(2,4),goal:t=>t.kind==='groups'&&t.groups===3&&t.size===4,goalHint:'Set the number of groups to three. Keep four in each group.',success:'Three equal plates of four make twelve. Now start with the twelve and think about undoing the grouping.'},
  frames:[frame('Count the four buns on each of our three plates. Equal groups let us add four three times.',groups(3,4),'4 + 4 + 4 = 12'),frame('Multiplication is a shorter way to record those equal groups: three groups of four.',groups(3,4),'3 × 4 = 12'),frame('Start with all twelve buns. Share them equally among three plates. There are four on each plate.',groups(3,4),'12 ÷ 3 = 4'),frame('Ask a different question about the same twelve: if each plate must hold four, how many plates do we need? Three.',groups(3,4),'12 ÷ 4 = 3')],
  worked:{kind:'worked',title:'Keep twelve, change the arrangement',problem:'Twelve buns are shared equally among four plates. How many buns go on each plate?',tool:groups(4,3),steps:[frame('Before, we had three plates of four. Now the same twelve buns are arranged on four plates.',groups(4,3)),turn('We know the total and the number of plates. Count the buns on one plate.',groups(4,3),'How many buns are on each plate?','3','Count one plate, not all four.',{'4':'Four counts the plates. We need the buns on each plate.','12':'Twelve counts all the buns. We need one equal share.'}),frame('Four equal shares of three rebuild twelve. That checks the division.',groups(4,3),'12 ÷ 4 = 3; 4 × 3 = 12')]},
  practice:[q('groups-total','Four plates each have three buns. How many buns altogether?','12',groups(4,3),['There are four equal groups.','Add three four times, or multiply.'],'4 × 3 = 12.'),q('groups-share','The same twelve buns are shared among four plates. How many on each?','3',groups(4,3),['The total is twelve and there are four plates.','Read one equal share.'],'4 × 3 makes the original twelve.'),q('groups-change','Now fifteen buns are put in groups of three. How many groups?','5',groups(5,3),['Keep three in each group.','Count how many groups make fifteen.'],'5 × 3 = 15.')],
  reflect:{text:'Explain the two different division questions we can ask about twelve buns.',tool:groups(3,4),prompts:['What do the three and four count?','What does 12 ÷ 3 find?','What does 12 ÷ 4 find?'],explanation:['Three counts the plates; four counts the buns on each plate.','12 ÷ 3 = 4 finds the size of one equal share.','12 ÷ 4 = 3 finds how many groups of four fit into twelve.'],transfer:'With twenty buns, would “share among five plates” and “put five on each plate” ask for the same thing? Name what each answer counts.'}
 },
 'p3s-frac-01':{
  goal:'Make an equivalent fraction by cutting every part equally, while keeping the whole and the chosen amount unchanged.',
  setup:'Half of a strip is coloured. We cut every half into two equal pieces. Did the coloured amount grow?',
  prediction:'After adding the cuts, what should stay the same?',
  options:[['The coloured length and the whole strip.',true,'Cuts change the pieces we count, not how much of the strip is coloured.'],['The number of pieces.',false,'Every old piece is cut into two. There will be more, smaller pieces.']],
  explore:{kind:'explore',title:'Match the same amount',text:'The top strip shows one half. The bottom is an equal-sized whole cut into quarters. Shade enough bottom pieces to reach the same point.',tool:wall([2,4],[1,0]),goal:t=>t.kind==='fractions'&&t.shaded[0]===1&&t.shaded[1]===2,goalHint:'Keep one half shaded on top. Shade two quarters on the bottom so the coloured lengths match.',success:'One half and two quarters cover the same length of equal-sized wholes. Their names differ, but their amount is equal.'},
  frames:[frame('Start with one of two equal parts coloured. The whole is the full strip, not just the coloured part.',wall([2],[1]),'1/2'),frame('Cut every half into two. The whole now has four parts; the coloured half now contains two.',wall([2,4],[1,2]),'1/2 = 2/4'),frame('We multiplied both counts by two: one coloured part became two, and two parts in the whole became four.',wall([2,4],[1,2]),'(1 × 2) / (2 × 2) = 2/4'),frame('Cut each original half into three instead. Three sixths still reaches the same point. More pieces does not mean more strip.',wall([2,6],[1,3]),'1/2 = 3/6')],
  worked:{kind:'worked',title:'Split thirds into sixths',problem:'Two thirds of a strip is coloured. Each third is cut into two equal pieces. How many sixths are coloured?',tool:wall([3,6],[2,4]),steps:[frame('This time two of three equal parts are coloured. Both strips show the same whole and the same coloured length.',wall([3,6],[2,4])),turn('Each coloured third becomes two sixths. Count the small coloured pieces.',wall([3,6],[2,4]),'How many sixths are coloured?','4','There are two coloured thirds. Split each into two.',{'2':'Two counts the old thirds. Each old third now contains two sixths.','3':'Adding one to both numbers does not describe cutting every part into two.'}),frame('Four of six parts are coloured. Both counts doubled because every part was cut the same way.',wall([3,6],[2,4]),'2/3 = 4/6')]},
  practice:[q('equiv-same','Fill the missing top number: 2/3 = ?/6.','4',wall([3,6],[2,4]),['Three parts became six: each part was split into two.','Apply the same split to both coloured parts.'],'4/6 covers the same amount as 2/3.'),q('equiv-split','Keep two thirds coloured. Cut each third into three instead. Fill: 2/3 = ?/9.','6',wall([3,9],[2,6]),['There are now three little pieces in each old part.','Two coloured old parts make two groups of three.'],'6/9 and 2/3 reach the same point.'),q('equiv-new','A new strip has three quarters coloured. Fill: 3/4 = ?/8.','6',wall([4,8],[3,6]),['Each quarter becomes two eighths.','Double the count of coloured pieces too.'],'6/8 and 3/4 name the same amount.')],
  reflect:{text:'Someone says 2/3 = 3/4 because they added one to both numbers. Use the strips to explain why cutting is different from adding one.',tool:wall([3,4],[2,3]),prompts:['Do the coloured lengths reach the same point?','When a part is cut in two, what happens to every other part?','Which fraction in sixths really equals 2/3?'],explanation:['The two equal-sized strips show different coloured lengths: 3/4 is more than 2/3.','Cutting every third in two doubles every part count. It does not add just one piece.','Both counts double, giving 4/6. The coloured amount stays two thirds.'],transfer:'Could 2/3 equal 8/12? Describe how every third would need to be cut.'}
 },
 'p4s-dec-01':{
  goal:'Explain why the same digit has different values in tenths, hundredths and thousandths.',
  setup:'One square is one whole. Four tenths of it is coloured. How is that different from four hundredths?',
  prediction:'Which covers more of the same whole: four tenths or four hundredths?',
  options:[['Four tenths.',true,'A tenth is a larger piece than a hundredth. We have four of either piece.'],['They are equal because both have a four.',false,'The digit counts pieces. The place tells us how large each piece is.']],
  explore:{kind:'explore',title:'Change the size of the pieces',text:'Start with four tenths: 0.4. Remove all four tenths, then add four hundredths instead. Keep the thousandths at zero. Watch what happens to the value.',tool:place(4,0,0),goal:t=>t.kind==='place'&&t.digits.join(',')==='0,4,0',goalHint:'Set tenths to zero, hundredths to four and thousandths to zero.',success:'The digit four now counts smaller pieces. Four hundredths is 0.04, one tenth of the amount you started with. The next pictures show why.'},
  frames:[frame('This full square is one whole. A row is one tenth. Four complete rows cover four tenths.',grid(40),'4/10 = 0.4'),frame('Each row contains ten small squares. One small square is one hundredth. Four small squares cover much less than four rows.',grid(4),'4/100 = 0.04'),frame('Imagine cutting each small square into ten equal pieces again. Four of those tiny pieces are four thousandths. The chart records their size with a different column.',place(0,0,4),'4/1000 = 0.004'),frame('Now put these three amounts together: four tenths, four hundredths and four thousandths. Each needs its own column because the units have different sizes.',place(4,4,4),'0.444 = 0.4 + 0.04 + 0.004')],
  worked:{kind:'worked',title:'Read a number with an empty place',problem:'In 0.306, what is the value of the digit 6?',tool:place(3,0,6),steps:[frame('The three is in tenths. The zero holds the hundredths place, so the six belongs in thousandths.',place(3,0,6)),turn('The question asks for the value, not the digit alone. Six copies of what size?',place(3,0,6),'What is the value of the digit 6 in 0.306?','0.006','The six counts thousandths: six parts out of one thousand.',{'6':'That names the digit. The place makes its value six thousandths.','0.06':'That is six hundredths. In this number the hundredths column contains zero.'}),frame('Six thousandths is 0.006. Without the middle zero, 0.36 would put the six in hundredths and change its value.',place(3,0,6),'0.306 = 0.3 + 0.006')]},
  practice:[q('decimal-tenths','In the same number 0.306, what is the value of the digit 3?','0.3',place(3,0,6),['The three is one place after the decimal point.','That column counts tenths.'],'Three tenths is 0.3.'),q('decimal-thousandths','In 0.306, what is the value of the digit 6?','0.006',place(3,0,6),['Count the places: tenths, hundredths, thousandths.','The six is in thousandths.'],'0.3 + 0.006 = 0.306.'),q('decimal-move','Now the number is 0.360. What is the value of the digit 6?','0.06',place(3,6,0),['Only the place of the six has changed.','Six now counts hundredths, which are ten times the size of thousandths.'],'0.06 is ten times 0.006.')],
  reflect:{text:'Explain why 0.306 and 0.360 are different, even though they use the same digits.',tool:place(3,0,6),prompts:['What unit does each digit count?','Why can we not remove the zero between three and six?','Which number has the larger value for six?'],explanation:['Both numbers have three tenths.','In 0.306 the six counts thousandths. The middle zero keeps the hundredths place empty.','In 0.360 the six counts hundredths. Six hundredths is larger than six thousandths.'],transfer:'If the six moved from hundredths to tenths, would its value grow or shrink? Explain using the sizes of the units.'}
 },
 'p4s-dec-05':{
  goal:'Add and subtract decimals by combining or exchanging equal-sized units.',
  setup:'A ribbon is 0.35 m long. We join another 0.27 m. How can hundredths help us find the new length?',
  prediction:'When joining these two ribbons, which units can we add directly?',
  options:[['Hundredths with hundredths, and tenths with tenths.',true,'We count together units of the same size. Ten hundredths can then be exchanged for one tenth.'],['Any digits that are at the end of a number.',false,'A last digit may count tenths or hundredths. Align the units, not the ends.']],
  explore:{kind:'explore',title:'Make the extra hundredths visible',text:'This square stands for one metre. Thirty-five hundredths are coloured. Extend the coloured part to show the length after adding twenty-seven more hundredths. Each full row is ten hundredths.',tool:grid(35),goal:t=>t.kind==='hundred'&&t.shaded===62,goalHint:'Show 62 small squares: six full rows and two extra squares.',success:'The coloured length grew from 35 hundredths to 62 hundredths. Ten small squares make one row, just as ten hundredths make one tenth.'},
  frames:[frame('Represent the first ribbon as 35 hundredths of one metre. Every little square stands for the same length: 0.01 m.',grid(35),'0.35 m = 35 hundredths of a metre'),frame('Add 27 more of those same units. We now have 62 hundredths, which fill six rows and two extra squares.',grid(62),'35 hundredths + 27 hundredths = 62 hundredths'),frame('In columns, five hundredths plus seven hundredths gives twelve hundredths. Exchange ten of them for one tenth. Keep two hundredths.',table([['3','5'],['+ 2','+ 7'],['5 + 1 exchanged','2']]),'0.35 + 0.27 = 0.62'),frame('Subtraction undoes the join. Take the added 27 hundredths away from 62. The original 35 hundredths remain.',grid(35),'0.62 − 0.27 = 0.35')],
  worked:{kind:'worked',title:'An exchange when taking away',problem:'A 0.62 m ribbon is shortened by 0.27 m. How much remains?',tool:place(6,2),steps:[frame('Start with six tenths and two hundredths. We need to take away two tenths and seven hundredths.',place(6,2)),turn('Two hundredths are not enough to remove seven. Exchange one tenth for ten hundredths. The amount stays 0.62.',table([['6','2'],['5','12']]),'After the exchange, how many hundredths are available?','12','One tenth is ten hundredths. Join those ten to the two already there.'),turn('Remove seven of the twelve hundredths, then two of the five tenths. Read what remains.',table([['5 − 2','12 − 7']]),'How many metres remain?','0.35','Five tenths minus two tenths leaves three tenths. Twelve hundredths minus seven leaves five hundredths.',{'0.45':'After the exchange there are five tenths, not six. One tenth became ten hundredths.'}),frame('The answer is 0.35 m. Join 0.27 m back on to check the original length.',grid(35),'0.35 + 0.27 = 0.62')]},
  practice:[q('decimal-add','Use the ribbon picture again. What is 0.35 + 0.27?','0.62',grid(62),['Both amounts can be counted in hundredths.','Add 35 and 27 hundredths.'],'62 hundredths is 0.62.'),q('decimal-one-more','Only the second ribbon changes: 0.28 instead of 0.27. What is 0.35 + 0.28?','0.63',grid(63),['We added one extra hundredth.','The total must be one hundredth more than 0.62.'],'0.63 − 0.28 = 0.35.'),q('decimal-sub','Undo the new join. What is 0.63 − 0.28?','0.35',grid(35),['The same three quantities belong together.','Take the added piece away to recover the first piece.'],'0.35 + 0.28 = 0.63.')],
  reflect:{text:'Explain why exchanging one tenth for ten hundredths does not change 0.62.',tool:table([['6','2'],['5','12']]),prompts:['How many hundredths is each row worth?','Why does the exchange help with subtracting 0.27?','How can addition check 0.62 − 0.27?'],explanation:['Six tenths and two hundredths is 60 + 2 hundredths. Five tenths and twelve hundredths is 50 + 12 hundredths. Both are 62.','Now we can remove seven hundredths from twelve, leaving five. Three tenths remain too.','0.35 + 0.27 = 0.62, so the subtraction has restored the original whole.'],transfer:'For 0.62 − 0.21, would an exchange be needed? Explain before calculating.'}
 },
 'p5s-pct-03':{
  goal:'Find a percentage by identifying the whole and building the requested share from equal parts.',
  setup:'A box holds 80 pencils. Thirty per cent are blue. Does 30% mean thirty pencils?',
  prediction:'If a whole changes from 100 pencils to 80, does 30% still mean thirty pencils?',
  options:[['No. The same fraction of a smaller whole is a smaller amount.',true,'Thirty per cent names a share of the whole. We must use the actual total of 80.'],['Yes. The number before % is always the number of objects.',false,'That works only when the whole contains exactly 100 objects.']],
  explore:{kind:'explore',title:'Build thirty per cent of eighty',text:'The whole bar stands for 80 pencils, split into ten equal sections. Shade three sections to show 30%.',tool:percent(80,0),goal:t=>t.kind==='percent'&&t.whole===80&&t.percent===30,goalHint:'Press +10% three times. Each section is one tenth of all 80 pencils.',success:'One tenth of 80 is eight. Three such sections hold 24 pencils. So 30% of 80 is 24, not 30.'},
  frames:[frame('The entire bar is all 80 pencils. Its ten equal sections each represent ten per cent of that whole.',percent(80,0),'100% = 80 pencils'),frame('Divide 80 into ten equal shares. One section, or ten per cent, contains eight pencils.',percent(80,10),'10% = 80 ÷ 10 = 8 pencils'),frame('Three sections represent thirty per cent. Three groups of eight contain twenty-four pencils.',percent(80,30),'30% = 3 × 8 = 24 pencils'),frame('The coloured part is less than half the bar. Twenty-four is less than half of eighty, so its size makes sense.',percent(80,30),'24 ÷ 80 = 0.30 = 30%')],
  worked:{kind:'worked',title:'Keep the share, change the whole',problem:'A different box has 60 pencils. Thirty per cent are blue. How many blue pencils are there?',tool:percent(60,30),steps:[frame('The share is still 30%, but the whole is now 60 pencils. Each equal section must be smaller.',percent(60,30)),turn('Start with one of the ten equal sections.',percent(60,10),'How many pencils is 10% of 60?','6','The whole bar is sixty. Divide it into ten equal groups.',{'10':'Ten is the percentage for one section, not its pencil count.'}),turn('Thirty per cent needs three sections, each containing six pencils.',percent(60,30),'How many pencils is 30% of 60?','18','Join three groups of six.',{'30':'Thirty names the percentage, not the number of pencils.','24':'Twenty-four belonged to the earlier whole of eighty. Our whole is now sixty.'}),frame('Eighteen pencils is 30% of sixty. The percentage stayed the same; the smaller whole made a smaller share.',percent(60,30),'60 ÷ 10 × 3 = 18')]},
  practice:[q('pct-same','In the same box of 60 pencils, how many is 30%?','18',percent(60,30),['Ten per cent is six pencils.','Three sections make thirty per cent.'],'18 ÷ 60 = 0.30.'),q('pct-share','Keep the whole at 60 pencils. Now how many is 40%?','24',percent(60,40),['Each ten-per-cent section still holds six.','This time use four sections.'],'24 is four tenths of sixty.'),q('pct-whole','Keep the share at 40%, but change the whole to 90 pencils. How many now?','36',percent(90,40),['The new ten-per-cent section holds nine.','Four sections now hold four groups of nine.'],'36 ÷ 90 = 0.40.')],
  reflect:{text:'Explain why 30% of 80 is different from 30% of 60.',tool:percent(80,30),prompts:['What does the whole bar stand for?','What does one section stand for?','What changed when the whole became sixty?'],explanation:['The whole bar represents the total number of pencils, not always one hundred pencils.','Each of ten equal sections is 10%: eight pencils when the total is eighty, but six when the total is sixty.','Thirty per cent uses three sections: 24 of eighty, or 18 of sixty.'],transfer:'If the whole doubled but the percentage stayed 30%, what would happen to the amount in the coloured part?'}
 },
 'p6s-alg-05':{
  goal:'Solve an equation by making equal changes to both sides, then check the unknown in the original equation.',
  setup:'Two identical mystery bags and three counters balance eleven counters. How many counters must be in each bag?',
  prediction:'If we remove three counters from just the left side, will the balance stay level?',
  options:[['No. We must remove the same amount from both sides.',true,'Equality means the two totals match. Changing one side alone breaks that match.'],['Yes. Removing counters always helps find the bag.',false,'It changes the relationship. We need to preserve the equality while uncovering the bag value.']],
  explore:{kind:'explore',title:'Keep the balance equal',text:'Each x is an identical bag. Take one counter off both sides three times. Then split both sides into two equal groups. If you try changing only the left, notice what happens and start again.',tool:balance(2,3,11,4),goal:t=>t.kind==='balance'&&t.left.x===1&&t.left.n===0&&t.right.x===0&&t.right.n===4,goalHint:'Remove three from BOTH sides before dividing BOTH sides by two.',success:'One bag balances four counters. Equal changes kept the relationship true: 2x + 3 = 11 became 2x = 8, then x = 4.'},
  frames:[frame('Two identical bags and three loose counters have the same total as eleven counters. The letter x stands for the unknown number in each bag.',balance(2,3,11,4),'2x + 3 = 11'),frame('Remove three loose counters from each side. Both totals shrink by three, so the scale remains level.',balance(2,0,8,4),'2x = 8'),frame('Share both sides into two equal groups. One bag has the same value as four counters.',balance(1,0,4,4),'x = 4'),frame('Check the starting situation, not just the final line. Two bags of four plus three loose counters make eleven.',balance(2,3,11,4),'2 × 4 + 3 = 11')],
  worked:{kind:'worked',title:'Try a new balanced equation',problem:'Solve 3x + 2 = 14.',tool:balance(3,2,14,4),steps:[turn('Three equal bags and two loose counters balance fourteen. First remove two from both sides.',balance(3,2,14,4),'What total remains on the right after subtracting two?','12','Fourteen minus two. The same two must also leave the left.'),turn('Three bags now balance twelve counters. Share the twelve equally among the three bags.',balance(3,0,12,4),'What is x?','4','The twelve belongs to three equal bags, not one.',{'12':'Twelve is the total for three bags. Divide that total into three equal shares.','16':'Adding two to fourteen does not undo the extra two on the left.'}),frame('Put four into the original equation. Three groups of four plus two is fourteen, so both sides match.',balance(3,2,14,4),'3 × 4 + 2 = 14')]},
  practice:[q('alg-same','Solve the same equation: 3x + 2 = 14.','4',balance(3,2,14,4),['Subtract two from both sides.','Divide both sides by three.'],'3 × 4 + 2 = 14.'),q('alg-total','Keep 3x + 2 on the left. Change the total to 17. What is x?','5',balance(3,2,17,5),['Subtract two from both sides to get three equal bags.','Share fifteen among the three bags.'],'3 × 5 + 2 = 17.'),q('alg-extra','Keep three bags and the total of seventeen. Now there are five loose counters instead of two. Solve 3x + 5 = 17.','4',balance(3,5,17,4),['Remove five from both sides.','Twelve belongs to three equal bags.'],'3 × 4 + 5 = 17.')],
  reflect:{text:'Explain why solving 2x + 3 = 11 needs changes on both sides.',tool:balance(2,3,11,4),prompts:['What does the equals sign tell us?','Why subtract three before dividing by two?','How do we check x = 4 in the original equation?'],explanation:['The equals sign says both sides have the same value. The two bags are identical.','Subtracting three from both sides leaves two bags equal to eight. Dividing both sides by two gives one bag equal to four.','Substituting four into 2x + 3 gives 2 × 4 + 3 = 11. The original equality is true.'],transfer:'Someone removes three only from the left. Use the scale to explain why that is not an equivalent equation.'}
 }
};
const practiceMistakes:Record<string,Record<string,string>>={
 'bonds-same':{'6':'Six is the part taken away. Name the other part that stays.','15':'Nine already includes the six. We are separating its parts, not adding six more.'},
 'bonds-switch':{'3':'Three is taken away this time. The other part stays.'},
 'bonds-change':{'3':'Three leave the group of ten. Count the counters that stay.','6':'The whole grew from nine to ten. Taking away the same three leaves one more.'},
 'groups-total':{'7':'Four counts the plates; three counts buns per plate. Add three four times, not four plus three.'},
 'groups-share':{'4':'Four counts the plates. We need the buns on one plate.','12':'Twelve is the total across all four plates.'},
 'groups-change':{'3':'Three is the size of each group. Count how many such groups make fifteen.'},
 'equiv-same':{'3':'Adding one to the top and bottom does not keep the amount. Each old part was split into TWO.','2':'Two counts the old thirds. Each coloured third now has two smaller pieces.'},
 'equiv-split':{'2':'Each of the two coloured thirds has been split into three. Count all those smaller pieces.','5':'We multiply each count by three; adding three does not describe equal cuts.'},
 'equiv-new':{'7':'Four parts became eight by doubling. Double the three coloured parts too; do not add four.'},
 'decimal-tenths':{'3':'Three is the digit. Its place makes the value three tenths.','0.03':'That is three hundredths. Here the three is in tenths.'},
 'decimal-thousandths':{'6':'Six is the digit. Its value is six thousandths.','0.06':'That names six hundredths. The six here is three places after the point.'},
 'decimal-move':{'0.006':'That was the value in 0.306. The six has moved to hundredths in 0.360.','6':'Name the value of the digit, not the digit alone.'},
 'decimal-add':{'0.52':'Twelve hundredths contains one extra tenth. Add that exchanged tenth to the five tenths.','0.512':'Twelve hundredths must be regrouped as one tenth and two hundredths, not written as extra decimal digits.'},
 'decimal-one-more':{'0.62':'The second ribbon is one hundredth longer now. Add that extra hundredth to the earlier total.'},
 'decimal-sub':{'0.45':'When one tenth becomes ten hundredths, only five tenths remain before subtracting the two tenths.'},
 'pct-same':{'30':'Thirty is the percentage. Each ten-per-cent section contains six pencils.','24':'Twenty-four belonged to the earlier total of eighty. The total here is sixty.'},
 'pct-share':{'40':'Forty is the percentage, not the pencil count. Each section holds six pencils.','18':'Eighteen was three sections. Forty per cent needs four sections.'},
 'pct-whole':{'24':'The whole changed from sixty to ninety, so each ten-per-cent section now holds nine.','40':'Forty names the share out of one hundred, not the amount out of ninety.'},
 'alg-same':{'12':'Twelve is the value of three bags. Share it equally among the three.'},
 'alg-total':{'15':'Fifteen is the value of three bags after removing two. Divide by three for one bag.','4':'Four solved the earlier total of fourteen. Check it in the new total of seventeen.'},
 'alg-extra':{'12':'Twelve belongs to three bags. Divide it into three equal shares.','5':'Five solved the previous equation. More of this same total is now loose counters, so less belongs to each bag.'}
};
export const REFERENCE_IDS=['p1s-as-07','p2s-frac-01','p5s-area-02',...Object.keys(references)];
/** Deliberate variation: the first practice reuses the worked situation; then one feature changes. */
export function referenceLesson(lesson:Lesson):Lesson{
 const r=references[lesson.id];if(!r)return lesson;
 const readiness=lesson.stages.find(s=>s.kind==='readiness')!;
 const lastAsk=r.worked.steps.map(s=>!!s.ask).lastIndexOf(true);
 const later=lesson.stages.filter(s=>s.kind==='practice'&&s.mode==='independent'||['apply','reason','mastery'].includes(s.kind));
 return {...lesson,mission:{goal:r.goal,question:r.worked.problem,pictureExample:r.setup,connection:'Predict, build a model, explain what changed, then use the relationship in a new situation.'},canDo:[r.goal,...lesson.canDo.slice(1)],stages:[
  readiness,
  {kind:'hook',title:'A question worth exploring',text:r.setup,tool:r.frames[0].tool,next:'First make a prediction. Then test the relationship with the model.'},
  {kind:'notice',title:'Predict before trying',text:r.prediction,tool:r.frames[0].tool,options:r.options.map(([text,correct,reply])=>({text,correct,reply})),flow:{phase:'watch',label:'Predict before changing the model',transition:'Use the starting situation to make a prediction. Next you will try an action and see whether your prediction fits.'}},
  r.explore,
  {kind:'explain',title:'Connect the action to the maths',text:r.frames[0].text,example:r.setup,frames:annotateSteps(r.frames)},
  {...r.worked,steps:annotateSteps(r.worked.steps.map((s,i)=>i===lastAsk&&s.ask?{...s,ask:{...s.ask,prompt:r.worked.problem}}:s)),flow:{phase:'together',label:'Change the example, keep the idea',transition:'Our first situation is complete. Read what stays the same and what changes in this next example.',carry:r.frames.at(-1)!.text}},
  {kind:'practice',mode:'guided',title:'One small change at a time',text:'Start with the example we just solved. Then notice the one change in each new question.',flow:{phase:'try',label:'Notice one change at a time',transition:'Start with the example we just solved. Then notice the one change in each new question.'},count:r.practice.length,gen:(_seed,i)=>{const item=r.practice[i%r.practice.length];return {...item,wrong:practiceMistakes[item.key]??item.wrong,simpler:readiness.kind==='readiness'?{...readiness.items[0],key:`support-${item.key}`,simpler:undefined}:undefined};}},
  {kind:'reflect',title:'Teach it back',...r.reflect},
  ...later,
  {kind:'discovery',title:'The connection to remember',text:`${r.worked.problem} ${r.worked.steps.at(-1)!.text}`,tool:r.worked.steps.at(-1)!.tool,math:r.worked.steps.at(-1)!.math,caption:r.goal}
 ]};
}
