import { sqliteTable, text, integer, primaryKey, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const schools = sqliteTable('schools', { id: text('id').primaryKey(), code: text('code').notNull().unique(), name: text('name').notNull(), demo: integer('demo').notNull().default(0), curriculumVersion: text('curriculum_version').notNull().default('moe-2021-oct2025') });
export const years = sqliteTable('years', { id: text('id').primaryKey(), schoolId: text('school_id').notNull().references(()=>schools.id), year: integer('year').notNull() }, t=>[uniqueIndex('school_year').on(t.schoolId,t.year)]);
export const classes = sqliteTable('classes', { id:text('id').primaryKey(), schoolId:text('school_id').notNull().references(()=>schools.id), yearId:text('year_id').notNull().references(()=>years.id), level:integer('level').notNull(), name:text('name').notNull(), track:text('track').notNull().default('standard') },t=>[uniqueIndex('class_name').on(t.yearId,t.level,t.name)]);
export const users = sqliteTable('users', { id:text('id').primaryKey(), schoolId:text('school_id').notNull().references(()=>schools.id), username:text('username').notNull(), name:text('name').notNull(), role:text('role').notNull(), passwordHash:text('password_hash').notNull(), active:integer('active').notNull().default(1), mustChange:integer('must_change').notNull().default(1), createdAt:integer('created_at').notNull() },t=>[uniqueIndex('school_username').on(t.schoolId,t.username)]);
export const memberships = sqliteTable('memberships', { userId:text('user_id').notNull().references(()=>users.id), classId:text('class_id').notNull().references(()=>classes.id) },t=>[primaryKey({columns:[t.userId,t.classId]})]);
export const sessions = sqliteTable('sessions', { hash:text('hash').primaryKey(), userId:text('user_id').notNull().references(()=>users.id), expiresAt:integer('expires_at').notNull() });
export const limits = sqliteTable('login_limits', { key:text('key').primaryKey(), count:integer('count').notNull(), until:integer('until').notNull() });
export const progress = sqliteTable('progress', { userId:text('user_id').primaryKey().references(()=>users.id), version:integer('version').notNull().default(0), data:text('data').notNull(), updatedAt:integer('updated_at').notNull() });
export const events = sqliteTable('events', { userId:text('user_id').notNull().references(()=>users.id), id:text('id').notNull(), data:text('data').notNull(), at:integer('at').notNull() },t=>[primaryKey({columns:[t.userId,t.id]})]);
export const audit = sqliteTable('audit', { id:text('id').primaryKey(), schoolId:text('school_id').notNull(), actor:text('actor').notNull(), action:text('action').notNull(), target:text('target').notNull(), at:integer('at').notNull() });
// Later assessment types use versioned payloads; they are not reported as implemented features.
export const learningRecords = sqliteTable('learning_records', { id:text('id').primaryKey(), userId:text('user_id').notNull().references(()=>users.id), kind:text('kind').notNull(), curriculumVersion:text('curriculum_version').notNull(), data:text('data').notNull(), at:integer('at').notNull() });
