import type { Track, Strand } from '../school/curriculum';
export type GameKind = 'count'|'place'|'compare'|'order'|'pattern'|'ordinal'|'add'|'subtract'|'bond'|'missing'|'groups'|'share'|'money'|'moneyChange'|'length'|'clock'|'duration'|'shape'|'shapePattern'|'pictureGraph'|'oddEven'|'multiply'|'divide'|'fractionShade'|'fractionCompare'|'fractionAdd'|'unitConvert'|'solid'|'remainder'|'fractionEquivalent'|'fractionSimplify'|'fractionSubtract'|'perimeter'|'area'|'angleType'|'parallel'|'barGraph'|'round'|'factor'|'multiple'|'mixedFraction'|'fractionSet'|'decimalPlace'|'decimalCompare'|'decimalRound'|'decimalAdd'|'decimalMultiply'|'symmetry'|'net'|'lineGraph'|'pieChart'|'operations'|'fractionMultiply'|'fractionDecimal'|'percent'|'discount'|'rate'|'triangleArea'|'volume'|'angleFacts'|'triangleAngle'|'quadrilateral'|'fractionDivide'|'reversePercent'|'percentChange'|'ratio'|'ratioShare'|'algebra'|'equation'|'circle'|'volumeMissing'|'average'|'story'|'decimalDivide';
export interface Activity { id:string; level:number; track:Track; strand:Strand; kind:GameKind; title:string; objective:string; skillIds:string[]; parameter?:string; icon:string }
const N:Strand='Number & Algebra',G:Strand='Measurement & Geometry',S:Strand='Statistics';
// Every row is a distinct, playable activity. References link to the versioned MOE map.
type Entry=[GameKind,string,string,string?];
const sets:Record<string,{strand:Strand;entries:Entry[]}[]>={
 '1S':[
 {strand:N,entries:[['count','Firefly forest','WN.01'],['place','Tens & ones workshop','WN.02'],['compare','Number crocodile','WN.04'],['order','Number train','WN.04'],['pattern','Stepping stones','WN.05'],['ordinal','Race-day positions','WN.06'],['add','Fruit basket','AS.01'],['subtract','Take-away picnic','AS.02'],['bond','Number-bond nests','AS.03'],['missing','Mystery boxes','AS.04'],['add','Number bridge to 100','AS.05','large'],['groups','Equal-group garden','MD.01'],['share','Sharing picnic','MD.02'],['money','Coin collector','MONEY.01'],['story','Story detectives','AS.01']]},
 {strand:G,entries:[['length','Ruler ranger','LENGTH.01'],['clock','Clock explorers','TIME.01'],['duration','Time travellers','TIME.03'],['shape','Shape safari','SHAPE.01'],['shapePattern','Picture-copy parade','SHAPE.03']]},
 {strand:S,entries:[['pictureGraph','Favourite-fruit fair','GRAPH.01']]}],
 '2S':[
 {strand:N,entries:[['place','Hundreds workshop','WN.02'],['compare','Number mountain','WN.04'],['order','Thousand-number train','WN.04'],['pattern','Pattern path','WN.05'],['oddEven','Odd & even arcade','WN.06'],['add','Addition architect','AS.01'],['subtract','Subtraction station','AS.01'],['multiply','Times-table trails','MD.01'],['divide','Division delivery','MD.02'],['groups','Array orchard','MD.01'],['share','Fair-share café','MD.02'],['fractionShade','Fraction bakery','FRAC.01'],['fractionCompare','Fraction seesaw','FRAC.03'],['fractionAdd','Slice builders','FRAC.05'],['money','Dollar detectives','MONEY.01'],['moneyChange','Money exchange','MONEY.03'],['story','Market mysteries','AS.01']]},
 {strand:G,entries:[['unitConvert','Measure match','MEASURE.04','choose'],['clock','Minute mission','TIME.01'],['duration','Hours & minutes','TIME.02'],['shapePattern','Pattern designers','SHAPE.01'],['solid','Solid safari','SHAPE.02']]},
 {strand:S,entries:[['pictureGraph','Pictograph park','GRAPH.01']]}],
 '3S':[
 {strand:N,entries:[['place','Ten-thousand tower','WN.01'],['compare','Number summit','WN.03'],['order','Place-value express','WN.03'],['add','Four-digit builders','AS.01'],['subtract','Difference detectives','AS.01'],['multiply','Table quest 6–9','MD.01','tables'],['multiply','Multiplication workshop','MD.03'],['divide','Division workshop','MD.04'],['remainder','Leftover lab','MD.02'],['fractionEquivalent','Equivalent-fraction bridge','FRAC.01'],['fractionSimplify','Simplify safari','FRAC.02'],['fractionCompare','Fraction balance','FRAC.03'],['fractionAdd','Fraction kitchen','FRAC.05'],['fractionSubtract','Slice rescue','FRAC.05'],['moneyChange','Canteen cashier','MONEY.01'],['story','Two-step detectives','AS.01']]},
 {strand:G,entries:[['unitConvert','Measurement express','MEASURE.03'],['clock','24-hour adventures','TIME.03'],['duration','Journey planner','TIME.02'],['area','Garden designer','AREA.03'],['perimeter','Fence builders','AREA.02'],['angleType','Right-angle hunt','ANGLE.01'],['parallel','Line explorers','LINES.01']]},
 {strand:S,entries:[['barGraph','Bar-chart detectives','GRAPH.01']]}],
 '4S':[
 {strand:N,entries:[['place','Hundred-thousand tower','WN.01'],['round','Rounding rocket','WN.02'],['factor','Factor finder','FACT.01'],['multiple','Common-multiple maze','FACT.03'],['multiply','Multiplication machine','MD.02'],['divide','Division expedition','MD.03'],['mixedFraction','Mixed-number bakery','FRAC.01'],['fractionSet','Fraction treasure','FRAC.03'],['fractionAdd','Fraction combinations','FRAC.04'],['fractionSubtract','Fraction differences','FRAC.04'],['decimalPlace','Decimal laboratory','DEC.01'],['decimalCompare','Decimal balance','DEC.02'],['fractionDecimal','Fraction-decimal bridge','DEC.03'],['decimalRound','Precision pilots','DEC.04'],['decimalAdd','Decimal builders','DEC.05'],['decimalMultiply','Decimal factory','DEC.06'],['decimalDivide','Decimal sharing','DEC.06'],['story','Problem-solving expedition','MD.02']]},
 {strand:G,entries:[['area','Composite gardens','AREA.02','composite'],['perimeter','Missing-length mission','AREA.01','missing'],['angleType','Protractor explorers','ANGLE.02','measure'],['shape','Shape property lab','SHAPE.01'],['symmetry','Mirror studio','SYM.01'],['solid','3D shape explorers','SOLID.01'],['net','Net detectives','SOLID.03']]},
 {strand:S,entries:[['lineGraph','Line-graph journeys','GRAPH.02'],['pieChart','Pie-chart party','GRAPH.03']]}],
 '5S':[
 {strand:N,entries:[['place','Ten-million city','WN.01'],['multiply','Powers-of-ten portal','WN.02','powers'],['operations','Operation codebreakers','WN.03'],['mixedFraction','Mixed-number workshop','FRAC.04','add'],['fractionMultiply','Fraction multiplication lab','FRAC.06'],['fractionSet','Fraction of a collection','FRAC.05'],['fractionDecimal','Fraction-decimal converter','FRAC.03'],['decimalMultiply','Decimal power station','DEC.01','powers'],['decimalDivide','Decimal division portal','DEC.01','powers'],['unitConvert','Decimal measurement lab','DEC.02'],['percent','Percentage mosaics','PCT.01'],['percent','Percentage treasure','PCT.03','quantity'],['discount','Sale-day detectives','PCT.04'],['rate','Rate racers','RATE.02'],['story','Multi-step market','FRAC.05']]},
 {strand:G,entries:[['triangleArea','Triangle gardens','AREA.02'],['area','Composite-area architects','AREA.03','triangle'],['volume','Cube builders','VOL.03'],['volume','Water-tank mission','VOL.04','liquid'],['angleFacts','Angle codebreakers','ANGLE.01'],['triangleAngle','Triangle detectives','SHAPE.01'],['quadrilateral','Quadrilateral quest','SHAPE.02']]},
 {strand:S,entries:[['lineGraph','Data expedition','GRAPH.02','review'],['pieChart','Data-circle challenge','GRAPH.03','review']]}],
 '6S':[
 {strand:N,entries:[['fractionDivide','Fraction division lab','FRAC.02'],['reversePercent','Original-price detectives','PCT.01'],['percentChange','Percentage-change challenge','PCT.02'],['ratio','Ratio recipe lab','RATIO.01'],['ratio','Equivalent-ratio bridge','RATIO.02','equivalent'],['ratioShare','Treasure in proportion','RATIO.03'],['algebra','Expression codebreakers','ALG.04'],['algebra','Simplify the machine','ALG.03','simplify'],['equation','Equation escape','ALG.05'],['story','Ratio story detectives','RATIO.03'],['story','Percentage story detectives','PCT.01','percent'],['fractionDivide','Whole-number fraction division','FRAC.01','whole'],['ratioShare','Three-way sharing','RATIO.03','three']]},
 {strand:G,entries:[['circle','Circle explorers','CIRCLE.01'],['circle','Circle-area architects','CIRCLE.01','area'],['circle','Half-circle gardens','CIRCLE.02','half'],['circle','Quarter-circle paths','CIRCLE.02','quarter'],['volumeMissing','Missing-dimension mission','VOL.01'],['volumeMissing','Base-area builders','VOL.02','base'],['quadrilateral','Composite-angle detectives','SHAPE.01'],['triangleArea','Triangle foundations','AREA.02','review']]},
 {strand:S,entries:[['average','Average detectives','AVG.01'],['average','Missing-total mission','AVG.02','total'],['average','Missing-data mystery','AVG.02','missing']]}],
 '5F':[
 {strand:N,entries:[['place','Big-number builders','WN.01'],['compare','Number-order trail','WN.02'],['round','Rounding rocket','WN.03'],['add','Addition workshop','AS.01'],['subtract','Subtraction workshop','AS.01'],['multiply','Table & product trail','MD.01'],['divide','Division delivery','MD.01'],['operations','Operation codebreakers','MD.03'],['factor','Factor finder','FACT.01'],['multiple','Multiple maze','FACT.02'],['fractionShade','Fraction bakery','FRAC.01'],['fractionEquivalent','Fraction bridges','FRAC.02'],['fractionSimplify','Simplify safari','FRAC.02'],['fractionCompare','Fraction balance','FRAC.03'],['mixedFraction','Mixed-number workshop','FRAC.04'],['fractionAdd','Fraction kitchen','FRAC.05'],['fractionSubtract','Slice rescue','FRAC.05'],['fractionMultiply','Fraction products','FRAC.08'],['decimalPlace','Decimal laboratory','DEC.01'],['decimalCompare','Decimal balance','DEC.02'],['decimalRound','Precision pilots','DEC.04'],['decimalAdd','Decimal builders','DEC.05'],['decimalMultiply','Powers-of-ten portal','DEC.06','powers'],['rate','Rate racers','RATE.02']]},
 {strand:G,entries:[['duration','Journey planner','TIME.02'],['area','Garden architects','AREA.01'],['perimeter','Fence builders','AREA.01'],['volume','Counting cube stacks','VOL.01','count'],['parallel','Line explorers','LINES.01'],['angleFacts','Angle facts','ANGLE.03'],['shape','Rectangle & square lab','SHAPE.01']]},
 {strand:S,entries:[['barGraph','Bar-chart detectives','GRAPH.02'],['lineGraph','Line-graph journeys','GRAPH.03']]}],
 '6F':[
 {strand:N,entries:[['fractionDecimal','Fraction-decimal bridge','FRAC.03'],['fractionDivide','Fraction division lab','FRAC.05'],['fractionDivide','Share a fraction','FRAC.04','whole'],['decimalMultiply','Decimal factory','DEC.01'],['decimalDivide','Decimal division','DEC.01'],['decimalRound','Precision pilots','DEC.03'],['percent','Percentage mosaics','PCT.01'],['percent','Percentage treasure','PCT.02','quantity'],['discount','Sale-day detectives','PCT.03'],['story','Discount story detectives','PCT.03','discount'],['story','Fraction story detectives','FRAC.04','fraction']]},
 {strand:G,entries:[['triangleArea','Triangle gardens','AREA.02'],['area','Composite gardens','AREA.03','triangle'],['perimeter','Composite fences','AREA.03','composite'],['volume','Cube builders','VOL.01'],['volume','Water-tank mission','VOL.02','liquid'],['unitConvert','Litres & cubes','VOL.03','volume'],['triangleAngle','Triangle detectives','SHAPE.02'],['shape','Shape property lab','SHAPE.01']]},
 {strand:S,entries:[['pieChart','Pie-chart party','GRAPH.01'],['average','Average detectives','AVG.01'],['average','Missing-total mission','AVG.01','total']]}],
};
export const ACTIVITIES:Activity[]=Object.entries(sets).flatMap(([key,sections])=>sections.flatMap(({strand,entries})=>entries.map(([kind,title,ref,parameter],i)=>{
 const level=Number(key[0]),track:Track=key[1]==='F'?'foundation':'standard';
 // P5 data and P6 triangle activities are explicitly marked prerequisite review.
 const prefix=parameter==='review'?(level===5?'P4.S':'P5.S'):`P${level}.${key[1]}`;
 return {id:`p${level}${key[1].toLowerCase()}-${kind}${parameter?'-'+parameter:''}-${strand===N?'n':strand===G?'g':'s'}${i}`,level,track,strand,kind,title,objective:ref,skillIds:[`${prefix}.${ref}`],parameter,icon:strand===N?'✦':strand===G?'◇':'▥'};
})));
export function activitiesFor(level:number,track:Track){return ACTIVITIES.filter(a=>a.level===level&&a.track===(level<5?'standard':track));}
export function activityById(id:string){return ACTIVITIES.find(a=>a.id===id);}
