import { Rng,hashString } from '../engine/random';
import type { Activity } from './catalog';
export type Picture = {type:'counters';count:number;group?:number}|{type:'fraction';parts:number;filled:number}|{type:'clock';minutes:number}|{type:'shape';shape:string;labels?:string[]}|{type:'bars';labels:string[];values:number[];scale:number;line?:boolean;pictures?:boolean}|{type:'pie';labels:string[];values:number[]}|{type:'angle';degrees:number;label?:string}|{type:'ruler';length:number}|{type:'net';cells:[number,number][]}|{type:'pattern';items:string[]}|{type:'solid';shape:string;a?:number;b?:number;c?:number}|{type:'area';a:number;b:number;cut?:number};
export interface Question {key:string;prompt:string;display?:string;answer:string;choices?:string[];unit?:string;hint:string;explanation:string;picture?:Picture;order?:string[];fractionBuilder?:number;proof?:Proof;requireSimplified?:boolean;requireImproper?:boolean}
export type Proof=number|{op:'+'|'-'|'*'|'/'|'round'|'floor';a:Proof;b:Proof};
const calc=(op:'+'|'-'|'*'|'/',a:Proof,b:Proof):Proof=>({op,a,b});
const fmt=(n:number)=>Number(n.toFixed(6)).toString();
const money=(n:number)=>'$'+n.toFixed(2);
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):a;
export function fraction(n:number,d:number){const g=gcd(n,d);return d/g===1?String(n/g):`${n/g}/${d/g}`;}
export function numberValue(s:string):number|null{const t=s.trim().replaceAll(',','').replace(/\s+/g,' ');if(/^-?\d+(\.\d+)?$/.test(t))return Number(t);if(/^-?\d+\/\d+$/.test(t)){const [n,d]=t.split('/').map(Number);return d?n/d:null;}if(/^\d+ \d+\/\d+$/.test(t)){const [whole,part]=t.split(' ');return Number(whole)+(numberValue(part)??NaN);}return null;}
export function correctAnswer(q:Question,input:string){if(q.order)return input===q.answer;if(q.requireSimplified&&input.includes('/')){const parts=input.split('/').map(Number);if(parts.length!==2||gcd(parts[0],parts[1])!==1)return false;}if(q.requireImproper&&input.trim().includes(' '))return false;const a=numberValue(q.answer),b=numberValue(input);return a!==null&&b!==null?Math.abs(a-b)<1e-7:input.trim().toLowerCase()===q.answer.trim().toLowerCase();}
const time=(minutes:number,clock24=false)=>{const h=Math.floor(minutes/60)%24,m=minutes%60;return clock24?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`:`${h%12||12}:${String(m).padStart(2,'0')}`;};
export function makeQuestion(activity:Activity,seed:number,index=0):Question{
 const r=new Rng(hashString(`${activity.id}:${seed}:${index}`)),g=activity.level,f=activity.track==='foundation',p=activity.parameter;
 const max=[0,100,1000,10000,100000,10000000,10000000][g];
 const choose=(answer:string,wrong:string[])=>r.shuffle([...new Set([answer,...wrong.filter(v=>v!==answer)])].slice(0,4));
 const base={key:`${activity.id}:${seed}:${index}`};
 const numeric=(prompt:string,answer:number,hint:string,explanation:string,extra:Partial<Question>={}):Question=>({...base,prompt,answer:fmt(answer),hint,explanation,...extra});
 const choice=(prompt:string,answer:string,wrong:string[],hint:string,explanation:string,extra:Partial<Question>={}):Question=>({...base,prompt,answer,choices:choose(answer,wrong),hint,explanation,...extra});
 const rational=(prompt:string,n:number,d:number,hint:string,explanation:string,extra:Partial<Question>={})=>({...base,prompt,answer:fraction(n,d),hint,explanation,...extra});
 const table=()=>r.pick(g===1?[2,3,4]:g===2?[2,3,4,5,10]:[2,3,4,5,6,7,8,9,10]);
 const barQuestion=(line=false,pictures=false)=>{const labels=line?['Mon','Tue','Wed','Thu']:['Mango','Apple','Pear','Orange'],scale=g===1?1:r.pick([2,5,10]),values=labels.map(()=>r.int(1,6)*scale),k=r.int(0,3);const mode=r.int(0,2);const a=mode===0?values[k]:mode===1?values.reduce((a,b)=>a+b,0):Math.max(...values)-Math.min(...values);const prompt=mode===0?`How many ${line?'books were read on '+labels[k]:labels[k].toLowerCase()+' votes are there'}?`:mode===1?'How many are there altogether?':'How many more is the greatest value than the smallest value?';return numeric(prompt,a,mode===1?'Add all four values.':mode===2?'Find the highest and lowest values, then subtract.':`Check the scale: each ${pictures?'symbol':'step'} represents ${scale}.`,mode===1?`${values.join(' + ')} = ${a}.`:mode===2?`${Math.max(...values)} − ${Math.min(...values)} = ${a}.`:`${labels[k]} has ${values[k]}.`,{picture:{type:'bars',labels,values,scale,line,pictures},proof:mode===0?values[k]:mode===1?values.reduce<Proof>((a,b)=>calc('+',a,b),0):calc('-',Math.max(...values),Math.min(...values))});};
 switch(activity.kind){
 case 'count':{const a=r.int(3,20);return numeric('How many fireflies are in the forest?',a,'Count each firefly once. Try making a group of ten.',`There are ${a} fireflies.`,{picture:{type:'counters',count:a},proof:a});}
 case 'place':{const n=r.int(g===1?12:Math.floor(max/10),max-1),places=g===1?[10,1]:g===2?[100,10,1]:g===3?[1000,100,10,1]:g===4?[10000,1000,100,10,1]:[1000000,100000,10000,1000,100],place=r.pick(places),digit=Math.floor(n/place)%10;return numeric(`What is the value of the digit in the ${place.toLocaleString('en-SG')} place?`,digit*place,'A digit’s value is the digit multiplied by its place value.',`${digit} × ${place.toLocaleString('en-SG')} = ${(digit*place).toLocaleString('en-SG')}.`,{display:n.toLocaleString('en-SG'),proof:calc('*',digit,place)});}
 case 'compare':{const cap=f?100000:max,a=r.int(1,cap),b=r.chance(.15)?a:r.int(1,cap),ans=a>b?'>':a<b?'<':'=';return choice('Choose the sign that makes this true.',ans,['<','>','='],'Compare the greatest place value first.',`${a.toLocaleString('en-SG')} ${ans} ${b.toLocaleString('en-SG')}.`,{display:`${a.toLocaleString('en-SG')}  □  ${b.toLocaleString('en-SG')}`});}
 case 'order':{const values=[...new Set(Array.from({length:12},()=>r.int(1,max)))].slice(0,4).sort((a,b)=>a-b);return {...base,prompt:'Build the train from smallest to greatest.',answer:values.join(','),order:r.shuffle(values.map(String)),hint:'Find the smallest number first. Compare place values.',explanation:`${values.join(' < ')}.`};}
 case 'pattern':{const step=r.pick(g===1?[1,2,5,10]:[2,3,5,10,20,100]),start=r.int(1,g===1?Math.max(1,99-step*4):500),values=[0,1,2,3].map(i=>start+step*i);return numeric('What comes next on the stepping stones?',start+4*step,`Compare neighbouring numbers. What is added each time?`,`Add ${step} each time. ${values[3]} + ${step} = ${start+4*step}.`,{display:`${values.join('  →  ')}  →  ?`,proof:calc('+',start,calc('*',4,step))});}
 case 'ordinal':{const names=['first','second','third','fourth','fifth','sixth','seventh','eighth','ninth','tenth'],n=r.int(1,10),suffix=n===1?'st':n===2?'nd':n===3?'rd':'th';return choice(`Which position means “${names[n-1]}”?`,`${n}${suffix}`,r.shuffle(names.map((_,i)=>`${i+1}${i===0?'st':i===1?'nd':i===2?'rd':'th'}`)),'Positions start with first, then second, then third.',`${names[n-1]} is written ${n}${suffix}.`,{picture:{type:'counters',count:10}});}
 case 'add':case 'subtract':{const cap=g===1?(p==='large'?100:20):g===2||f?999:9999,total=r.int(4,cap),a=r.int(1,total-1),b=total-a,sub=activity.kind==='subtract';return numeric(sub?'Find the difference.':'How many altogether?',sub?b:total,sub?'Subtract ones, then tens. Regroup if you need to.':'Add ones, then tens. Regroup when you make a new ten.',sub?`${total} − ${a} = ${b}. Check: ${a} + ${b} = ${total}.`:`${a} + ${b} = ${total}.`,{display:sub?`${total} − ${a} = ?`:`${a} + ${b} = ?`,proof:sub?calc('-',total,a):calc('+',a,b),...(g===1&&total<=20?{picture:{type:'counters' as const,count:total}}:{})});}
 case 'bond':case 'missing':{const total=r.int(4,20),a=r.int(1,total-1),b=total-a;return numeric('Find the missing part.',b,'The two parts make the whole. Subtract the known part from the whole.',`${total} − ${a} = ${b}, so ${a} + ${b} = ${total}.`,{display:`${a} + □ = ${total}`,proof:calc('-',total,a)});}
 case 'groups':{const groups=g===1?r.int(2,5):table(),size=r.int(2,g===1?Math.min(8,Math.floor(40/groups)):6);return numeric(`There are ${groups} equal groups. How many objects altogether?`,groups*size,'Count one group, then add the same amount for each group.',`${groups} groups of ${size}: ${groups} × ${size} = ${groups*size}.`,{picture:{type:'counters',count:groups*size,group:size},proof:calc('*',groups,size)});}
 case 'share':{const groups=r.int(2,5),each=r.int(1,g===1?Math.floor(20/groups):5),total=groups*each;return numeric(`Share ${total} strawberries equally among ${groups} friends. How many does each get?`,each,`Make ${groups} equal groups.`,`${total} ÷ ${groups} = ${each}. Each friend gets ${each}.`,{picture:{type:'counters',count:total},proof:calc('/',total,groups)});}
 case 'multiply':{let a=table(),b=r.int(2,10);if(p==='tables')a=r.pick([6,7,8,9]);else if(p==='powers'){a=r.int(12,999);b=r.pick([10,100,1000]);}else if(g===3){a=r.int(101,999);b=r.int(2,9);}else if(g===4){a=r.int(101,999);b=r.int(11,99);}else if(f){a=r.int(11,99);b=r.int(2,9);}return numeric('Find the product.',a*b,'Split a number by place value. Multiply each part, then add.',`${a} × ${b} = ${a*b}.`,{display:`${a} × ${b} = ?`,proof:calc('*',a,b)});}
 case 'divide':{const b=table(),quotient=r.int(2,g===2?10:f?Math.floor(99/b):g===3?Math.floor(999/b):Math.floor(9999/b)),a=b*quotient;return numeric('Divide into equal groups.',quotient,`What number multiplied by ${b} gives ${a}?`,`${a} ÷ ${b} = ${quotient}, because ${quotient} × ${b} = ${a}.`,{display:`${a} ÷ ${b} = ?`,proof:calc('/',a,b)});}
 case 'remainder':{const b=r.int(3,9),q=r.int(3,30),rem=r.int(1,b-1),a=b*q+rem;return numeric(`What is the remainder when ${a} is divided by ${b}?`,rem,'Find the greatest multiple of the divisor that fits. The leftover is the remainder.',`${b} × ${q} = ${b*q}. ${a} − ${b*q} = ${rem}, which is smaller than ${b}.`,{display:`${a} ÷ ${b}`,proof:calc('-',a,calc('*',b,q))});}
 case 'oddEven':{const a=r.int(1,999),ans=a%2?'Odd':'Even';return choice(`Is ${a} odd or even?`,ans,['Odd','Even'],'Look at the ones digit. Even numbers end in 0, 2, 4, 6 or 8.',`${a} is ${ans.toLowerCase()}. ${a%2?'One is left over when making pairs.':'It can be grouped into pairs.'}`);}
 case 'money':{if(g===1){const coins=r.shuffle([5,10,20,50]).slice(0,3),sum=coins.reduce((a,b)=>a+b,0);return numeric('How many cents are these coins worth?',sum,'Add the value of each coin.',`${coins.join(' + ')} = ${sum} cents.`,{picture:{type:'pattern',items:coins.map(c=>c+'¢')},unit:'cents',proof:coins.reduce<Proof>((a,b)=>calc('+',a,b),0)});}const cents=r.int(100,9999);return numeric(`Write ${cents} cents in dollars.`,cents/100,'100 cents make one dollar.',`${cents} ÷ 100 = ${money(cents/100)}.`,{unit:'dollars',proof:calc('/',cents,100)});}
 case 'moneyChange':{if(g===2){const d=r.int(1,20),c=r.int(1,99);return numeric(`How many cents are there in ${money(d+c/100)}?`,d*100+c,`Each dollar is 100 cents.`,`${d} × 100 + ${c} = ${d*100+c} cents.`,{unit:'cents',proof:calc('+',calc('*',d,100),c)});}const cost=r.int(125,875),paid=1000;return numeric(`Aisha pays $10.00 for a book costing ${money(cost/100)}. How much change?`,(paid-cost)/100,'Subtract the cost from the amount paid.',`$10.00 − ${money(cost/100)} = ${money((paid-cost)/100)}.`,{unit:'dollars',proof:calc('/',calc('-',paid,cost),100)});}
 case 'length':{const n=r.int(2,12);return numeric('How long is the blue ribbon?',n,'The ribbon starts at zero. Read the number where it ends.',`The ribbon reaches ${n} cm. Its length is ${n} cm.`,{picture:{type:'ruler',length:n},unit:'cm',proof:n});}
 case 'clock':{const minute=r.int(0,g===1?11:59)*(g===1?5:1),h=r.int(1,g>=3?23:12),t=h*60+minute,ans=time(t,g>=3);return choice(g>=3?'It is after midday. Choose this time using the 24-hour clock.':'What time does this clock show?',g>=3?time((h%12+12)*60+minute,true):ans,[-60,5,60].map(delta=>time((g>=3?(h%12+12)*60+minute:t)+delta,g>=3)),'The short hand shows the hour. Each large step of the minute hand is five minutes.',g>=3?`After midday, add 12 to the hour (except 12 noon). The time is ${time((h%12+12)*60+minute,true)}.`:`The hour is ${h%12||12} and the minute is ${minute}. It is ${ans}.`,{picture:{type:'clock',minutes:t}});}
 case 'duration':{if(g===1){const start=r.int(1,10)*60,add=r.pick([30,60]),ans=time(start+add);return choice(`A game starts at ${time(start)}. It lasts ${add===30?'half an hour':'one hour'}. When does it finish?`,ans,[time(start+15),time(start+90),time(start)],'Half an hour is 30 minutes. One hour is 60 minutes.',`${time(start)} plus ${add} minutes is ${ans}.`,{picture:{type:'clock',minutes:start}});}if(g===2){const hours=r.int(1,5),mins=r.int(0,5)*10;return numeric(`How many minutes are ${hours} h ${mins} min?`,hours*60+mins,'Each hour is 60 minutes.',`${hours} × 60 + ${mins} = ${hours*60+mins} minutes.`,{unit:'minutes',proof:calc('+',calc('*',hours,60),mins)});}const start=r.int(7,15)*60+r.int(0,11)*5,duration=r.int(3,30)*5;return numeric(`A trip starts at ${time(start,true)} and ends at ${time(start+duration,true)}. How long is the trip?`,duration,'Count to the next whole hour, then count the remaining minutes.',`The difference between ${time(start,true)} and ${time(start+duration,true)} is ${duration} minutes.`,{unit:'minutes',proof:calc('-',start+duration,start)});}
 case 'shape':{const basic=['circle','triangle','square','rectangle'];const shape=r.pick(basic);if(g===1)return choice('What is the name of this shape?',shape,basic,'Look for straight sides and corners.',shape==='circle'?'A circle has a curved boundary and no corners.':`This is a ${shape}.`,{picture:{type:'shape',shape}});const shapes=['square','rectangle','triangle'],s=r.pick(shapes);const question=s==='square'?'Which shape must have four equal sides and four right angles?':s==='rectangle'?'Which name describes a four-sided shape with four right angles, with opposite sides equal?':'Which shape has three straight sides?';return choice(question,s,shapes,'Check every property in the description.',`A ${s} has these properties.`,{...(s==='rectangle'?{choices:r.shuffle(['rectangle','triangle','circle'])}:{})});}
 case 'shapePattern':{if(g===1){const shapes=['●','▲','■'],items=Array.from({length:3},()=>r.pick(shapes)),ans=items.join(' ');return choice('Which row copies the picture exactly?',ans,[...Array.from({length:8},()=>Array.from({length:3},()=>r.pick(shapes)).join(' '))],'Look at each shape from left to right.',`The matching row is ${ans}.`,{picture:{type:'pattern',items}});}const cycle=r.pick([['●','▲'],['■','●','▲'],['▲','▲','●']]),start=r.int(0,2),items=Array.from({length:5},(_,i)=>cycle[(start+i)%cycle.length]),answer=cycle[(start+5)%cycle.length];return choice('Which shape comes next?',answer,['●','▲','■'],'Find the repeating group. Then continue the same order.',`The repeating unit is ${cycle.join(' ')}. The next shape is ${answer}.`,{picture:{type:'pattern',items:[...items,'?']}});}
 case 'fractionShade':{const parts=r.pick([2,3,4,5,6,8,10,12]),filled=r.int(1,parts-1);return {...base,prompt:`Shade ${filled}/${parts} of the tray. Tap the equal parts.`,answer:`${filled}/${parts}`,fractionBuilder:parts,hint:`The denominator ${parts} is the number of equal parts. Shade ${filled} of them.`,explanation:`${filled} out of ${parts} equal parts is ${fraction(filled,parts)}.`,proof:calc('/',filled,parts)};}
 case 'fractionCompare':{const d=g===2?r.pick([3,4,5,6,8,10,12]):r.pick([4,6,8,10,12]);let n1=r.int(1,d-1),d1=d,n2=r.int(1,d-1),d2=d;if(g===2&&r.chance(.5)){n1=1;n2=1;d1=r.int(2,12);d2=r.int(2,12);}else if(g>=3){d1=r.pick([2,3,4,6,8,12]);n1=r.int(1,d1-1);}const v1=n1/d1,v2=n2/d2,ans=v1>v2?'>':v1<v2?'<':'=';return choice('Compare these fractions.',ans,['<','>','='],'Use equal-sized wholes. Make equivalent fractions with the same denominator.',`${n1}/${d1} = ${n1*d2}/${d1*d2} and ${n2}/${d2} = ${n2*d1}/${d1*d2}, so use ${ans}.`,{display:`${n1}/${d1}  □  ${n2}/${d2}`});}
 case 'fractionAdd':case 'fractionSubtract':{const d=r.pick([4,6,8,10,12]),factor=g===2?1:r.pick([1,2]),d1=d/factor,n1=r.int(1,Math.max(1,d1-1)),n2=r.int(1,Math.max(1,d-n1*factor));const sub=activity.kind==='fractionSubtract';const a=sub?Math.max(n1*factor,n2):n1*factor,b=sub?Math.min(n1*factor,n2):n2;return rational(sub?'Find the difference.':'Combine the fractions.',sub?a-b:a+b,d,'Use a common denominator. Add or subtract the numerators; keep the denominator.',`${a}/${d} ${sub?'−':'+'} ${b}/${d} = ${fraction(sub?a-b:a+b,d)}.`,{display:sub?`${fraction(a,d)} − ${fraction(b,d)} = ?`:`${n1}/${d1} + ${n2}/${d} = ?`,proof:calc(sub?'-':'+',calc('/',a,d),calc('/',b,d))});}
 case 'fractionEquivalent':{const d=r.int(2,6),n=r.int(1,d-1),k=r.int(2,4);return numeric('Find the missing numerator.',n*k,`The denominator was multiplied by ${k}. Do the same to the numerator.`,`${n} × ${k} = ${n*k}. Both parts of the fraction use the same multiplier.`,{display:`${n}/${d} = □/${d*k}`,proof:calc('*',n,k)});}
 case 'fractionSimplify':{const d=r.int(2,6),n=r.int(1,d-1),k=r.int(2,4);return rational('Write this fraction in simplest form.',n,d,'Divide numerator and denominator by their greatest common factor.',`${n*k}/${d*k} simplifies to ${fraction(n,d)}.`,{display:`${n*k}/${d*k}`,requireSimplified:true,proof:calc('/',n*k,d*k)});}
 case 'mixedFraction':{const d=r.int(2,8),whole=r.int(1,4),n=r.int(1,d-1);if(p==='add'){const w2=r.int(1,3),n2=r.int(1,d-1),num=(whole+w2)*d+n+n2;return rational('Add the mixed numbers. Give a fraction or mixed number.',num,d,'Add the whole parts and fraction parts. Regroup any whole made by the fractions.',`${whole} + ${w2} + ${n}/${d} + ${n2}/${d} = ${fraction(num,d)}.`,{display:`${whole} ${n}/${d} + ${w2} ${n2}/${d}`,proof:calc('+',calc('+',whole,w2),calc('/',n+n2,d))});}return rational('Write this mixed number as an improper fraction.',whole*d+n,d,'Multiply the whole number by the denominator, then add the numerator.',`(${whole} × ${d} + ${n})/${d} = ${fraction(whole*d+n,d)}.`,{display:`${whole} ${n}/${d}`,requireImproper:true,proof:calc('+',whole,calc('/',n,d))});}
 case 'fractionSet':{const d=r.int(2,10),n=r.int(1,d-1),each=r.int(2,12),total=d*each;return numeric(`There are ${total} beads. ${n}/${d} of them are blue. How many are blue?`,n*each,'Find one equal part by dividing by the denominator, then multiply by the numerator.',`${total} ÷ ${d} × ${n} = ${n*each}.`,{proof:calc('*',calc('/',total,d),n)});}
 case 'fractionMultiply':{const d1=r.int(2,9),n1=r.int(1,d1-1),d2=r.int(2,9),n2=r.int(1,(f?1:2)*d2-1);return rational('Multiply the fractions.',n1*n2,d1*d2,'Multiply the numerators together and the denominators together. Simplify.',`${n1}/${d1} × ${n2}/${d2} = ${n1*n2}/${d1*d2} = ${fraction(n1*n2,d1*d2)}.`,{display:`${n1}/${d1} × ${n2}/${d2}`,proof:calc('*',calc('/',n1,d1),calc('/',n2,d2))});}
 case 'fractionDivide':{const d1=r.int(2,9),n1=r.int(1,d1-1),d2=r.int(2,9),n2=r.int(1,d2-1);if(p==='whole'){const k=r.int(2,7);return rational('Share this fraction equally.',n1,d1*k,'Dividing by a whole number makes each share smaller. Multiply the denominator by the number of shares.',`${n1}/${d1} ÷ ${k} = ${fraction(n1,d1*k)}.`,{display:`${n1}/${d1} ÷ ${k}`,proof:calc('/',calc('/',n1,d1),k)});}return rational('How many groups of the second fraction fit into the first?',n1*d2,d1*n2,'Divide by a fraction by multiplying by its reciprocal.',`${n1}/${d1} × ${d2}/${n2} = ${fraction(n1*d2,d1*n2)}.`,{display:`${n1}/${d1} ÷ ${n2}/${d2}`,proof:calc('/',calc('/',n1,d1),calc('/',n2,d2))});}
 case 'fractionDecimal':{const d=r.pick(g===4||f?[2,4,5,10,20,25,50,100]:[2,4,5,8,10,20,25,50,100]),n=r.int(1,d-1);return numeric('Write this fraction as a decimal.',n/d,'Divide the numerator by the denominator, or make an equivalent fraction with denominator 10, 100 or 1000.',`${n} ÷ ${d} = ${fmt(n/d)}.`,{display:`${n}/${d}`,proof:calc('/',n,d)});}
 case 'unitConvert':{if(p==='choose'){const pairs=[['length of a pencil','cm'],['length of a swimming pool','m'],['mass of a school bag','kg'],['mass of a paper clip','g'],['volume of a bucket of water','litres']],pair=r.pick(pairs);return choice(`Choose a suitable unit for the ${pair[0]}.`,pair[1],r.shuffle(['cm','m','kg','g','litres']),'Think about what is being measured and how large it is.',`Use ${pair[1]} for the ${pair[0]}.`);}const units:readonly (readonly [string,string,number])[]=p==='volume'?[['litres','cm³',1000],['ml','cm³',1]] as const:[['m','cm',100],['km','m',1000],['kg','g',1000],['litres','ml',1000]] as const;const [big,little,factor]=r.pick(units),value=g>=5?r.int(12,95)/10:r.int(1,9),reverse=r.chance(.5);return numeric(`Convert ${reverse?fmt(value*factor):fmt(value)} ${reverse?little:big} to ${reverse?big:little}.`,reverse?value:value*factor,`1 ${big} = ${factor} ${little}.`,reverse?`${fmt(value*factor)} ÷ ${factor} = ${value} ${big}.`:`${value} × ${factor} = ${fmt(value*factor)} ${little}.`,{unit:reverse?big:little,proof:reverse?calc('/',value*factor,factor):calc('*',value,factor)});}
 case 'solid':{const shapes=g===2?['cube','cuboid','cone','cylinder','sphere']:['cube','cuboid','cone','cylinder','sphere','triangular prism','square pyramid'],s=r.pick(shapes);return choice('Name this solid.',s,r.shuffle(shapes),'Look at the flat faces, curved surfaces and overall shape.',`This solid is a ${s}.`,{picture:{type:'solid',shape:s}});}
 case 'perimeter':{const a=r.int(4,18),b=r.int(2,a-1);if(p==='missing')return numeric(`A rectangle has perimeter ${2*(a+b)} cm and length ${a} cm. What is its width?`,b,'Half the perimeter is length + width. Subtract the length.',`${2*(a+b)} ÷ 2 − ${a} = ${b} cm.`,{picture:{type:'shape',shape:'rectangle',labels:[`${a} cm`,'? cm']},unit:'cm',proof:calc('-',calc('/',2*(a+b),2),a)});if(p==='composite'){const cut=r.int(1,b-1);return numeric('Find the perimeter of this L-shaped garden. The corner notch has equal horizontal and vertical lengths.',2*(a+b),'The missing corner removes two lengths and adds two equal lengths. Walk all the way around.',`The perimeter is the same as the outer rectangle: 2 × (${a} + ${b}) = ${2*(a+b)} cm.`,{picture:{type:'area',a,b,cut},unit:'cm',proof:calc('*',2,calc('+',a,b))});}return numeric('How much fencing goes all the way around this garden?',2*(a+b),'Add all four sides, or double length + width.',`2 × (${a} + ${b}) = ${2*(a+b)} cm.`,{picture:{type:'shape',shape:'rectangle',labels:[`${a} cm`,`${b} cm`]},unit:'cm',proof:calc('*',2,calc('+',a,b))});}
 case 'area':{const a=r.int(5,15),b=r.int(3,10);if(p==='composite'){const cut=r.int(1,Math.min(a,b)-1);return numeric('Find the area of the L-shaped garden.',a*b-cut*cut,'Find the area of the outer rectangle, then subtract the square cut-out.',`${a} × ${b} − ${cut} × ${cut} = ${a*b-cut*cut} cm².`,{picture:{type:'area',a,b,cut},unit:'cm²',proof:calc('-',calc('*',a,b),calc('*',cut,cut))});}if(p==='triangle'){const h=r.int(2,8)*2;return numeric(`A ${a} cm by ${b} cm rectangle has a triangular roof with base ${a} cm and perpendicular height ${h} cm. What is the total area?`,a*b+a*h/2,'Add the rectangle area and the triangle area.',`${a} × ${b} + ½ × ${a} × ${h} = ${a*b+a*h/2} cm².`,{picture:{type:'shape',shape:'house',labels:[`${a} cm`,`${b} cm`,`${h} cm`]},unit:'cm²',proof:calc('+',calc('*',a,b),calc('/',calc('*',a,h),2))});}return numeric('Find the area of the garden.',a*b,'Count the square units by multiplying length by width.',`${a} × ${b} = ${a*b} cm².`,{picture:{type:'area',a,b},unit:'cm²',proof:calc('*',a,b)});}
 case 'angleType':{const degrees=r.pick(p==='measure'?[20,35,50,65,80,95,110,125,140,155]:[30,45,60,90,120,135,150]);if(p==='measure')return numeric('Read the angle using the protractor.',degrees,'Start at zero on the right-hand baseline and follow the inner scale.',`The second ray meets the ${degrees}° mark.`,{picture:{type:'angle',degrees,label:'protractor'},unit:'degrees',proof:degrees});const answer=degrees===90?'A right angle':degrees<90?'Smaller than a right angle':'Larger than a right angle';return choice('Compare this angle with a right angle.',answer,['A right angle','Smaller than a right angle','Larger than a right angle'],'A right angle makes a square corner (90°).',`This ${degrees}° angle is ${answer.toLowerCase()}.`,{picture:{type:'angle',degrees}});}
 case 'parallel':{const shape=r.pick(['parallel','perpendicular','crossing']),ans=shape==='parallel'?'Parallel':shape==='perpendicular'?'Perpendicular':'Neither';return choice('How are these two lines related?',ans,['Parallel','Perpendicular','Neither'],'Parallel lines never meet. Perpendicular lines meet at a right angle.',shape==='parallel'?'These lines stay the same distance apart.':shape==='perpendicular'?'These lines meet at 90°.':'These lines cross, but not at a right angle.',{picture:{type:'shape',shape}});}
 case 'pictureGraph':return barQuestion(false,true);
 case 'barGraph':return barQuestion();
 case 'lineGraph':return barQuestion(true);
 case 'round':{const place=r.pick([10,100,1000]),n=r.int(place,Math.min(g===4||f?100000:max,place*90)),a=Math.round(n/place)*place;return numeric(`Round ${n.toLocaleString('en-SG')} to the nearest ${place}.`,a,'Look at the next digit. Five or more rounds up.',`${n.toLocaleString('en-SG')} rounded to the nearest ${place} is ${a.toLocaleString('en-SG')}.`,{proof:{op:'round',a:n,b:place}});}
 case 'factor':{const n=r.pick([12,18,20,24,28,30,36,40,42,48,56,60,72,84,90]),factors=Array.from({length:n-1},(_,i)=>i+2).filter(k=>n%k===0),yes=r.pick(factors),wrong=Array.from({length:10},(_,i)=>i+2).filter(k=>n%k!==0);return choice(`Which number is a factor of ${n}?`,String(yes),r.shuffle(wrong.map(String)),'A factor divides the number with no remainder.',`${n} ÷ ${yes} = ${n/yes}, with no remainder.`);}
 case 'multiple':{const a=r.pick([2,3,4,5,6]),b=r.pick([3,4,5,6,8,9]),lcm=a*b/gcd(a,b),ans=lcm*r.int(1,3),wrongs=Array.from({length:ans+10},(_,i)=>i+1).filter(n=>n%a!==0||n%b!==0);return choice(`Which is a common multiple of ${a} and ${b}?`,String(ans),r.shuffle(wrongs.map(String)),'The number must be in both multiplication tables.',`${ans} = ${a} × ${ans/a} and ${ans} = ${b} × ${ans/b}.`);}
 case 'decimalPlace':{const n=r.int(1001,99999),places=r.pick([10,100,1000]),whole=n/1000,digit=Math.floor(n/(1000/places))%10;return numeric(`What is the value of the digit in the ${places===10?'tenths':places===100?'hundredths':'thousandths'} place?`,digit/places,'To the right of the decimal point are tenths, hundredths and thousandths.',`${digit} ${places===10?'tenths':places===100?'hundredths':'thousandths'} = ${fmt(digit/places)}.`,{display:whole.toFixed(3),proof:calc('/',digit,places)});}
 case 'decimalCompare':{const a=r.int(1,9999)/1000,b=r.int(1,9999)/1000,ans=a>b?'>':a<b?'<':'=';return choice('Compare these decimals.',ans,['<','>','='],'Line up the decimal points, then compare each place from left to right.',`${fmt(a)} ${ans} ${fmt(b)}.`,{display:`${fmt(a)}  □  ${fmt(b)}`});}
 case 'decimalRound':{const n=r.int(1001,99999)/1000,dp=r.int(0,2),factor=10**dp,a=Math.round(n*factor+1e-9)/factor;return numeric(`Round ${n.toFixed(3)} to ${dp===0?'the nearest whole number':dp+' decimal place'+(dp===1?'':'s')}.`,a,'Look one place to the right of the last digit you will keep.',`${n.toFixed(3)} rounds to ${a.toFixed(dp)}.`,{proof:{op:'round',a:n,b:1/factor}});}
 case 'decimalAdd':{const a=r.int(101,9999),b=r.int(1,a-1),sub=r.chance(.5),ans=(sub?a-b:a+b)/100;return numeric(sub?'Subtract the decimals.':'Add the decimals.',ans,'Line up the decimal points so that equal place values match.',`${fmt(a/100)} ${sub?'−':'+'} ${fmt(b/100)} = ${fmt(ans)}.`,{display:`${fmt(a/100)} ${sub?'−':'+'} ${fmt(b/100)}`,proof:calc('/',calc(sub?'-':'+',a,b),100)});}
 case 'decimalMultiply':case 'decimalDivide':{const div=activity.kind==='decimalDivide',powers=p==='powers',b=powers?r.pick([10,100,1000]):r.int(2,9),a=r.int(1,powers?999:999)/100;const dividend=div&&!powers?a*b:a,ans=div?dividend/b:a*b;return numeric(div?'Divide the decimal.':'Multiply the decimal.',ans,powers?'Track how the value of each digit changes by a factor of 10, 100 or 1000.':'Use whole-number calculation, then check the decimal place value.',`${fmt(dividend)} ${div?'÷':'×'} ${b} = ${fmt(ans)}.`,{display:`${fmt(dividend)} ${div?'÷':'×'} ${b}`,proof:calc(div?'/':'*',dividend,b)});}
 case 'symmetry':{const shape=r.pick(['square','rectangle','equilateral triangle']),ans=shape==='square'?4:shape==='rectangle'?2:3;return numeric(`How many lines of symmetry does this ${shape} have?`,ans,'Imagine folding the shape so that both halves match exactly.',`A ${shape} has ${ans} lines of symmetry.`,{picture:{type:'shape',shape},proof:ans});}
 case 'net':{const valid=r.chance(.5),shift=r.int(0,2),cells: [number,number][]=valid?[[1,0],[1,1],[1,2],[1,3],[0,shift],[2,shift]]:[[0,0],[1,0],[2,0],[0,1],[1,1],[2,1]];return choice('Can these six squares fold into a cube without overlapping?',valid?'Yes':'No',['Yes','No'],'A cube has six faces. Imagine folding along each edge: no two squares may cover the same face.',valid?'The four middle squares wrap around the cube; the side squares close its top and bottom.':'This 2 by 3 arrangement overlaps when folded; it does not close into a cube.',{picture:{type:'net',cells}});}
 case 'pieChart':{const vals=r.shuffle([1,1,2,4]),unit=r.int(2,8)*5,labels=['Reading','Art','Sport','Music'],total=8*unit,k=r.int(0,3),ans=vals[k]*unit;return numeric(`The chart shows ${total} pupils. How many chose ${labels[k].toLowerCase()}?`,ans,'Each small sector is one eighth of the whole group. Use the labelled fraction.',`${vals[k]}/8 × ${total} = ${ans}.`,{picture:{type:'pie',labels,values:vals},proof:calc('*',calc('/',vals[k],8),total)});}
 case 'operations':{const a=r.int(2,12),b=r.int(2,9),c=r.int(2,9),brackets=r.chance(.5),ans=brackets?(a+b)*c:a+b*c;return numeric('Crack the expression. Follow the order of operations.',ans,'Brackets first. Then multiplication and division, then addition and subtraction.',brackets?`First ${a} + ${b} = ${a+b}. Then ${a+b} × ${c} = ${ans}.`:`First ${b} × ${c} = ${b*c}. Then ${a} + ${b*c} = ${ans}.`,{display:brackets?`(${a} + ${b}) × ${c}`:`${a} + ${b} × ${c}`,proof:brackets?calc('*',calc('+',a,b),c):calc('+',a,calc('*',b,c))});}
 case 'percent':{const pct=r.pick([5,10,15,20,25,30,40,50,60,75,80,90]);if(p==='quantity'){const total=r.int(2,20)*20;return numeric(`Find ${pct}% of ${total}.`,pct*total/100,'One percent means one hundredth. Divide by 100, then multiply by the percentage.',`${total} ÷ 100 × ${pct} = ${pct*total/100}.`,{proof:calc('*',calc('/',total,100),pct)});}return numeric('What percentage of this hundred-grid is shaded?',pct,'Percent means out of 100. Count the shaded parts.',`${pct} out of 100 means ${pct}%.`,{picture:{type:'fraction',parts:100,filled:pct},unit:'%',proof:pct});}
 case 'discount':{const cost=r.int(2,20)*20,pct=r.pick([5,10,15,20,25,30,40,50]),ans=cost*(100-pct)/100;return numeric(`A bag costs ${money(cost)} before a ${pct}% discount. What is the sale price?`,ans,'Find the discount amount, then subtract it from the original price.',`${pct}% of ${money(cost)} is ${money(cost*pct/100)}. Sale price = ${money(cost)} − ${money(cost*pct/100)} = ${money(ans)}.`,{unit:'dollars',proof:calc('-',cost,calc('*',cost,calc('/',pct,100)))});}
 case 'rate':{const rate=r.int(2,12),hours=r.int(2,8),reverse=r.chance(.5);return numeric(reverse?`A machine packs ${rate*hours} boxes in ${hours} minutes. How many boxes per minute?`:`A machine packs ${rate} boxes each minute. How many in ${hours} minutes?`,reverse?rate:rate*hours,reverse?'Divide the total by the number of units.':'Multiply amount per unit by number of units.',reverse?`${rate*hours} ÷ ${hours} = ${rate} boxes per minute.`:`${rate} × ${hours} = ${rate*hours} boxes.`,{unit:reverse?'boxes/min':'boxes',proof:reverse?calc('/',rate*hours,hours):calc('*',rate,hours)});}
 case 'triangleArea':{const b=r.int(3,15)*2,h=r.int(3,12);return numeric('Find the area of this triangle.',b*h/2,'Use half × base × perpendicular height.',`½ × ${b} × ${h} = ${b*h/2} cm².`,{picture:{type:'shape',shape:'triangle',labels:[`${b} cm`,`${h} cm`]},unit:'cm²',proof:calc('/',calc('*',b,h),2)});}
 case 'volume':{const a=r.int(2,8),b=r.int(2,6),c=r.int(2,5),liquid=p==='liquid',ans=liquid?a*b*c*1000:a*b*c;return numeric(liquid?'The tank is full. What volume of water does it hold in millilitres?':p==='count'?`There are ${c} layers, each with ${a*b} unit cubes. How many 1 cm³ cubes altogether?`:'Find the volume of this cuboid.',ans,p==='count'?'Count the cubes in each layer, then add the equal layers.':'Multiply length × width × height. For liquid, 1 cm³ = 1 ml.',liquid?`${a*10} × ${b*10} × ${c*10} = ${ans} cm³ = ${ans} ml.`:`${a} × ${b} × ${c} = ${ans} cm³.`,{picture:{type:'solid',shape:'cuboid',a:liquid?a*10:a,b:liquid?b*10:b,c:liquid?c*10:c},unit:liquid?'ml':'cm³',proof:calc('*',calc('*',liquid?a*10:a,liquid?b*10:b),liquid?c*10:c)});}
 case 'angleFacts':{const type=r.pick(['line','point','opposite']),a=r.int(3,15)*10,ans=type==='line'?180-a:type==='point'?360-a:a;return numeric(type==='line'?`Two angles lie on a straight line. One is ${a}°. Find the other.`:type==='point'?`Two angles make one full turn. One is ${a}°. Find the other.`:`Two lines cross. One angle is ${a}°. Find the vertically opposite angle.`,ans,type==='line'?'Angles on a straight line add to 180°.':type==='point'?'Angles around a point add to 360°.':'Vertically opposite angles are equal.',type==='line'?`180 − ${a} = ${ans}°.`:type==='point'?`360 − ${a} = ${ans}°.`:`The opposite angle is also ${a}°.`,{unit:'degrees',proof:type==='opposite'?a:calc('-',type==='line'?180:360,a)});}
 case 'triangleAngle':{const a=r.int(3,8)*10,b=r.int(3,8)*10,ans=180-a-b;return numeric(`A triangle has angles ${a}° and ${b}°. Find the third angle.`,ans,'The angles in every triangle add to 180°.',`180 − ${a} − ${b} = ${ans}°.`,{picture:{type:'shape',shape:'triangle'},unit:'degrees',proof:calc('-',calc('-',180,a),b)});}
 case 'quadrilateral':{const a=r.int(4,13)*10,opposite=r.chance(.5),ans=opposite?a:180-a;return numeric(`One angle of a parallelogram is ${a}°. Find ${opposite?'the opposite':'an adjacent'} angle.`,ans,opposite?'Opposite angles of a parallelogram are equal.':'Adjacent angles of a parallelogram add to 180°.',opposite?`The opposite angle is ${a}°.`:`180 − ${a} = ${ans}°.`,{picture:{type:'shape',shape:'parallelogram'},unit:'degrees',proof:opposite?a:calc('-',180,a)});}
 case 'reversePercent':{const original=r.int(2,30)*20,pct=r.pick([20,25,40,50,60,75,80]),part=original*pct/100;return numeric(`${pct}% of a number is ${part}. What is the original number?`,original,`Find 1% by dividing by ${pct}, then multiply by 100.`,`${part} ÷ ${pct} × 100 = ${original}.`,{proof:calc('*',calc('/',part,pct),100)});}
 case 'percentChange':{const original=r.int(2,20)*20,pct=r.pick([5,10,15,20,25,30,40,50]),up=r.chance(.5),next=original*(100+(up?pct:-pct))/100;return numeric(`A quantity changes from ${original} to ${next}. What is the percentage ${up?'increase':'decrease'}?`,pct,'Divide the change by the original quantity, then multiply by 100.',`${Math.abs(next-original)} ÷ ${original} × 100 = ${pct}%.`,{unit:'%',proof:calc('*',calc('/',Math.abs(next-original),original),100)});}
 case 'ratio':{const a=r.int(1,8),b=r.int(1,9),k=r.int(2,6);if(p==='equivalent')return numeric('Find the missing term.',b*k,`The first term was multiplied by ${k}. Multiply the second term by the same number.`,`${b} × ${k} = ${b*k}.`,{display:`${a} : ${b} = ${a*k} : □`,proof:calc('*',b,k)});const div=gcd(a,b);return choice(`Simplify the ratio ${a*k} : ${b*k}.`,`${a/div}:${b/div}`,[`${a*k}:${b}`,`${a}:${b*k}`,`${a/div+1}:${b/div}`],'Divide both terms by their greatest common factor.',`Divide both terms by ${k*div}: ${a/div} : ${b/div}.`);}
 case 'ratioShare':{const a=r.int(1,5),b=r.int(2,7),c=p==='three'?r.int(1,5):0,unit=r.int(3,15),total=(a+b+c)*unit;return numeric(`${total} stickers are shared by ${c?'Aisha, Ben and Chen':'Aisha and Ben'} in the ratio ${a}:${b}${c?':'+c:''}. How many does Ben get?`,b*unit,'Add the ratio parts. Divide the total by the number of parts, then multiply by Ben’s parts.',`${a+b+c} parts = ${total}. 1 part = ${unit}. Ben gets ${b} × ${unit} = ${b*unit}.`,{proof:calc('*',calc('/',total,a+b+c),b)});}
 case 'algebra':{const a=r.int(2,9),b=r.int(1,12),x=r.int(1,10);if(p==='simplify')return choice(`Simplify ${a}x + ${b}x.`,`${a+b}x`,[`${a*b}x`,`${a+b}`,`${a+b}x²`],'Combine like terms by adding their coefficients.',`${a} groups of x plus ${b} groups of x is ${a+b}x.`);return numeric(`Find the value of ${a}x + ${b} when x = ${x}.`,a*x+b,'Substitute the value of x. Multiply before adding.',`${a} × ${x} + ${b} = ${a*x+b}.`,{proof:calc('+',calc('*',a,x),b)});}
 case 'equation':{const a=r.int(2,9),x=r.int(1,20),b=r.int(1,15),total=a*x+b;return numeric('Solve for x.',x,'Undo the addition first, then divide by the coefficient of x.',`Subtract ${b}: ${a}x = ${total-b}. Divide by ${a}: x = ${x}.`,{display:`${a}x + ${b} = ${total}`,proof:calc('/',calc('-',total,b),a)});}
 case 'circle':{const radius=r.int(1,6)*7,pi=22/7,area=p==='area'||p==='half',fractionPart=p==='half'?.5:p==='quarter'?.25:1;const ans=area?pi*radius*radius*fractionPart:2*pi*radius*fractionPart+(p==='quarter'?2*radius:0);return numeric(p==='half'?`Find the area of a semicircle of radius ${radius} cm. Use π = 22/7.`:p==='quarter'?`Find the perimeter of a quarter-circle of radius ${radius} cm, including its two straight sides. Use π = 22/7.`:`Find the ${area?'area':'circumference'} of a circle of radius ${radius} cm. Use π = 22/7.`,ans,area?'Area = π × radius × radius. Use half for a semicircle.':p==='quarter'?'Find one quarter of the circumference, then add two radii.':'Circumference = 2 × π × radius.',area?`${fractionPart===.5?'½ × ':''}22/7 × ${radius} × ${radius} = ${fmt(ans)} cm².`:p==='quarter'?`¼ × 2 × 22/7 × ${radius} + 2 × ${radius} = ${fmt(ans)} cm.`:`2 × 22/7 × ${radius} = ${fmt(ans)} cm.`,{picture:{type:'shape',shape:p==='half'?'semicircle':p==='quarter'?'quarter-circle':'circle',labels:[`r = ${radius} cm`]},unit:area?'cm²':'cm',proof:area?calc('*',calc('*',calc('/',22,7),calc('*',radius,radius)),fractionPart):calc('+',calc('*',calc('*',2,calc('/',22,7)),calc('*',radius,fractionPart)),p==='quarter'?2*radius:0)});}
 case 'volumeMissing':{const a=r.int(3,12),b=r.int(3,10),h=r.int(3,15),v=a*b*h;return numeric(p==='base'?`A tank has volume ${v} cm³ and base area ${a*b} cm². What is its height?`:`A cuboid has volume ${v} cm³, length ${a} cm and width ${b} cm. Find its height.`,h,'Height = volume ÷ base area.',`${v} ÷ ${a*b} = ${h} cm.`,{unit:'cm',proof:calc('/',v,calc('*',a,b))});}
 case 'average':{const nums=Array.from({length:4},()=>r.int(2,20)*4),total=nums.reduce((a,b)=>a+b,0),avg=total/4;if(p==='total')return numeric(`The average of 4 scores is ${avg}. What is their total?`,total,'Total = average × number of items.',`${avg} × 4 = ${total}.`,{proof:calc('*',avg,4)});if(p==='missing')return numeric(`Four numbers have average ${avg}. Three are ${nums.slice(0,3).join(', ')}. Find the missing number.`,nums[3],'Find the total from the average, then subtract the three known numbers.',`${avg} × 4 − (${nums.slice(0,3).join(' + ')}) = ${nums[3]}.`,{proof:calc('-',calc('*',avg,4),nums.slice(0,3).reduce<Proof>((a,b)=>calc('+',a,b),0))});return numeric('Find the average of these four scores.',avg,'Add the scores, then divide by the number of scores.',`(${nums.join(' + ')}) ÷ 4 = ${avg}.`,{display:nums.join('   ·   '),proof:calc('/',nums.reduce<Proof>((a,b)=>calc('+',a,b),0),4)});}
 case 'story':{if(g<=2){const a=r.int(3,g===1?10:100),b=r.int(2,g===1?9:99),add=r.chance(.5);return numeric(add?`Mei has ${a} stickers. Ravi gives her ${b} more. How many does she have now?`:`Mei has ${a+b} stickers. She gives Ravi ${b}. How many are left?`,add?a+b:a,add?'Start with Mei’s stickers. Join the stickers Ravi gives her to that amount.':'Start with the whole and take away the part given away.',add?`${a} + ${b} = ${a+b} stickers.`:`${a+b} − ${b} = ${a} stickers.`,{proof:add?calc('+',a,b):calc('-',a+b,b)});}if(g<=4){const boxes=r.int(3,8),each=r.int(6,20),given=r.int(2,each),ans=boxes*each-given;return numeric(`A class has ${boxes} boxes of pencils, with ${each} in each box. They give away ${given} pencils. How many remain?`,ans,'First find the total in all boxes. Then subtract the pencils given away.',`${boxes} × ${each} − ${given} = ${ans} pencils.`,{proof:calc('-',calc('*',boxes,each),given)});}if(p==='discount')return makeQuestion({...activity,kind:'discount'},seed,index);if(p==='percent')return makeQuestion({...activity,kind:'reversePercent'},seed,index);if(p==='fraction')return makeQuestion({...activity,kind:'fractionDivide',parameter:'whole'},seed,index);if(g===6)return makeQuestion({...activity,kind:'ratioShare'},seed,index);const d=r.int(3,8),n=r.int(1,d-1),each=r.int(4,12),total=d*each;return numeric(`A baker makes ${total} buns. ${n}/${d} are sold in the morning. How many buns are left?`,total-n*each,'Find the fraction sold, then subtract it from the whole.',`${total} ÷ ${d} × ${n} = ${n*each} sold. ${total} − ${n*each} = ${total-n*each} left.`,{proof:calc('-',total,calc('*',calc('/',total,d),n))});}
 }
 // Exhaustiveness is checked by TypeScript when a new game kind is added.
 const never:never=activity.kind;throw new Error(`Unimplemented activity ${never}`);
}
export function gameSession(activity:Activity,seed:number,count=8):Question[]{const result:Question[]=[],seen=new Set<string>();for(let i=0;i<1000&&result.length<count;i++){const q=makeQuestion(activity,seed,i),key=JSON.stringify([q.prompt,q.display,q.picture,q.answer]);if(!seen.has(key)){seen.add(key);result.push(q);}}return result;}
